### Pandas Series

In [1]:
import numpy as np;
import pandas as pd;

In [4]:
D = {'a':234,'b':532,'c':345};
Series = pd.Series(D, index=['a','b','c']);
Series

a    234
b    532
c    345
dtype: int64

In [5]:
Series = pd.Series([23,542,23,53], index=[1,2,3,4]);
Series

1     23
2    542
3     23
4     53
dtype: int64

In [6]:
D = {'A':433, 'B':633, 'C':432};
Series = pd.Series(D, index=[1,4,5]);
Series

1   NaN
4   NaN
5   NaN
dtype: float64

In [9]:
D = [34,53,23,53,24];
Series = pd.Series(D, copy=False);
Series.iloc[0]=100;
print("Series : \n",Series);
print("D : ",D);

Series : 
 0    100
1     53
2     23
3     53
4     24
dtype: int64
D :  [34, 53, 23, 53, 24]


In [12]:
D = [532,744,723,635,156];
Series = pd.Series(D, copy=True);
Series.iloc[2]=100;
print(Series);
print(D);

0    532
1    744
2    100
3    635
4    156
dtype: int64
[532, 744, 723, 635, 156]


In [18]:
D = np.array([4,34,23,54,23,53]);
Series = pd.Series(D, copy=False);
Series.loc[0] = 100;
print(" D : ",D);
print(" Series : \n",Series);

 D :  [100  34  23  54  23  53]
 Series : 
 0    100
1     34
2     23
3     54
4     23
5     53
dtype: int32


#### Attributes

In [19]:
Series = pd.Series([23,53,23,65,23,23,64,74,23,63]);
Series

0    23
1    53
2    23
3    65
4    23
5    23
6    64
7    74
8    23
9    63
dtype: int64

In [20]:
Series.T

0    23
1    53
2    23
3    65
4    23
5    23
6    64
7    74
8    23
9    63
dtype: int64

In [21]:
Series.array

<PandasArray>
[23, 53, 23, 65, 23, 23, 64, 74, 23, 63]
Length: 10, dtype: int64

In [22]:
Series[0]

23

In [23]:
Series = pd.Series([43,63,23,53,23,56,64,23], name='Age');
Series

0    43
1    63
2    23
3    53
4    23
5    56
6    64
7    23
Name: Age, dtype: int64

In [29]:
Series = pd.Series([[53,23,53],[65,23,64]]);
Series

0    [53, 23, 53]
1    [65, 23, 64]
dtype: object

In [30]:
type(Series[0])

list

In [33]:
Series[0][0:3]

[53, 23, 53]

In [35]:
Series[1][0:2]

[65, 23]

In [36]:
Series = pd.Series([[[34,53,23],[64,23,64]]]);
Series

0    [[34, 53, 23], [64, 23, 64]]
dtype: object

In [37]:
Series = pd.Series([234,53,12,64,12,642,5]);
Series

0    234
1     53
2     12
3     64
4     12
5    642
6      5
dtype: int64

In [38]:
Series.at[0]

234

In [40]:
Series.at[5]

642

In [42]:
Series.attrs

{}

In [44]:
Series.axes

[RangeIndex(start=0, stop=7, step=1)]

In [45]:
Series = pd.Series([34,53,23], index=[2,4,6]);
Series

2    34
4    53
6    23
dtype: int64

In [46]:
Series.index

Int64Index([2, 4, 6], dtype='int64')

In [47]:
Series.axes

[Int64Index([2, 4, 6], dtype='int64')]

In [48]:
Series.dtype

dtype('int64')

In [49]:
Series.dtypes

dtype('int64')

In [50]:
Series.flags

<Flags(allows_duplicate_labels=True)>

In [51]:
Series.hasnans

False

In [58]:
Series = pd.Series([34,534,np.nan,35], index=['a','b','c','d']);
Series

a     34.0
b    534.0
c      NaN
d     35.0
dtype: float64

In [59]:
Series.hasnans

True

In [60]:
Series.iloc[0]

34.0

In [63]:
Series.at['a']

34.0

In [64]:
Series.at['c']

nan

In [66]:
Series.iloc[0:4]

a     34.0
b    534.0
c      NaN
d     35.0
dtype: float64

In [71]:
Series.at['c']

nan

In [72]:
Series.ndim

1

In [73]:
Series.size

4

In [74]:
Series.shape

(4,)

In [75]:
Series.values

array([ 34., 534.,  nan,  35.])

In [76]:
Series.name

In [77]:
Series.nbytes

32

In [107]:
Series.unique()

array([ 34., 534.,  nan,  35.])

In [79]:
Series.is_monotonic_increasing

False

In [80]:
Series.is_monotonic_decreasing

False

In [81]:
Series

a     34.0
b    534.0
c      NaN
d     35.0
dtype: float64

In [82]:
Series.add(3)

a     37.0
b    537.0
c      NaN
d     38.0
dtype: float64

In [83]:
Series.add([34,53,23,53])

a     68.0
b    587.0
c      NaN
d     88.0
dtype: float64

In [87]:
Series.add([34,63,23,53])

a     68.0
b    597.0
c      NaN
d     88.0
dtype: float64

In [90]:
pd.Series([35,67,23,642,23], index=[1,2,3,4,5]).add(pd.Series([34,74,23,23,75], index=[1,2,3,4,5]))

1     69
2    141
3     46
4    665
5     98
dtype: int64

In [91]:
Series

a     34.0
b    534.0
c      NaN
d     35.0
dtype: float64

In [92]:
Series.add([34,53,23,53], fill_value=0)

a     68.0
b    587.0
c     23.0
d     88.0
dtype: float64

In [93]:
pd.Series([34,-4,23,-4,-234]).abs()

0     34
1      4
2     23
3      4
4    234
dtype: int64

In [94]:
Series.add_prefix('S_')

S_a     34.0
S_b    534.0
S_c      NaN
S_d     35.0
dtype: float64

In [96]:
Series.add_suffix('.S')

a.S     34.0
b.S    534.0
c.S      NaN
d.S     35.0
dtype: float64

In [97]:
Series.agg(sum)

603.0

In [99]:
Series.agg([sum, min, max])

sum    603.0
min     34.0
max    534.0
dtype: float64

In [103]:
Series.agg([np.sum, min, max])

sum    603.0
min     34.0
max    534.0
dtype: float64

In [105]:
Series.cumprod()

a        34.0
b     18156.0
c         NaN
d    635460.0
dtype: float64

In [106]:
Series.cumsum()

a     34.0
b    568.0
c      NaN
d    603.0
dtype: float64

In [108]:
Series.max()

534.0

In [109]:
Series.argmax()

1

In [110]:
Series.any()

True

In [111]:
Series.all()

True

In [112]:
pd.Series([False, True]).all()

False

In [116]:
pd.Series(np.zeros((10))).any()

False

In [117]:
pd.Series(np.ones(10)).all()

True

In [118]:
Series.argsort()

a    0
b    2
c   -1
d    1
dtype: int64

In [120]:
Series.sort_index()

a     34.0
b    534.0
c      NaN
d     35.0
dtype: float64

In [121]:
Series.sort_index(ascending=False)

d     35.0
c      NaN
b    534.0
a     34.0
dtype: float64

In [122]:
Series.sort_values()

a     34.0
d     35.0
b    534.0
c      NaN
dtype: float64

In [123]:
Series.sort_values(ascending=False)

b    534.0
d     35.0
a     34.0
c      NaN
dtype: float64

In [124]:
Series.sample()

b    534.0
dtype: float64

In [126]:
Series.sample(3)

a     34.0
c      NaN
b    534.0
dtype: float64

In [4]:
d = {
    ('a','a'):23,
    ('a','b'):63,
    ('a','c'):53,
    ('b','a'):63,
    ('b','b'):15,
    ('b','c'):64
}

df = pd.DataFrame(d, index=['A'])
df

a           b        
    a   b   c   a   b   c
A  23  63  53  63  15  64

In [6]:
d = {
    ('a','a'):{('A','B'):53, ('C','D'):44},
    ('a','b'):{('A','B'):63, ('C','D'):94},
    ('a','c'):{('A','C'):56, ('B','D'):20},
    ('b','a'):{('A','D'):94, ('C','B'):99},
    ('b','b'):{('B','C'):39, ('A','D'):23},
    ('b','c'):{('A','B'):30, ('C','D'):29}
}

df = pd.DataFrame(d)
df

a                 b            
        a     b     c     a     b     c
A B  53.0  63.0   NaN   NaN   NaN  30.0
C D  44.0  94.0   NaN   NaN   NaN  29.0
A C   NaN   NaN  56.0   NaN   NaN   NaN
B D   NaN   NaN  20.0   NaN   NaN   NaN
A D   NaN   NaN   NaN  94.0  23.0   NaN
C B   NaN   NaN   NaN  99.0   NaN   NaN
B C   NaN   NaN   NaN   NaN  39.0   NaN

In [7]:
df['a']

a     b     c
A B  53.0  63.0   NaN
C D  44.0  94.0   NaN
A C   NaN   NaN  56.0
B D   NaN   NaN  20.0
A D   NaN   NaN   NaN
C B   NaN   NaN   NaN
B C   NaN   NaN   NaN

In [8]:
type(df['a'])

pandas.core.frame.DataFrame

In [9]:
df['a']['a']

A  B    53.0
C  D    44.0
A  C     NaN
B  D     NaN
A  D     NaN
C  B     NaN
B  C     NaN
Name: a, dtype: float64

In [11]:
type(df['a']['a'])

pandas.core.series.Series

In [12]:
df['a']['a']['A']

B    53.0
C     NaN
D     NaN
Name: a, dtype: float64

In [13]:
df['a']['a']['A']['C']

nan

In [15]:
df.iloc[0]

a  a    53.0
   b    63.0
   c     NaN
b  a     NaN
   b     NaN
   c    30.0
Name: (A, B), dtype: float64

In [18]:
del df['a']['a']['A']['C']

In [19]:
df

a                 b            
        a     b     c     a     b     c
A B  53.0  63.0   NaN   NaN   NaN  30.0
C D  44.0  94.0   NaN   NaN   NaN  29.0
A C   NaN   NaN  56.0   NaN   NaN   NaN
B D   NaN   NaN  20.0   NaN   NaN   NaN
A D   NaN   NaN   NaN  94.0  23.0   NaN
C B   NaN   NaN   NaN  99.0   NaN   NaN
B C   NaN   NaN   NaN   NaN  39.0   NaN

In [22]:
df['b']['b']['B']['C']

39.0

In [24]:
del df['a']['a']

In [25]:
df

a                 b            
        a     b     c     a     b     c
A B  53.0  63.0   NaN   NaN   NaN  30.0
C D  44.0  94.0   NaN   NaN   NaN  29.0
A C   NaN   NaN  56.0   NaN   NaN   NaN
B D   NaN   NaN  20.0   NaN   NaN   NaN
A D   NaN   NaN   NaN  94.0  23.0   NaN
C B   NaN   NaN   NaN  99.0   NaN   NaN
B C   NaN   NaN   NaN   NaN  39.0   NaN

In [26]:
del df['a']

In [27]:
df

b            
        a     b     c
A B   NaN   NaN  30.0
C D   NaN   NaN  29.0
A C   NaN   NaN   NaN
B D   NaN   NaN   NaN
A D  94.0  23.0   NaN
C B  99.0   NaN   NaN
B C   NaN  39.0   NaN

In [28]:
del df['b']['a']

In [29]:
df

b            
        a     b     c
A B   NaN   NaN  30.0
C D   NaN   NaN  29.0
A C   NaN   NaN   NaN
B D   NaN   NaN   NaN
A D  94.0  23.0   NaN
C B  99.0   NaN   NaN
B C   NaN  39.0   NaN

In [71]:
df = pd.DataFrame([[52,23,53,23],[53,23,63,18],[53,93,92,50]]);
df

0   1   2   3
0  52  23  53  23
1  53  23  63  18
2  53  93  92  50

In [72]:
df.insert(4,4,[49,25,63])

In [73]:
df

0   1   2   3   4
0  52  23  53  23  49
1  53  23  63  18  25
2  53  93  92  50  63

In [74]:
df.insert(0,'A',[45,62,23])

In [75]:
df

A   0   1   2   3   4
0  45  52  23  53  23  49
1  62  53  23  63  18  25
2  23  53  93  92  50  63

In [76]:
df['khan']=[35,63,23]

In [77]:
df

A   0   1   2   3   4  khan
0  45  52  23  53  23  49    35
1  62  53  23  63  18  25    63
2  23  53  93  92  50  63    23

In [41]:
df

A   0   1   2   3   4  khan
0  45  52  23  53  23  49    35
1  62  53  23  63  18  25    63
2  23  53  93  92  50  63    23

In [42]:
(df>0).all()

A       True
0       True
1       True
2       True
3       True
4       True
khan    True
dtype: bool

In [43]:
df.all()

A       True
0       True
1       True
2       True
3       True
4       True
khan    True
dtype: bool

In [44]:
df>0

A     0     1     2     3     4  khan
0  True  True  True  True  True  True  True
1  True  True  True  True  True  True  True
2  True  True  True  True  True  True  True

In [46]:
div , rem = divmod(df, 4)

In [49]:
df

A   0   1   2   3   4  khan
0  45  52  23  53  23  49    35
1  62  53  23  63  18  25    63
2  23  53  93  92  50  63    23

In [47]:
div

A   0   1   2   3   4  khan
0  11  13   5  13   5  12     8
1  15  13   5  15   4   6    15
2   5  13  23  23  12  15     5

In [48]:
rem

A  0  1  2  3  4  khan
0  1  0  3  1  3  1     3
1  2  1  3  3  2  1     3
2  3  1  1  0  2  3     3

In [51]:
rem['A'].unique()

array([1, 2, 3], dtype=int64)

In [55]:
df[rem==1]

A     0     1     2   3     4  khan
0  45.0   NaN   NaN  53.0 NaN  49.0   NaN
1   NaN  53.0   NaN   NaN NaN  25.0   NaN
2   NaN  53.0  93.0   NaN NaN   NaN   NaN

In [56]:
df[rem==2]

A   0   1   2     3   4  khan
0   NaN NaN NaN NaN   NaN NaN   NaN
1  62.0 NaN NaN NaN  18.0 NaN   NaN
2   NaN NaN NaN NaN  50.0 NaN   NaN

In [57]:
df

A   0   1   2   3   4  khan
0  45  52  23  53  23  49    35
1  62  53  23  63  18  25    63
2  23  53  93  92  50  63    23

In [58]:
column = df['khan']
df + column

0      1      2   3   4   A  khan
0  87.0   86.0   76.0 NaN NaN NaN   NaN
1  88.0   86.0   86.0 NaN NaN NaN   NaN
2  88.0  156.0  115.0 NaN NaN NaN   NaN

In [61]:
df + 3

A   0   1   2   3   4  khan
0  48  55  26  56  26  52    38
1  65  56  26  66  21  28    66
2  26  56  96  95  53  66    26

In [63]:
df + pd.Series([10,20,30])

0      1      2   3   4   A  khan
0  62.0   43.0   83.0 NaN NaN NaN   NaN
1  63.0   43.0   93.0 NaN NaN NaN   NaN
2  63.0  113.0  122.0 NaN NaN NaN   NaN

In [67]:
df.add(df, fill_value=0)

A    0    1    2    3    4  khan
0   90  104   46  106   46   98    70
1  124  106   46  126   36   50   126
2   46  106  186  184  100  126    46

In [78]:
df.loc[2,'khan']=np.NaN

In [80]:
df1 = df.copy()

In [81]:
df1

A   0   1   2   3   4  khan
0  45  52  23  53  23  49  35.0
1  62  53  23  63  18  25  63.0
2  23  53  93  92  50  63   NaN

In [83]:
df1.loc[2,'khan']=39;

In [84]:
df.add(df1, fill_value=0)

A    0    1    2    3    4   khan
0   90  104   46  106   46   98   70.0
1  124  106   46  126   36   50  126.0
2   46  106  186  184  100  126   39.0

In [85]:
df.empty

False

In [86]:
df.all()

A       True
0       True
1       True
2       True
3       True
4       True
khan    True
dtype: bool

In [87]:
df.any()

A       True
0       True
1       True
2       True
3       True
4       True
khan    True
dtype: bool

In [88]:
df

A   0   1   2   3   4  khan
0  45  52  23  53  23  49  35.0
1  62  53  23  63  18  25  63.0
2  23  53  93  92  50  63   NaN

In [89]:
(df>30).all()

A       False
0        True
1       False
2        True
3       False
4       False
khan    False
dtype: bool

In [90]:
(df>50).any()

A        True
0        True
1        True
2        True
3       False
4        True
khan     True
dtype: bool

In [94]:
df.any().any()

True

In [96]:
(df>30).all().all()

False

In [97]:
pd.Series([True]).bool()

True

In [98]:
pd.DataFrame([False]).bool()

False

In [99]:
np.nan==np.nan

False

In [101]:
df + df == df * 2

A     0     1     2     3     4   khan
0  True  True  True  True  True  True   True
1  True  True  True  True  True  True   True
2  True  True  True  True  True  True  False

In [102]:
(df+df == df*2).all()    # Because the np.nan != np.nan

A        True
0        True
1        True
2        True
3        True
4        True
khan    False
dtype: bool

In [104]:
(df+df).equals(df*2)    # the method will solve the problem 

True

In [105]:
df1 = pd.DataFrame({"col": ["foo", 0, np.nan]})
df2 = pd.DataFrame({"col": [np.nan, 0, "foo"]}, index=[2, 1, 0])

In [108]:
(df1+df2).equals(df2*2)

False

In [112]:
(df1+df2).equals(df2.sort_index()*2)

True

In [115]:
df == 23

A      0      1      2      3      4   khan
0  False  False   True  False   True  False  False
1  False  False   True  False  False  False  False
2   True  False  False  False  False  False  False

In [119]:
pd.Series(['khan','patan','malak']) == pd.Index(['khan','patan','malek'])

0     True
1     True
2    False
dtype: bool

In [120]:
pd.Series(['khan','patan','malak']) == np.array(['khan','patan','malak'])

0    True
1    True
2    True
dtype: bool