## Numpy Array Method

In [1]:
import numpy as np;

In [6]:
# help(np.random.rand)

arr = np.random.rand(3,5);
arr

array([[0.57374247, 0.98975377, 0.86694882, 0.30707723, 0.83185243],
       [0.29875647, 0.66756154, 0.42725532, 0.16585915, 0.27305158],
       [0.61259516, 0.3944911 , 0.3176903 , 0.44661045, 0.44170102]])

In [7]:
arr.shape

(3, 5)

In [8]:
arr.ndim

2

In [9]:
arr.dtype

dtype('float64')

In [10]:
arr.strides

(40, 8)

In [12]:
np.info(arr)

class:  ndarray
shape:  (3, 5)
strides:  (40, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x26bcefeb7a0
byteorder:  little
byteswap:  False
type: float64


In [14]:
arr.itemsize

8

In [15]:
arr.size

15

In [16]:
arr.flat[0]

0.5737424662336169

In [17]:
arr.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [18]:
type(arr)

numpy.ndarray

In [22]:
arr.nbytes

120

In [23]:
arr.T

array([[0.57374247, 0.29875647, 0.61259516],
       [0.98975377, 0.66756154, 0.3944911 ],
       [0.86694882, 0.42725532, 0.3176903 ],
       [0.30707723, 0.16585915, 0.44661045],
       [0.83185243, 0.27305158, 0.44170102]])

In [24]:
arr.real

array([[0.57374247, 0.98975377, 0.86694882, 0.30707723, 0.83185243],
       [0.29875647, 0.66756154, 0.42725532, 0.16585915, 0.27305158],
       [0.61259516, 0.3944911 , 0.3176903 , 0.44661045, 0.44170102]])

In [25]:
arr.imag

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
print(arr.base)

None


In [29]:
arr.ctypes

In [30]:
arr

array([[0.57374247, 0.98975377, 0.86694882, 0.30707723, 0.83185243],
       [0.29875647, 0.66756154, 0.42725532, 0.16585915, 0.27305158],
       [0.61259516, 0.3944911 , 0.3176903 , 0.44661045, 0.44170102]])

In [31]:
# ndarray.any()
arr.any()

True

In [32]:
arr.any(axis=0)

array([ True,  True,  True,  True,  True])

In [35]:
arr.any(axis=0, keepdims=True)   # the dimensional of output array will be the same as input.

array([[ True,  True,  True,  True,  True]])

In [36]:
arr3d= np.random.randn(2,3,4);

In [37]:
arr3d

array([[[ 0.236985  ,  0.20499273,  0.2375254 , -0.14176958],
        [-1.88735545,  1.54266471,  0.74608548, -1.41129863],
        [ 0.03956334,  1.09501812, -0.03149772, -0.7870021 ]],

       [[ 0.07820965, -1.10742281,  1.13844076, -0.75745   ],
        [-0.76624808, -0.78552842,  0.41716128,  2.06369225],
        [ 0.2312347 , -0.44161334, -0.78954475, -1.5984875 ]]])

In [39]:
arr3d.any()

True

In [40]:
arr3d.any(axis=0)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [50]:
arr3d[1,2] = 0;

In [51]:
arr3d

array([[[ 0.236985  ,  0.20499273,  0.2375254 , -0.14176958],
        [-1.88735545,  1.54266471,  0.74608548, -1.41129863],
        [ 0.03956334,  1.09501812, -0.03149772, -0.7870021 ]],

       [[ 0.07820965, -1.10742281,  1.13844076, -0.75745   ],
        [-0.76624808, -0.78552842,  0.41716128,  2.06369225],
        [ 0.        ,  0.        ,  0.        ,  0.        ]]])

In [52]:
arr3d.any(axis=2)

array([[ True,  True,  True],
       [ True,  True, False]])

In [53]:
arr3d[1,2]

array([0., 0., 0., 0.])

In [54]:
arr

array([[0.57374247, 0.98975377, 0.86694882, 0.30707723, 0.83185243],
       [0.29875647, 0.66756154, 0.42725532, 0.16585915, 0.27305158],
       [0.61259516, 0.3944911 , 0.3176903 , 0.44661045, 0.44170102]])

In [55]:
arr3d

array([[[ 0.236985  ,  0.20499273,  0.2375254 , -0.14176958],
        [-1.88735545,  1.54266471,  0.74608548, -1.41129863],
        [ 0.03956334,  1.09501812, -0.03149772, -0.7870021 ]],

       [[ 0.07820965, -1.10742281,  1.13844076, -0.75745   ],
        [-0.76624808, -0.78552842,  0.41716128,  2.06369225],
        [ 0.        ,  0.        ,  0.        ,  0.        ]]])

In [56]:
# ndarray.all()
arr.all()

True

In [57]:
arr.all(axis=0)

array([ True,  True,  True,  True,  True])

In [58]:
arr.all(axis=1)

array([ True,  True,  True])

In [59]:
arr[0,0].all()

True

In [60]:
arr[0,0]

0.5737424662336169

In [61]:
arr3d.all()

False

In [62]:
arr3d.all(axis=1)

array([[ True,  True,  True,  True],
       [False, False, False, False]])

In [64]:
arr3d.all(axis=2, keepdims=True)

array([[[ True],
        [ True],
        [ True]],

       [[ True],
        [ True],
        [False]]])

In [65]:
arr3d.all(axis=0, keepdims=True)

array([[[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [False, False, False, False]]])

In [66]:
arr3d.all(axis=1, keepdims=True)

array([[[ True,  True,  True,  True]],

       [[False, False, False, False]]])

In [69]:
arr

array([[0.57374247, 0.98975377, 0.86694882, 0.30707723, 0.83185243],
       [0.29875647, 0.66756154, 0.42725532, 0.16585915, 0.27305158],
       [0.61259516, 0.3944911 , 0.3176903 , 0.44661045, 0.44170102]])

In [70]:
arr3d

array([[[ 0.236985  ,  0.20499273,  0.2375254 , -0.14176958],
        [-1.88735545,  1.54266471,  0.74608548, -1.41129863],
        [ 0.03956334,  1.09501812, -0.03149772, -0.7870021 ]],

       [[ 0.07820965, -1.10742281,  1.13844076, -0.75745   ],
        [-0.76624808, -0.78552842,  0.41716128,  2.06369225],
        [ 0.        ,  0.        ,  0.        ,  0.        ]]])

In [68]:
# argmax()
arr.argmax()

1

In [72]:
arr.argmax(axis=0)

array([2, 0, 0, 2, 0], dtype=int64)

In [73]:
arr.argmax(axis=1)

array([1, 1, 0], dtype=int64)

In [74]:
arr3d.argmax()

19

In [75]:
arr3d.argmax(axis=0)

array([[0, 0, 1, 0],
       [1, 0, 0, 1],
       [0, 0, 1, 1]], dtype=int64)

In [76]:
arr3d.argmax(axis=2)

array([[2, 1, 1],
       [2, 3, 0]], dtype=int64)

In [77]:
arr3d.argmax(axis=1)

array([[0, 1, 1, 0],
       [0, 2, 0, 1]], dtype=int64)

In [78]:
# ndarray.argmin()
arr.argmin()

8

In [79]:
arr.argmin(axis=0)

array([1, 2, 2, 1, 1], dtype=int64)

In [80]:
arr.argmin(axis=1)

array([3, 3, 2], dtype=int64)

In [81]:
arr.argmin(axis=None)

8

In [82]:
arr3d.argmin()

4

In [83]:
arr3d.argmin(axis=0)

array([[1, 1, 0, 1],
       [0, 1, 1, 0],
       [1, 1, 0, 0]], dtype=int64)

In [84]:
arr

array([[0.57374247, 0.98975377, 0.86694882, 0.30707723, 0.83185243],
       [0.29875647, 0.66756154, 0.42725532, 0.16585915, 0.27305158],
       [0.61259516, 0.3944911 , 0.3176903 , 0.44661045, 0.44170102]])

In [85]:
arr3d

array([[[ 0.236985  ,  0.20499273,  0.2375254 , -0.14176958],
        [-1.88735545,  1.54266471,  0.74608548, -1.41129863],
        [ 0.03956334,  1.09501812, -0.03149772, -0.7870021 ]],

       [[ 0.07820965, -1.10742281,  1.13844076, -0.75745   ],
        [-0.76624808, -0.78552842,  0.41716128,  2.06369225],
        [ 0.        ,  0.        ,  0.        ,  0.        ]]])

In [88]:
#ndarray.argpartition(kth, axis=-1)

arr.argpartition(3)

array([[3, 0, 4, 2, 1],
       [3, 4, 0, 2, 1],
       [1, 2, 4, 3, 0]], dtype=int64)

In [90]:
arr.partition(3)

In [91]:
arr

array([[0.57374247, 0.30707723, 0.83185243, 0.86694882, 0.98975377],
       [0.27305158, 0.16585915, 0.29875647, 0.42725532, 0.66756154],
       [0.3176903 , 0.3944911 , 0.44170102, 0.44661045, 0.61259516]])

In [92]:
arr.argpartition(1)

array([[1, 0, 2, 3, 4],
       [1, 0, 2, 3, 4],
       [0, 1, 2, 3, 4]], dtype=int64)

In [93]:
arr

array([[0.57374247, 0.30707723, 0.83185243, 0.86694882, 0.98975377],
       [0.27305158, 0.16585915, 0.29875647, 0.42725532, 0.66756154],
       [0.3176903 , 0.3944911 , 0.44170102, 0.44661045, 0.61259516]])

In [94]:
arr.partition(1)

In [95]:
arr

array([[0.30707723, 0.57374247, 0.83185243, 0.86694882, 0.98975377],
       [0.16585915, 0.27305158, 0.29875647, 0.42725532, 0.66756154],
       [0.3176903 , 0.3944911 , 0.44170102, 0.44661045, 0.61259516]])

#### ndarray.astype(dtype, order=’K’, casting=’unsafe’, subok=True, copy=True)
- Copy of the array, cast to a specified type.


In [96]:
arr.dtype

dtype('float64')

In [106]:
arr.astype(dtype=np.float32, order='C', casting='same_kind', subok=True, copy=False)

array([[0.30707723, 0.57374245, 0.83185244, 0.86694884, 0.9897538 ],
       [0.16585915, 0.2730516 , 0.29875648, 0.4272553 , 0.66756153],
       [0.31769028, 0.3944911 , 0.44170102, 0.44661045, 0.61259514]],
      dtype=float32)

In [108]:
arr3d.dtype

dtype('float64')

In [116]:
a = arr3d.astype(dtype=np.int32, order='F', casting='unsafe', subok=False, copy=False);
a

array([[[ 0,  0,  0,  0],
        [-1,  1,  0, -1],
        [ 0,  1,  0,  0]],

       [[ 0, -1,  1,  0],
        [ 0,  0,  0,  2],
        [ 0,  0,  0,  0]]])

In [117]:
a.dtype

dtype('int32')

In [118]:
arr3d.dtype

dtype('float64')

In [119]:
id(a)

2662168202480

In [120]:
id(arr3d)

2662118429136

In [6]:
# ndarray.conj()
# Complex-conjugate all elements.

c_arr = np.array([23+5j, -3-5j, 23+1j, 4-5j]);
print(c_arr);
print(c_arr.dtype);
print(c_arr.size);

# c_arr.con()   change the sign of complex imaginary part
c_arr.conj()

[23.+5.j -3.-5.j 23.+1.j  4.-5.j]
complex128
4


array([23.-5.j, -3.+5.j, 23.-1.j,  4.+5.j])

In [9]:
c_arr = np.arange(10, dtype=np.complex_)
print(c_arr);
print(c_arr.dtype);
print(c_arr.size);

# c_arr.con()   change the sign of complex imaginary part
c_arr.conj()

[0.+0.j 1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j 7.+0.j 8.+0.j 9.+0.j]
complex128
10


array([0.-0.j, 1.-0.j, 2.-0.j, 3.-0.j, 4.-0.j, 5.-0.j, 6.-0.j, 7.-0.j,
       8.-0.j, 9.-0.j])

In [11]:
# ndarray.conjugate

In [12]:
c_arr

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j,
       8.+0.j, 9.+0.j])

In [13]:
c_arr.conjugate()

array([0.-0.j, 1.-0.j, 2.-0.j, 3.-0.j, 4.-0.j, 5.-0.j, 6.-0.j, 7.-0.j,
       8.-0.j, 9.-0.j])

In [14]:
# ndarray.copy(order=’C’)
# Return a copy of the array.

arr = np.arange(40).reshape(4,10);
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [15]:
arr.copy()

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [16]:
arr.copy(order='C')

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [17]:
arr.copy(order='F')

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [18]:
arr.copy(order='K')

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [27]:
arr.flags['C_CONTIGUOUS']

True

In [28]:
arr.flags.c_contiguous

True

In [29]:
# ndarray.cumprod(axis=None, dtype=None, out=None)
# Return the cumulative product of the elements along the given axis.

arr = np.array([[2,4,2],[5,2,6],[6,4,1]]);
print(arr);
print();
print(arr.cumprod())

[[2 4 2]
 [5 2 6]
 [6 4 1]]

[    2     8    16    80   160   960  5760 23040 23040]


In [32]:
print(arr);
print();
print(arr.cumprod(axis=0, dtype=np.int32));

[[2 4 2]
 [5 2 6]
 [6 4 1]]

[[ 2  4  2]
 [10  8 12]
 [60 32 12]]


In [33]:
print(arr);
print();
print(arr.cumprod(axis=1, dtype=np.float16))

[[2 4 2]
 [5 2 6]
 [6 4 1]]

[[ 2.  8. 16.]
 [ 5. 10. 60.]
 [ 6. 24. 24.]]


In [34]:
# ndarray.cumsum(axis=None, dtype=None, out=None)
# Return the cumulative sum of the elements along the given axis.

arr = np.arange(6).reshape(2,3);
print(arr);
print();
print(arr.cumsum());
print();
print(arr.cumsum(axis=0, dtype='e'));
print();
print(arr.cumsum(axis=1, dtype='f'));

[[0 1 2]
 [3 4 5]]

[ 0  1  3  6 10 15]

[[0. 1. 2.]
 [3. 5. 7.]]

[[ 0.  1.  3.]
 [ 3.  7. 12.]]


In [41]:
arr = np.linspace(1, 3, 20, dtype=np.half).reshape(2,2,5);
print(arr);
print(end='\n\n');
print(arr.cumsum(axis=-1));

[[[1.    1.105 1.211 1.315 1.421]
  [1.526 1.632 1.737 1.842 1.947]]

 [[2.053 2.158 2.264 2.37  2.475]
  [2.578 2.684 2.79  2.895 3.   ]]]


[[[ 1.     2.105  3.316  4.633  6.055]
  [ 1.526  3.158  4.895  6.734  8.68 ]]

 [[ 2.053  4.21   6.477  8.84  11.32 ]
  [ 2.578  5.26   8.05  10.94  13.94 ]]]


In [48]:
# ndarray.diagonal(offset=0, axis1=0, axis2=1)
# Return specified diagonals

arr = np.logspace(1,2,12, dtype=np.half).reshape(3,4);
print(arr)
arr.diagonal()

[[ 10.     12.33   15.195  18.73 ]
 [ 23.1    28.48   35.12   43.28 ]
 [ 53.38   65.8    81.1   100.   ]]


array([10.  , 28.48, 81.1 ], dtype=float16)

In [54]:
arr.diagonal(offset=-1, axis1=1, axis2=0)

array([ 12.33,  35.12, 100.  ], dtype=float16)

In [59]:
arr.diagonal(offset=1, axis1=0, axis2=1)

array([ 12.33,  35.12, 100.  ], dtype=float16)

In [61]:
# ndarray.dot(b, out=None)
# Dot product of two arrays.

arr1 = np.identity(3, dtype=np.float32);
arr2 = np.ones((3,3), dtype=np.int32);

arr1.dot(arr2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [64]:
matrix1 = np.arange(1,5,1).reshape(2,2);
matrix2 = np.arange(1,7,1).reshape(2,3);

matrix1.dot(matrix2)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [78]:
# ndarray.fill(value)
# Fill the array with a scalar value.

arr4 = np.empty((3,4));
print(arr4);
arr4.fill(4);
print(arr4)

[[1.         1.09090909 1.18181818 1.27272727]
 [1.36363636 1.45454545 1.54545455 1.63636364]
 [1.72727273 1.81818182 1.90909091 2.        ]]
[[4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]]


In [79]:
arr4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [84]:
arr = np.arange(20).reshape(4,5);
print(arr);
print();
arr.fill(100);
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

[[100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]]


In [87]:
arr

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [88]:
# ndarray.flatten(order=’C’)
# Return a copy of the array collapsed into one dimension.
arr.flatten()

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100])

In [89]:
arr

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [90]:
arr4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [92]:
arr4.flatten()

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

In [93]:
arr = np.array([[2,3],[4,5]]);
print(arr);
print();
print(arr.flatten(order='F'));

[[2 3]
 [4 5]]

[2 4 3 5]


In [94]:
print(arr.flatten(order='C'))

[2 3 4 5]


In [95]:
# ndarray.var(axis=None, dtype=None, out=None, ddof=0, keepdims=False)
# Returns the variance of the array elements, along given axis.

In [96]:
arr = np.arange(10);
arr.var()

8.25

In [98]:
arr = np.linspace(1,2, 20).reshape(2,10);
print(arr.var(axis=0, keepdims=True, dtype='e'));
print(arr.var(axis=0, keepdims=True, dtype='e').size)

[[0.0692 0.0692 0.0692 0.0693 0.0693 0.0693 0.0693 0.0692 0.0692 0.0692]]
10


In [99]:
arr.var(axis=1, keepdims=True, dtype='e')

array([[0.02286],
       [0.02286]], dtype=float16)

In [100]:
# ndarray.mean(axis=None, dtype=None, out=None, keepdims=False)
# Returns the average of the array elements along given axis

In [101]:
# ndarray.cumsum(axis=None, dtype=None, out=None)
# Return the cumulative sum of the elements along the given axis

In [102]:
# ndarray.sum(axis=None, dtype=None, out=None, keepdims=False)
# Return the sum of the array elements over the given axis.

In [106]:
# ndarray.trace(offset=0, axis1=0, axis2=1, dtype=None, out=None)
# Return the sum along diagonals of the array.

arr = np.arange(20, dtype='l').reshape(4,5);
print(arr);
arr.trace(offset=0)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


36

In [107]:
arr.trace(offset=1)

40

In [108]:
arr.trace(offset=-1)

33

In [110]:
arr.trace(offset=-2)

26

In [111]:
arr.trace(offset=-3)

15

In [112]:
arr.trace(offset=2)

24

In [113]:
arr.trace(offset=4)

4

In [115]:
arr.trace(offset=7)

0

In [118]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [119]:
arr.trace(offset=2, dtype=np.float16, axis1=1, axis2=0)

26.0

In [121]:
arr.trace(offset=-2, dtype=np.float16, axis1=1, axis2=0)

24.0

In [137]:
# ndarray.round(decimals=0, out=None)
# Return a with each element rounded to the given number of decimals.

arr = np.linspace(1,20,12)
arr.resize((3,4), refcheck=False);
arr

array([[ 1.        ,  2.72727273,  4.45454545,  6.18181818],
       [ 7.90909091,  9.63636364, 11.36363636, 13.09090909],
       [14.81818182, 16.54545455, 18.27272727, 20.        ]])

In [140]:
# ndarray.ptp(axis=None, out=None)
# Peak to peak (maximum - minimum) value along a given axis.

arr = np.arange(30).reshape(5,6);
print(arr);
print();
print(arr.ptp(axis=0));

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]

[24 24 24 24 24 24]


In [141]:
print(arr.ptp(axis=1))

[5 5 5 5 5]


In [143]:
print(arr.max(axis=0))

[24 25 26 27 28 29]


In [147]:
print(arr.max(axis=1))

[ 5 11 17 23 29]


In [148]:
print(arr.max(axis=0) - arr.min(axis=0))

[24 24 24 24 24 24]


In [154]:
# ndarray.swapaxes(axis1, axis2)
# Return a view of the array with axis1 and axis2 interchanged.

In [155]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [156]:
arr.swapaxes(0,1)

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

In [157]:
arr.swapaxes(1,0)

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

In [162]:
# ndarray.squeeze(axis=None)
# Remove single-dimensional entries from the shape of a.
# Remobe the axis which has size of one.

arr = np.array([[[3],[5],[6]]]);
print(arr);
print();
print(arr.squeeze())

[[[3]
  [5]
  [6]]]

[3 5 6]


In [163]:
arr = np.array([[3,43],[53,43],[34,53]]);
print(arr);
print();
print(arr.squeeze())

[[ 3 43]
 [53 43]
 [34 53]]

[[ 3 43]
 [53 43]
 [34 53]]


In [164]:
arr = np.array([[43],[43],[53]]);
print(arr);
print();
print(arr.squeeze())

[[43]
 [43]
 [53]]

[43 43 53]


In [165]:
arr = np.array([[[74,23,53]],[[34,63,24]]])  #  2 x 1 x 3
print(arr);
print();
print(arr.squeeze());

[[[74 23 53]]

 [[34 63 24]]]

[[74 23 53]
 [34 63 24]]


In [169]:
arr.squeeze(axis=0)

ValueError: cannot select an axis to squeeze out which has size not equal to one

In [170]:
arr.squeeze(axis=1)

array([[74, 23, 53],
       [34, 63, 24]])

In [172]:
# ndarray.take(indices, axis=None, out=None, mode=’raise’)
# Return an array formed from the elements of a at the given indices.

arr = np.arange(20).reshape(4,5);
print(arr);
arr.take([2,4,6,-1])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


array([ 2,  4,  6, 19])

In [173]:
arr.take((0,0))

array([0, 0])

In [175]:
arr.take([(0,0),(1,1)])

array([[0, 0],
       [1, 1]])

In [176]:
arr.take([0,0,0,0,0], axis=0)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [178]:
arr.take([0,0,0,0,0,0], axis=1)

array([[ 0,  0,  0,  0,  0,  0],
       [ 5,  5,  5,  5,  5,  5],
       [10, 10, 10, 10, 10, 10],
       [15, 15, 15, 15, 15, 15]])

In [180]:
arr.take([0,1,2,3], axis=0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [181]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [183]:
# ndarray.put(indices, values, mode=’raise’)
# Set a.flat[n] = values[n] for all n in indices.

arr.put([0,1,2,3], [23,52,12,52]);
arr

array([[23, 52, 12, 52,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [185]:
arr.put((-1,-2,-3,-4,-5), (344,6223,12,512,634));
arr

array([[  23,   52,   12,   52,    4],
       [   5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14],
       [ 634,  512,   12, 6223,  344]])

In [186]:
arr.put([5,6,7,8,9], (300,400,500,6000,700));
arr

array([[  23,   52,   12,   52,    4],
       [ 300,  400,  500, 6000,  700],
       [  10,   11,   12,   13,   14],
       [ 634,  512,   12, 6223,  344]])

In [212]:
# ndarray.choose(choices, out=None, mode=’raise’)
# Use an index array to construct a new array from a set of choices.
# the size of choices must be matched to the index array

In [187]:
choices = [[0, 1, 2, 3], [10, 11, 12, 13],[20, 21, 22, 23], [30, 31, 32, 33]];
np.choose([2, 3, 1, 0], choices)


array([20, 31, 12,  3])

In [208]:
index_arr = np.array([3,2,0,1]);
choice = ([[34,63,23,52], [23,632,235,23], [53,23,63,23], [43,63,23,53]])

index_arr.choose(choice)

array([43, 23, 23, 23])

In [210]:
index_arr = np.array([1,2,0]);
choices = (np.array([95,32,63]), np.array([96,44,100]), np.array([77,29,40]));

index_arr.choose(choices)

array([96, 29, 63])

In [214]:
# ndarray.partition(kth, axis=-1, kind=’introselect’, order=None)
# Return a partitioned copy of an array.
# Perform a partition to move the smallest 3 elements to the left
# (0 to 2) and the rest to the right

arr = np.array([4,1,6,1,6,9,3,5]);
arr.partition(2)
arr

array([1, 1, 3, 4, 6, 9, 6, 5])

In [215]:
arr = np.array([9,5,8,4,2,3,5]);
arr.partition(3);
arr

array([2, 4, 3, 5, 5, 8, 9])