#### Creating Array using different methods

In [2]:
import numpy as np;

***This section covers np.array(), np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace(), dtype***

In [3]:
npArray=np.array([[234,623,623],[634,723,136]],np.int16);

In [4]:
print(npArray);

[[234 623 623]
 [634 723 136]]


In [8]:
for i in range(2):
    for j in range(3):
        print(npArray[i][j]);
        j=j+1;
    i=i+1;

234
623
623
634
723
136


In [10]:
npArray.shape

(2, 3)

In [11]:
npArray.size

6

In [12]:
npArray.dtype

dtype('int16')

In [16]:
npZeros=np.zeros(2);

In [17]:
print(npZeros);

[0. 0.]


In [18]:
print(npZeros.shape);

(2,)


In [19]:
print(npZeros.dtype)

float64


In [20]:
npOnes=np.ones(4);

In [22]:
print(npOnes);

[1. 1. 1. 1.]


In [23]:
npOnes.shape

(4,)

In [25]:
npEmpty= np.empty(5);

In [26]:
print(npEmpty);

[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.38252099e-311
 2.29111232e+251]


In [27]:
print(npEmpty.size);

5


In [28]:
npArange=np.arange(5);

In [29]:
print(npArange);

[0 1 2 3 4]


In [30]:
npArange=np.arange(0,20,4);

In [31]:
print(npArange);

[ 0  4  8 12 16]


In [32]:
npArange=np.arange(1,20);

In [33]:
print(npArange);

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [43]:
npLinspace=np.linspace(0,20,10);  # argument  (start , till, size_of_array)

In [44]:
print(npLinspace);

[ 0.          2.22222222  4.44444444  6.66666667  8.88888889 11.11111111
 13.33333333 15.55555556 17.77777778 20.        ]


In [45]:
print(npLinspace.size);

10


In [47]:
zeros=np.zeros(4,dtype=np.int16);

In [48]:
zeros.dtype

dtype('int16')