### Array Attribute

In [1]:
import numpy as np;

In [33]:
arr = np.linspace(2,4,20, dtype='f2').reshape(4,5);

In [34]:
arr

array([[2.   , 2.105, 2.21 , 2.316, 2.422],
       [2.525, 2.63 , 2.736, 2.842, 2.947],
       [3.053, 3.158, 3.264, 3.37 , 3.475],
       [3.578, 3.684, 3.79 , 3.895, 4.   ]], dtype=float16)

In [35]:
np.info(arr)

class:  ndarray
shape:  (4, 5)
strides:  (10, 2)
itemsize:  2
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x1f5cc96f8e0
byteorder:  little
byteswap:  False
type: float16


In [6]:
arr.T

array([[2.   , 2.525, 3.053, 3.578],
       [2.105, 2.63 , 3.158, 3.684],
       [2.21 , 2.736, 3.264, 3.79 ],
       [2.316, 2.842, 3.37 , 3.895],
       [2.422, 2.947, 3.475, 4.   ]], dtype=float16)

In [7]:
arr

array([[2.   , 2.105, 2.21 , 2.316, 2.422],
       [2.525, 2.63 , 2.736, 2.842, 2.947],
       [3.053, 3.158, 3.264, 3.37 , 3.475],
       [3.578, 3.684, 3.79 , 3.895, 4.   ]], dtype=float16)

In [8]:
arr.ndim

2

In [10]:
arr.shape

(4, 5)

In [11]:
arr.size

20

In [12]:
arr.itemsize

2

In [15]:
arr.nbytes

40

In [16]:
arr.real

array([[2.   , 2.105, 2.21 , 2.316, 2.422],
       [2.525, 2.63 , 2.736, 2.842, 2.947],
       [3.053, 3.158, 3.264, 3.37 , 3.475],
       [3.578, 3.684, 3.79 , 3.895, 4.   ]], dtype=float16)

In [17]:
arr.base

array([2.   , 2.105, 2.21 , 2.316, 2.422, 2.525, 2.63 , 2.736, 2.842,
       2.947, 3.053, 3.158, 3.264, 3.37 , 3.475, 3.578, 3.684, 3.79 ,
       3.895, 4.   ], dtype=float16)

In [18]:
arr.imag

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float16)

In [19]:
arr.strides

(10, 2)

In [20]:
arr.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [25]:
arr

array([[2.   , 2.105, 2.21 , 2.316, 2.422],
       [2.525, 2.63 , 2.736, 2.842, 2.947],
       [3.053, 3.158, 3.264, 3.37 , 3.475],
       [3.578, 3.684, 3.79 , 3.895, 4.   ]], dtype=float16)

In [24]:
for i in arr.flat:
    print(i)

2.0
2.105
2.21
2.316
2.422
2.525
2.63
2.736
2.842
2.947
3.053
3.158
3.264
3.37
3.475
3.578
3.684
3.79
3.895
4.0


In [29]:
arr.flags.writeable

True

In [31]:
arr.flags['WRITEABLE']

True

In [32]:
arr.flat[9]

2.947