In [2]:
import numpy as np;

In [3]:
x=np.array([[2.,5.],[8.,3.]]);
x

array([[2., 5.],
       [8., 3.]])

In [4]:
x.T

array([[2., 8.],
       [5., 3.]])

In [5]:
x.T

array([[2., 8.],
       [5., 3.]])

In [6]:
x

array([[2., 5.],
       [8., 3.]])

In [7]:
print(id(x))

1952543232080


In [8]:
x=x.T

In [9]:
x

array([[2., 8.],
       [5., 3.]])

In [10]:
print(id(x))

1952543231600


In [11]:
x=np.array([1.,2.,4.,5.,6.])

In [12]:
x

array([1., 2., 4., 5., 6.])

In [13]:
x.T

array([1., 2., 4., 5., 6.])

In [14]:
x.data

In [15]:
x.dtype

dtype('float64')

In [16]:
type(x.dtype)

numpy.dtype[float64]