### Preprocessing data in AI

In [1]:
import numpy as np;

In [3]:
from sklearn import preprocessing;

In [19]:
input_data=np.random.rand(4,4);
input_data

array([[0.25259658, 0.62429116, 0.89600401, 0.26396619],
       [0.9520085 , 0.1045731 , 0.69095172, 0.88014331],
       [0.81445627, 0.25764628, 0.89229838, 0.23803003],
       [0.12473778, 0.19908651, 0.81048363, 0.84089616]])

#### Binarization
- This process is used when we want to convert our numerical values into boolean values.
Let's use an inbuilt method to binarize input data using 2.1 as the threshold value.

In [21]:
binarize_data=preprocessing.Binarizer(threshold=0.5).transform(input_data);

In [22]:
binarize_data

array([[0., 1., 1., 0.],
       [1., 0., 1., 1.],
       [1., 0., 1., 0.],
       [0., 0., 1., 1.]])

In [32]:
input_data=np.linspace(-1,1,20).reshape(4,5)

In [33]:
input_data

array([[-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737],
       [-0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158],
       [ 0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421],
       [ 0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ]])

In [34]:
input_data.dtype

dtype('float64')

In [36]:
preprocessing.Binarizer(threshold=0).transform(input_data)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [39]:
input_data=np.empty((5,6));
input_data

array([[9.36641897e-312, 1.01283457e-321, 0.00000000e+000,
        0.00000000e+000, 1.37962320e-306, 1.16097020e-028],
       [1.26087994e-076, 2.80061838e-028, 1.02897634e-071,
        1.04917183e-153, 5.23081515e-143, 1.11622903e+165],
       [3.24866286e-057, 5.02818792e-037, 1.17475197e+165,
        1.70098498e+256, 5.49109388e-143, 1.06396443e+224],
       [3.96041428e+246, 1.16318408e-028, 2.03874192e+184,
        1.16346851e+165, 1.27863367e+165, 7.79853076e-071],
       [1.01848862e+248, 1.16096643e-028, 9.80058441e+252,
        7.50189709e+247, 1.14484251e+243, 2.59903827e-144]])

In [41]:
binarizer=preprocessing.Binarizer(threshold=2);

In [42]:
binarizer.transform(input_data)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 1., 0., 1.],
       [1., 0., 1., 1., 1., 0.],
       [1., 0., 1., 1., 1., 0.]])

### Mean and Standard diviation

In [46]:
np.array([3,5,2,52]).mean()

15.5

In [47]:
np.array([3,5,2,25]).std()

9.443913383762052

In [48]:
np.array([[35,63,23],[73,34,62]]).mean()

48.333333333333336

In [49]:
np.array([[35,63,23],[73,34,62]]).mean(axis=0)

array([54. , 48.5, 42.5])

In [50]:
np.array([[35,63,23],[73,34,62]]).mean(axis=1)

array([40.33333333, 56.33333333])

In [51]:
np.array([[35,63,23],[73,34,62]]).std()

18.417986378055073

In [54]:
np.array([[35,63,23],[73,34,62]]).std(axis=0)

array([19. , 14.5, 19.5])

In [55]:
np.array([[35,63,23],[73,34,62]]).std(axis=1)

array([16.75974012, 16.41814714])

#### Mean Removal

In [56]:
input_data=np.random.randint(low=0, high=100, size=(3,6));

In [57]:
input_data

array([[97, 70,  7, 52, 87, 45],
       [89,  4, 84, 67, 99, 54],
       [67, 28, 25, 84, 67, 16]])

In [58]:
input_data.mean(axis=0)

array([84.33333333, 34.        , 38.66666667, 67.66666667, 84.33333333,
       38.33333333])

In [60]:
input_data.std(axis=0)

array([12.68419839, 27.27636339, 32.88701196, 13.0724477 , 13.19932658,
       16.21384868])

In [61]:
# Remove mean
# scale function perform the following operation on each element in the input array
# scaled_X = (X - mean(X)) / std(X)  

scale_data=preprocessing.scale(input_data);

In [62]:
scale_data

array([[ 0.99861783,  1.31982404, -0.96289279, -1.19844937,  0.20203051,
         0.41117114],
       [ 0.36791183, -1.09985336,  1.37845705, -0.05099785,  1.1111678 ,
         0.96625218],
       [-1.36652966, -0.21997067, -0.41556426,  1.24944721, -1.31319831,
        -1.37742332]])

In [64]:
scale_data.mean(axis=0)

array([ 3.70074342e-16,  3.70074342e-17,  7.40148683e-17, -3.70074342e-16,
        3.70074342e-16, -1.48029737e-16])

In [65]:
scale_data.std(axis=0)

array([1., 1., 1., 1., 1., 1.])

In [68]:
#scaled_X = (X - mean(X)) / std(X)

(input_data[0,0]-input_data.mean(axis=0)[0])/input_data.std(axis=0)[0]

0.99861782933251