## Broadcasting 

- The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. 

In [1]:
import numpy as np;

In [2]:
arr1=np.random.randint(low=1,high=100,size=(3,3))

In [3]:
arr1

array([[37,  9, 17],
       [51, 88, 23],
       [13, 16, 13]])

In [5]:
arr2=np.random.randint(low=1,high=100,size=(3,1))

In [6]:
arr2

array([[16],
       [77],
       [49]])

In [7]:
arr1+arr2

array([[ 53,  25,  33],
       [128, 165, 100],
       [ 62,  65,  62]])

In [8]:
# Example 1

In [13]:
arr1=np.random.randint(low=1,high=100,size=(5,4));
arr2=np.random.randint(low=1,high=100,size=(1,4));
print(arr1);
print(arr2)

[[85 70 78 81]
 [71 84 75 52]
 [68 31  8 51]
 [73 48 57 19]
 [29 94 49 51]]
[[ 9 42 93 34]]


In [15]:
arr1*arr2

array([[ 765, 2940, 7254, 2754],
       [ 639, 3528, 6975, 1768],
       [ 612, 1302,  744, 1734],
       [ 657, 2016, 5301,  646],
       [ 261, 3948, 4557, 1734]])

In [16]:
arr1+arr2

array([[ 94, 112, 171, 115],
       [ 80, 126, 168,  86],
       [ 77,  73, 101,  85],
       [ 82,  90, 150,  53],
       [ 38, 136, 142,  85]])

In [17]:
# Example

In [26]:
arr1=np.zeros((15,3,5));
arr2=np.ones((15,1,5));

In [27]:
arr1

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0.,

In [28]:
arr2

array([[[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]]])

In [29]:
arr1+arr2

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1.,

In [30]:
# Example 3

In [31]:
arr1=np.zeros((6,3,5));
arr2=np.ones((3,5))

In [32]:
arr1

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [33]:
arr2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
arr1*arr2

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [35]:
# Example 

In [36]:
arr1=np.ones((5,3,4));
arr2=np.ones((1,4));

In [37]:
arr1

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [38]:
arr2

array([[1., 1., 1., 1.]])

In [39]:
arr1+arr2

array([[[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]],

       [[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]],

       [[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]],

       [[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]],

       [[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]]])

In [40]:
# Example 4

In [41]:
arr1=np.random.randint(low=0,high=100,size=12).reshape(4,3);
arr2=np.random.randint(low=0,high=100,size=(4,1));

In [42]:
arr1

array([[97, 43, 17],
       [ 4, 89, 55],
       [20, 66, 47],
       [27, 56, 33]])

In [43]:
arr2

array([[75],
       [23],
       [83],
       [37]])

In [44]:
arr1+arr2

array([[172, 118,  92],
       [ 27, 112,  78],
       [103, 149, 130],
       [ 64,  93,  70]])

In [45]:
# Example 5

In [46]:
arr1=np.random.randint(low=0,high=100,size=(3,4));
arr2=np.random.randint(low=0,high=100,size=4)

In [49]:
arr1[:,:,np.newaxis]

array([[[34],
        [ 4],
        [47],
        [71]],

       [[11],
        [32],
        [49],
        [57]],

       [[72],
        [48],
        [ 4],
        [94]]])

In [50]:
arr2

array([86,  2, 19, 67])

In [51]:
arr1[:,:,np.newaxis]+arr2

array([[[120,  36,  53, 101],
        [ 90,   6,  23,  71],
        [133,  49,  66, 114],
        [157,  73,  90, 138]],

       [[ 97,  13,  30,  78],
        [118,  34,  51,  99],
        [135,  51,  68, 116],
        [143,  59,  76, 124]],

       [[158,  74,  91, 139],
        [134,  50,  67, 115],
        [ 90,   6,  23,  71],
        [180,  96, 113, 161]]])

In [52]:
# Axis Practice

In [57]:
arr1

array([[34,  4, 47, 71],
       [11, 32, 49, 57],
       [72, 48,  4, 94]])

In [59]:
np.sum(arr1,axis=-1)

array([156, 149, 218])

In [60]:
np.sum(arr1,axis=0)

array([117,  84, 100, 222])

In [62]:
np.sum(arr1,axis=1)

array([156, 149, 218])

In [63]:
# Example 

### vector quantization

In [91]:
from numpy import array,argmin,sqrt;

In [92]:
observation=array([111.0,188.0]);
codes=np.array([[102.0,203.0],
                [132.0,193.0],
                [45.0,155.0], 
                [57.0,173.0]]);

In [93]:
diff=codes-observation;

In [94]:
diff.shape

(4, 2)

In [95]:
dist=sqrt(sum(diff**2,axis=1));

In [96]:
dist.shape

(4,)

In [97]:
argmin(dist)

0

In [99]:
dist[argmin(dist)]

17.4928556845359