## Copies and Views

### copy

- When a new array is created by duplicating the data buffer as well as the metadata, it is called a copy. Changes made to the copy do not reflect on the original array.

In [2]:
import numpy as np;

### copy() function

In [34]:
arr1=np.random.randint(low=0,high=100,size=(3,5));
arr2=arr1.copy();
print("Array 1 : \n", arr1,end='\n\n');
print("Array 2 : \n",arr2,end='\n\n');

arr2[:]=0;
print("array 2 changed");
print();

print("Array 1 after change : \n",arr1,end='\n\n');
print("Array 2 after change : \n",arr2,end='\n\n');

Array 1 : 
 [[89 16 48 87 56]
 [32 71 65 13 82]
 [19 63 59 92 24]]

Array 2 : 
 [[89 16 48 87 56]
 [32 71 65 13 82]
 [19 63 59 92 24]]

array 2 changed

Array 1 after change : 
 [[89 16 48 87 56]
 [32 71 65 13 82]
 [19 63 59 92 24]]

Array 2 after change : 
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]



### view

- It is possible to access the array differently by just changing certain metadata like stride and dtype without changing the data buffer.
- This creates a new war of looking at the data and the change made to a view reflects in the origional data.

### view() function

In [33]:
arr1=np.random.randint(low=0,high=100,size=(3,5));
arr2=arr1.view();
print("Array 1 : \n", arr1,end='\n\n');
print("Array 2 : \n",arr2,end='\n\n');

arr2[:]=0;
print("array 2 changed");
print();

print("Array 1 after change : \n",arr1,end='\n\n');
print("Array 2 after change : \n",arr2,end='\n\n');

Array 1 : 
 [[97 66 50 42 19]
 [77 29 94 59 34]
 [59 43 45 25 50]]

Array 2 : 
 [[97 66 50 42 19]
 [77 29 94 59 34]
 [59 43 45 25 50]]

array 2 changed

Array 1 after change : 
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

Array 2 after change : 
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]



### Indexing creates view

In [32]:
arr1=np.arange(24).reshape(4,6);
arr2=arr1[0];
print("Array 1: \n",arr1,end='\n\n');
print("Array 2: \n",arr2,end='\n\n');

arr2[:]=0;
print("array 2 changed");
print();

print("Array 1 : \n",arr1,end='\n\n');
print("Array 2 : \n",arr2,end='\n\n');

Array 1: 
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

Array 2: 
 [0 1 2 3 4 5]

array 2 changed

Array 1 : 
 [[ 0  0  0  0  0  0]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

Array 2 : 
 [0 0 0 0 0 0]



In [31]:
arr2=arr1[0:2,:];
print("Array 1 : \n",arr1,end='\n\n');
print("Array 2 : \n",arr2,end='\n\n');

arr2[:]=999;
print("array 2 changed");
print();

print("Array 1 : \n",arr1,end='\n\n');
print("Array 2 : \n",arr2,end='\n\n');

Array 1 : 
 [[ 6 15 60 37]
 [47 79 54 67]
 [ 4 15 55 12]
 [ 7 12 20 90]
 [97  4 10  2]]

Array 2 : 
 [[ 6 15 60 37]
 [47 79 54 67]]

array 2 changed

Array 1 : 
 [[999 999 999 999]
 [999 999 999 999]
 [  4  15  55  12]
 [  7  12  20  90]
 [ 97   4  10   2]]

Array 2 : 
 [[999 999 999 999]
 [999 999 999 999]]



### Advance indexing create copy

In [30]:
arr1=np.random.randint(low=1,high=100,size=(5,4));
arr2=arr1[[0,3]];
print("Array 1 : \n",arr1,end='\n\n');
print("Array 2 : \n",arr2,end='\n\n');

arr2[:]=555;
print("array 2 changed");
print();

print("Array 1 : \n",arr1,end='\n\n');
print("Array 2 : \n",arr2,end='\n\n');

Array 1 : 
 [[ 6 15 60 37]
 [47 79 54 67]
 [ 4 15 55 12]
 [ 7 12 20 90]
 [97  4 10  2]]

Array 2 : 
 [[ 6 15 60 37]
 [ 7 12 20 90]]

array 2 changed

Array 1 : 
 [[ 6 15 60 37]
 [47 79 54 67]
 [ 4 15 55 12]
 [ 7 12 20 90]
 [97  4 10  2]]

Array 2 : 
 [[555 555 555 555]
 [555 555 555 555]]



### Other Operation

#### numpy.reshape() function

- he numpy.reshape function creates a view where possible or a copy otherwise. In most cases, the strides can be modified to reshape the array with a view. However, in some cases where the array becomes non-contiguous (perhaps after a ndarray.transpose operation), the reshaping cannot be done by modifying strides and requires a copy.

In [39]:
arr1=np.array([[12,35,23,64],[87,34,74,34],[14,72,34,84]]);
arr2=arr1.reshape(2,3,2);
print("Array 1 : \n",arr1,end='\n\n');
print("Array 2 : \n",arr2,end='\n\n');

print(arr2.base);          # base object return the origional array

Array 1 : 
 [[12 35 23 64]
 [87 34 74 34]
 [14 72 34 84]]

Array 2 : 
 [[[12 35]
  [23 64]
  [87 34]]

 [[74 34]
  [14 72]
  [34 84]]]

[[12 35 23 64]
 [87 34 74 34]
 [14 72 34 84]]


####  numpy.transpose()

- numpy transpose function return a view of the origional data

In [44]:
arr1=np.array([[12,35,23,64],[87,34,74,34],[14,72,34,84]]);
arr2=arr1.transpose()
print("Array 1 : \n",arr1,end='\n\n');
print("Array 2 : \n",arr2,end='\n\n');

arr2[:]=0;
print("array 2 changed");
print();

print("Array 1 : \n",arr1,end='\n\n');
print("Array 2 : \n",arr2,end='\n\n');

Array 1 : 
 [[12 35 23 64]
 [87 34 74 34]
 [14 72 34 84]]

Array 2 : 
 [[12 87 14]
 [35 34 72]
 [23 74 34]
 [64 34 84]]

array 2 changed

Array 1 : 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Array 2 : 
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]



#### numpy.ravel() function

- ravel function returns a contiguous flattened view of the array wherever possible.

In [59]:
arr1=np.array([[12,35,23,64],[87,34,74,34],[14,72,34,84]]);
arr2=arr1.ravel();
print("Array 1 : \n",arr1,end='\n\n');
print("Array 2 : \n",arr2,end='\n\n');

arr2[:]=0;
print("array 2 changed");
print();

print("Array 1 : \n",arr1,end='\n\n');
print("Array 2 : \n",arr2,end='\n\n');

Array 1 : 
 [[12 35 23 64]
 [87 34 74 34]
 [14 72 34 84]]

Array 2 : 
 [12 35 23 64 87 34 74 34 14 72 34 84]

array 2 changed

Array 1 : 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Array 2 : 
 [0 0 0 0 0 0 0 0 0 0 0 0]



#### numpy.flatten

- this function return always a copy of the array.

In [63]:
arr1=np.array([[12,35,23,64],[87,34,74,34],[14,72,34,84]]);
arr2=arr1.flatten();
print("Array 1 : \n",arr1,end='\n\n');
print("Array 2 : \n",arr2,end='\n\n');

arr2[:]=0;
print("array 2 changed");
print();

print("Array 1 : \n",arr1,end='\n\n');
print("Array 2 : \n",arr2,end='\n\n');

arr2.base is None

Array 1 : 
 [[12 35 23 64]
 [87 34 74 34]
 [14 72 34 84]]

Array 2 : 
 [12 35 23 64 87 34 74 34 14 72 34 84]

array 2 changed

Array 1 : 
 [[12 35 23 64]
 [87 34 74 34]
 [14 72 34 84]]

Array 2 : 
 [0 0 0 0 0 0 0 0 0 0 0 0]



True

### base attribute

- The base attribute of the ndarray makes it easy to tell if an array is a view or a copy. The base attribute of a view returns the original array while it returns None for a copy.