### Creation of ND Array in Numpy

In [1]:
import numpy as np;

#### Using np.array Function

In [2]:
arr1=np.array([12,74,26,83,34,74]);

In [3]:
print(arr1);

[12 74 26 83 34 74]


In [5]:
type(arr1)

numpy.ndarray

In [24]:
arr1.dtype

dtype('int32')

In [25]:
arr2=np.array([[3,5,1,5],[5,4,5,8]],np.int64);

In [26]:
arr2

array([[3, 5, 1, 5],
       [5, 4, 5, 8]], dtype=int64)

In [13]:
type(arr2)

numpy.ndarray

In [27]:
arr2.dtype

dtype('int64')

#### Using np.zeros(()) Funtion

In [28]:
arr3=np.zeros((2,3));

In [29]:
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
type(arr3)

numpy.ndarray

In [56]:
arr3.dtype

dtype('float64')

#### Using np.ones(()) Function

In [31]:
arr4=np.ones((3,3));

In [32]:
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
arr4.dtype

dtype('float64')

#### Using identity() Function

In [35]:
arr5=np.identity(4);

In [36]:
arr5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [57]:
arr5=np.identity(2);

In [58]:
arr5

array([[1., 0.],
       [0., 1.]])

In [59]:
arr5=np.identity(4).reshape(2,8);

In [60]:
arr5

array([[1., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1.]])

#### Using np.arange() Function

In [37]:
arr6=np.arange(10);

In [38]:
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
arr6=np.arange(5,11);

In [40]:
arr6

array([ 5,  6,  7,  8,  9, 10])

In [41]:
arr6=np.arange(0,20,2);

In [42]:
arr6

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [43]:
arr6.shape

(10,)

In [45]:
arr6=np.arange(5,20).reshape(3,5);

In [46]:
arr6

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [47]:
arr6.dtype

dtype('int32')

#### Using copy() Function

In [52]:
arr7=arr2.copy();

In [53]:
arr7 

array([[3, 5, 1, 5],
       [5, 4, 5, 8]], dtype=int64)

In [54]:
arr7=arr2.copy().reshape(4,2);

In [55]:
arr7

array([[3, 5],
       [1, 5],
       [5, 4],
       [5, 8]], dtype=int64)

#### Using linspace() Function

In [63]:
arr8=np.linspace(10,20,10);

In [64]:
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [65]:
arr8[1]-arr8[0]

1.1111111111111107

In [66]:
arr8=np.linspace(11,20,10);

In [67]:
arr8

array([11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [68]:
arr8=np.linspace(20,11,10);

In [69]:
arr8

array([20., 19., 18., 17., 16., 15., 14., 13., 12., 11.])

In [70]:
arr8=np.linspace(16,30,9);

In [71]:
arr8

array([16.  , 17.75, 19.5 , 21.25, 23.  , 24.75, 26.5 , 28.25, 30.  ])

In [72]:
arr8=arr8.reshape(3,3);

In [73]:
arr8

array([[16.  , 17.75, 19.5 ],
       [21.25, 23.  , 24.75],
       [26.5 , 28.25, 30.  ]])