***

## Data Types


**A data type object (an instance of numpy.dtype class) describes how the bytes in the fixed-size block of memory corresponding to an array item should be interpreted. It describes the following aspects of the data:**

1. Type of the data (integer, float, Python object, etc.)
2. Size of the data (how many bytes is in e.g. the integer)
3. Byte order of the data (little-endian or big-endian)
4. If the data type is structured data type, an aggregate of other data types, (e.g., describing an array item consisting of an integer and a float),
    - what are the names of the “fields” of the structure, by which they can be accessed,
    - what is the data-type of each field, and
    - which part of the memory block each field takes
    
5. If the data type is a sub-array, what is its shape and data type.

**Numpy Data types are instances of numpy.dtype class.**

In [1]:
import numpy as np;

In [2]:
data_type = np.dtype(int);     # creating an instance of dtype class
data_type

dtype('int32')

****

### Constucting data types

In [3]:
dt = np.dtype('>i8');        #  '>i8'   represent an integer of 64bit in "big-endian" byte order

In [4]:
dt.byteorder

'>'

In [5]:
dt.name

'int64'

In [6]:
dt.itemsize

8

In [7]:
dt.type

numpy.int64

In [8]:
dt.type == np.int32

False

In [9]:
dt.type == np.int64

True

### Byte order

- Byteorder refer to the order in which the bytes of a multi-byte value are arranged in memory.

#### Two Byte Order in Numpy
- Little-Endian
    - In little-endian byte order, the least significant byte (LSB) is stored at the lowest memory address, while the most significant byte (MSB) is stored at the highest memory address. This is the byte order used by most Intel and AMD processors.
- Big-Endian
    - In big-endian byte order, the most significant byte (MSB) is stored at the lowest memory address, and the least significant byte (LSB) is stored at the highest memory address. This is used by some other processors and networking protocols.
    
- Example
    - For example, let's consider the 16-bit binary number 0101011011001101. In this binary number, the leftmost 8 bits (01010110) represent the most significant byte (MSB), and the rightmost 8 bits (11001101) represent the least significant byte (LSB). When this number is stored in memory, the byte order depends on the system's endianness.

In [10]:
import numpy as np;
little_endian = np.dtype('<i4');   # '<' represent little-endian byte order
big_endian = np.dtype('>i8');      # '>' represent big-endian byte order

print("Little Endian ",little_endian.byteorder);
print("Big Endian ",big_endian.byteorder);

Little Endian  =
Big Endian  >


### numpy.bool_

In [42]:
bool_arr = np.array([True,False,False,True], dtype=bool);
print(bool_arr);
print(bool_arr.dtype);
print(type(bool_arr))

[ True False False  True]
bool
<class 'numpy.ndarray'>


In [155]:
# character code for numpy.bool_  '?'

bool_arr = np.zeros((3,3), '?');
print(bool_arr);
print(bool_arr.size);
print(bool_arr.itemsize);
print(bool_arr.dtype)

[[False False False]
 [False False False]
 [False False False]]
9
1
bool


In [78]:
bool_arr = np.ones((3,3), dtype=np.bool_);
print(bool_arr.dtype);

bool


In [79]:
bool_arr = np.array([('abbas',20,True),('khalid',19,False),('kamran',18,True)], dtype="U10,i2,?");
bool_arr

array([('abbas', 20,  True), ('khalid', 19, False), ('kamran', 18,  True)],
      dtype=[('f0', '<U10'), ('f1', '<i2'), ('f2', '?')])

In [86]:
bool_arr = np.array([('abbas',20,True),('khalid',19,False),('kamran',18,True)], dtype=[('name','U15'),('age',np.int16),('selected',bool)]);
bool_arr

array([('abbas', 20,  True), ('khalid', 19, False), ('kamran', 18,  True)],
      dtype=[('name', '<U15'), ('age', '<i2'), ('selected', '?')])

### numpy.byte

In [31]:
import numpy as np;
byte_arr = np.array([4,3,6,2,7], dtype=np.byte);
print(byte_arr.dtype);
print(byte_arr.size);
print(byte_arr.itemsize);
print(byte_arr.dtype.byteorder)            # byte order is : '|'..   because there is only one byte in numpy.int8 dtype 

int8
5
1
|


In [32]:
# Alias for numpy.byte is numpy.int8;

byte_arr = np.random.randint(low=0, high=100, size=(2,3), dtype=np.int8);
print(byte_arr);
print(byte_arr.dtype);
print(byte_arr.size);
print(byte_arr.itemsize);

[[20 31 76]
 [58 84  2]]
int8
6
1


In [34]:
# character code for numpy.byte   'b'

byte_arr = np.linspace(10,30,20, dtype='b').reshape(4,5);
print(byte_arr);
print(byte_arr.dtype);
print(byte_arr.size);
print(byte_arr.itemsize);
print(byte_arr.dtype.byteorder);

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 30]]
int8
20
1
|


*****

### numpy.ubyte

In [38]:
ubyte_arr = np.array([[45,23,64,23],[34,74,23,64]], dtype=np.ubyte);
print(ubyte_arr);
print(ubyte_arr.size);
print(ubyte_arr.itemsize);
print(ubyte_arr.dtype);

[[45 23 64 23]
 [34 74 23 64]]
8
1
uint8


In [41]:
np.issubdtype(np.ubyte, np.integer)

True

In [57]:
# Alias for numpy.ubyte is numpy.uint8;

ubyte_arr = np.random.randint(low=0, high=100, size=(2,3), dtype=np.uint8);
print(ubyte_arr);
print(ubyte_arr.dtype);
print(ubyte_arr.size);
print(ubyte_arr.itemsize);

[[59 25  3]
 [48 41 15]]
uint8
6
1


In [58]:
# character code for numpy.ubyte    'B'

ubyte_arr=np.arange(22, dtype='B').reshape(2,11);
print(ubyte_arr);
print(ubyte_arr.dtype);
print(ubyte_arr.size);
print(ubyte_arr.itemsize);

[[ 0  1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20 21]]
uint8
22
1


****

### numpy.short

In [59]:
short_arr = np.array([43,42,52,62,26], np.short);
print(short_arr);
print(short_arr.dtype);
print(short_arr.size);
print(short_arr.itemsize);
print(short_arr.dtype.byteorder);

[43 42 52 62 26]
int16
5
2
=


In [66]:
# Alias for numpy.short is numpy.int16;

short_arr = np.random.randint(low=0, high=100, size=(3,3), dtype=np.int16);
print(short_arr);
print(short_arr.dtype);
print(short_arr.size);
print(short_arr.itemsize);
print(short_arr.dtype.byteorder);

[[63 51 75]
 [ 3 19 80]
 [26 11 50]]
int16
9
2
=


In [71]:
# character code for numpy.short      'h'

short_arr=np.arange(10, dtype='h').reshape(2,5);
print(short_arr);
print(short_arr.dtype);
print(short_arr.size);
print(short_arr.itemsize);

[[0 1 2 3 4]
 [5 6 7 8 9]]
int16
10
2


****

### numpy.ushort

In [72]:
ushort_arr = np.array([43,42,52,62,26], np.ushort);
print(ushort_arr);
print(ushort_arr.dtype);
print(ushort_arr.size);
print(ushort_arr.itemsize);
print(ushort_arr.dtype.byteorder);

[43 42 52 62 26]
uint16
5
2
=


In [74]:
# Alias for numpy.ushort is numpy.uint16;

ushort_arr = np.random.randint(low=0, high=100, size=(3,3), dtype=np.uint16);
print(ushort_arr);
print(ushort_arr.dtype);
print(ushort_arr.size);
print(ushort_arr.itemsize);
print(ushort_arr.dtype.byteorder);

[[70 75 83]
 [95 75 92]
 [ 9 23 14]]
uint16
9
2
=


In [75]:
# character code for numpy.short   'H'

short_arr=np.arange(10, dtype='H').reshape(2,5);
print(short_arr);
print(short_arr.dtype);
print(short_arr.size);
print(short_arr.itemsize);

[[0 1 2 3 4]
 [5 6 7 8 9]]
uint16
10
2


In [88]:
np.issubdtype(np.ushort, np.unsignedinteger)

True

In [89]:
np.issubdtype(np.ushort, np.integer)

True

In [91]:
np.issubdtype(np.ushort, np.signedinteger)

False

****

### numpy.intc

In [101]:
intc_arr=np.random.randint(0,100,(4,3), np.intc);
print(intc_arr);
print(intc_arr.size);
print(intc_arr.dtype);
print(intc_arr.itemsize);
print(intc_arr.dtype.byteorder);
print('************');
intc_arr.astype(np.int16)

[[35 13 98]
 [11 93 81]
 [65 78 39]
 [13 39  6]]
12
int32
4
=
************


array([[35, 13, 98],
       [11, 93, 81],
       [65, 78, 39],
       [13, 39,  6]], dtype=int16)

In [104]:
# Alias for np.intc is np.int32

intc_arr=np.identity(3, np.int32);
print(intc_arr);
print(intc_arr.size);
print(intc_arr.dtype);
print(intc_arr.itemsize);
print(intc_arr.dtype.byteorder);

[[1 0 0]
 [0 1 0]
 [0 0 1]]
9
int32
4
=


In [109]:
# character code for np.intc     'i'

intc_arr=np.array([43,434,63,234,63], '>i');
print(intc_arr);
print(intc_arr.size);
print(intc_arr.dtype);
print(intc_arr.itemsize);
print(intc_arr.dtype.byteorder);

[ 43 434  63 234  63]
5
>i4
4
>


******

### numpy.uintc

In [110]:
uintc_arr=np.random.randint(0,100,(4,3), np.uintc);
print(uintc_arr);
print(uintc_arr.size);
print(uintc_arr.dtype);
print(uintc_arr.itemsize);
print(uintc_arr.dtype.byteorder);
print('************');
intc_arr.astype(np.int16)

[[25  3 12]
 [60 15 87]
 [68 14 42]
 [13 10 55]]
12
uint32
4
=
************


array([ 43, 434,  63, 234,  63], dtype=int16)

In [113]:
# Alias for np.uintc is np.uint32

uintc_arr=np.uint32([[12,632,35],[63,223,74],[85,23,63]]);
print(uintc_arr);
print(uintc_arr.size);
print(uintc_arr.dtype);
print(uintc_arr.itemsize);
print(uintc_arr.dtype.byteorder);

[[ 12 632  35]
 [ 63 223  74]
 [ 85  23  63]]
9
uint32
4
=


In [112]:
# character code for np.uintc     'I'

uintc_arr=np.array([43,434,63,234,63], '>I');
print(uintc_arr);
print(uintc_arr.size);
print(uintc_arr.dtype);
print(uintc_arr.itemsize);
print(uintc_arr.dtype.byteorder);

[ 43 434  63 234  63]
5
>u4
4
>


******

### numpy.int_

In [136]:
int_arr=np.array([43,62,23,543], dtype=np.int_);
print(int_arr);
print(int_arr.size);
print(int_arr.dtype);
print(int_arr.itemsize);
print(int_arr.dtype.byteorder);

[ 43  62  23 543]
4
int32
4
=


In [129]:
# Alias for numpy.int_ is np.int64  or np.intp

int_arr=np.identity(4, dtype=np.int64);
print(int_arr);
print(int_arr.size);
print(int_arr.dtype);
print(int_arr.itemsize);
print(int_arr.dtype.byteorder);

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
16
int64
8
=


In [134]:
# character code for numpy.int_      'l'

int_arr=np.arange(12, dtype='l').reshape(2,2,3);
print(int_arr);
print(int_arr.size);
print(int_arr.dtype);
print(int_arr.itemsize);
print(int_arr.dtype.byteorder);

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
12
int32
4
=


************

### numpy.uint

In [137]:
uint_arr=np.array([43,62,23,543], dtype=np.uint);
print(uint_arr);
print(uint_arr.size);
print(uint_arr.dtype);
print(uint_arr.itemsize);
print(uint_arr.dtype.byteorder);

[ 43  62  23 543]
4
uint32
4
=


In [138]:
# Alias for numpy.uint is np.uint64 or np.uintp

uint_arr=np.identity(4, dtype=np.uint64);
print(uint_arr);
print(uint_arr.size);
print(uint_arr.dtype);
print(uint_arr.itemsize);
print(uint_arr.dtype.byteorder);

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
16
uint64
8
=


In [139]:
# character code for numpy.uint  'L'

uint_arr=np.arange(12, dtype='L').reshape(2,2,3);
print(uint_arr);
print(uint_arr.size);
print(uint_arr.dtype);
print(uint_arr.itemsize);
print(uint_arr.dtype.byteorder);

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
12
uint32
4
=


************

### numpy.longlong

In [140]:
longlong=np.random.randint(low=0,high=100,size=(3,4), dtype=np.longlong);
print(longlong);
print(longlong.size);
print(longlong.dtype);
print(longlong.itemsize);
print(longlong.dtype.byteorder);

[[40 97 20 58]
 [95 73 33 56]
 [92  2 75 48]]
12
int64
8
=


In [142]:
# Alias for numpy.longlong is np.int64 

longlong=np.identity(4, dtype=np.int64);
print(longlong);
print(longlong.size);
print(longlong.dtype);
print(longlong.itemsize);
print(longlong.dtype.byteorder);

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
16
int64
8
=


In [144]:
# character code for numpy.longlong  'q'

longlong=np.ones((3,5), '>q');
print(longlong);
print(longlong.size);
print(longlong.dtype);
print(longlong.itemsize);
print(longlong.dtype.byteorder);

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
15
>i8
8
>


******

### numpy.ulonglong

In [145]:
ulonglong=np.random.randint(low=0,high=100,size=(3,4), dtype=np.ulonglong);
print(ulonglong);
print(ulonglong.size);
print(ulonglong.dtype);
print(ulonglong.itemsize);
print(ulonglong.dtype.byteorder);

[[13 97 98 37]
 [93 94 55 17]
 [88  2  2 95]]
12
uint64
8
=


In [154]:
# Alias for numpy.ulonglong is np.uint64 

dt=np.dtype(np.uint64);
print("Byte order of dt : ",dt.byteorder);
dt=dt.newbyteorder('B')
ulonglong=np.identity(4, dtype=dt);
print(ulonglong);
print(ulonglong.size);
print(ulonglong.dtype);
print(ulonglong.itemsize);
print(ulonglong.dtype.byteorder);

Byte order of dt :  =
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
16
>u8
8
>


In [147]:
# character code for numpy.ulonglong  'Q'

ulonglong=np.ones((3,5), '<Q');
print(ulonglong);
print(ulonglong.size);
print(ulonglong.dtype);
print(ulonglong.itemsize);
print(ulonglong.dtype.byteorder);

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
15
uint64
8
=


********

### numpy.half / numpy.float16

In [156]:
half_arr=np.array([43,63.34,634,63.63,734.5], dtype=np.half);

print(half_arr);
print(half_arr.size);
print(half_arr.dtype);
print(half_arr.itemsize);
print(half_arr.dtype.byteorder);

[ 43.    63.34 634.    63.62 734.5 ]
5
float16
2
=


In [169]:
# Alias for numpy.half is np.float16

half_arr=np.float16(np.random.rand(3,4));
print(half_arr);
print(half_arr.size);
print(half_arr.dtype);
print(half_arr.itemsize);
print(half_arr.dtype.byteorder);

[[0.319   0.6934  0.315   0.3293 ]
 [0.9185  0.1427  0.706   0.02278]
 [0.717   0.678   0.255   0.9365 ]]
12
float16
2
=


In [171]:
# character code for numpy.half         'e'

half_arr=np.ones((5,2), '>e');
print(half_arr);
print(half_arr.size);
print(half_arr.dtype);
print(half_arr.itemsize);
print(half_arr.dtype.byteorder);

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
10
>f2
2
>


**********

### numpy.single

In [172]:
single=np.array([4,75,23,63], dtype=np.single);
print(single);
print(single.size);
print(single.dtype);
print(single.itemsize);
print(single.dtype.byteorder);

[ 4. 75. 23. 63.]
4
float32
4
=


In [174]:
# character code for np.single is np.float32

single=np.identity(5, np.float32);
print(single);
print(single.size);
print(single.dtype);
print(single.itemsize);
print(single.dtype.byteorder);

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
25
float32
4
=


In [181]:
# character code for numpy.single   'f'

single=np.arange(1,5,0.2, dtype='<f').reshape(2,5,2);
print(single);
print(single.size);
print(single.dtype);
print(single.itemsize);
print(single.dtype.byteorder);

[[[1.        1.2      ]
  [1.4000001 1.6000001]
  [1.8000002 2.0000002]
  [2.2000003 2.4000003]
  [2.6000004 2.8000004]]

 [[3.0000005 3.2000005]
  [3.4000006 3.6000006]
  [3.8000007 4.000001 ]
  [4.200001  4.4000006]
  [4.600001  4.800001 ]]]
20
float32
4
=


*************

### numpy.double

In [183]:
double=np.linspace(5,10,24, np.double).reshape(2,4,3);
print(double);
print(double.size);
print(double.dtype);
print(double.itemsize);
print(double.dtype.byteorder);

[[[ 5.          5.2173913   5.43478261]
  [ 5.65217391  5.86956522  6.08695652]
  [ 6.30434783  6.52173913  6.73913043]
  [ 6.95652174  7.17391304  7.39130435]]

 [[ 7.60869565  7.82608696  8.04347826]
  [ 8.26086957  8.47826087  8.69565217]
  [ 8.91304348  9.13043478  9.34782609]
  [ 9.56521739  9.7826087  10.        ]]]
24
float64
8
=


In [184]:
# Alias for numpy.double is   np.float64   or np.float_

double=np.float_([[45,63,23,63],[63,62,23,53]]);
print(double);
print(double.size);
print(double.dtype);
print(double.itemsize);
print(double.dtype.byteorder);

[[45. 63. 23. 63.]
 [63. 62. 23. 53.]]
8
float64
8
=


In [185]:
# character code for np.double  is  'd'

double=np.zeros((3,3), dtype='d');
print(double);
print(double.size);
print(double.dtype);
print(double.itemsize);
print(double.dtype.byteorder);

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
9
float64
8
=


**********

### numpy.longdouble

In [187]:
long_double=np.linspace(5,10,24, dtype=np.longdouble).reshape(2,4,3);
print(long_double);
print(long_double.size);
print(long_double.dtype);
print(long_double.itemsize);
print(long_double.dtype.byteorder);

[[[ 5.          5.2173913   5.43478261]
  [ 5.65217391  5.86956522  6.08695652]
  [ 6.30434783  6.52173913  6.73913043]
  [ 6.95652174  7.17391304  7.39130435]]

 [[ 7.60869565  7.82608696  8.04347826]
  [ 8.26086957  8.47826087  8.69565217]
  [ 8.91304348  9.13043478  9.34782609]
  [ 9.56521739  9.7826087  10.        ]]]
24
float64
8
=


In [188]:
# Alias for numpy.longdouble is   np.float128   or np.longfloat

long_double=np.longfloat([[45,63,23,63],[63,62,23,53]]);
print(long_double);
print(long_double.size);
print(long_double.dtype);
print(long_double.itemsize);
print(long_double.dtype.byteorder);

[[45. 63. 23. 63.]
 [63. 62. 23. 53.]]
8
float64
8
=


In [190]:
# character code for np.longdouble  is  'g'

long_double=np.zeros((3,3), dtype='g');
print(long_double);
print(long_double.size);
print(long_double.dtype);
print(long_double.itemsize);
print(long_double.dtype.byteorder);

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
9
float64
8
=


************

### numpy.csingle

### numpy.cdouble

### numpy.clongdouble

### numpy.bytes_
- A byte string.

In [182]:
bytes_arr=np.array(['kamran','waqas','haleem', 'suliman'], dtype=np.bytes_);
print(bytes_arr);
print(bytes_arr.dtype);
print(bytes_arr.size);
print(bytes_arr.itemsize);
print(bytes_arr.dtype.byteorder);

[b'kamran' b'waqas' b'haleem' b'suliman']
|S7
4
7
|


In [185]:
# Alias for numpy.bytes datatype is np.string_

bytes_arr=np.array(['kamran','waqas','haleem', 'suliman'], dtype=np.string_);
print(bytes_arr);
print(bytes_arr.dtype);
print(bytes_arr.size);
print(bytes_arr.itemsize);
print(bytes_arr.dtype.byteorder);

[b'kamran' b'waqas' b'haleem' b'suliman']
|S7
4
7
|


In [176]:
# character code for numpy.bytes is    'S'

bytes_arr=np.array(['kamran','waqas','haleem', 'suliman'], 'S');
print(bytes_arr);
print(bytes_arr.dtype);
print(bytes_arr.size);
print(bytes_arr.itemsize);
print(bytes_arr.dtype.byteorder);

[b'kamran' b'waqas' b'haleem' b'suliman']
|S7
4
7
|


In [211]:
bytes_arr=np.array([b'\x00\x01\x02', b'\x10\x11\x12'], dtype=np.bytes_);   # \x00 represent a two digit hexadecimal value
print(bytes_arr);
print(bytes_arr.dtype);
print(bytes_arr.size);
print(bytes_arr.itemsize);
print(bytes_arr.dtype.byteorder);

[b'\x00\x01\x02' b'\x10\x11\x12']
|S3
2
3
|


********************

### numpy.str_
- A unicode String.

In [183]:
unicode=np.array(['orange','banana','apricote❤'], dtype=np.str_);    #  unicode of heart : '\u2764'
print(unicode);
print(unicode.dtype);
print(unicode.itemsize);
print(unicode.size);
print(unicode.dtype.byteorder);

['orange' 'banana' 'apricote❤']
<U9
36
3
=


In [187]:
unicode=np.array(['orange','banana','\u2764apricote'], dtype=np.unicode_);
print(unicode);
print(unicode.dtype);
print(unicode.itemsize);
print(unicode.size);
print(unicode.dtype.byteorder);

['orange' 'banana' '❤apricote']
<U9
36
3
=


In [179]:
unicode=np.array(['orange','banana','apricote'], dtype='U');
print(unicode);
print(unicode.dtype);
print(unicode.itemsize);
print(unicode.size);
print(unicode.dtype.byteorder);

['orange' 'banana' 'apricote']
<U8
32
3
=


In [188]:
unicode=np.array(['❤','😂','🤣','♻','♥','🌹','🔥','🤦','✰','♤']);
print(unicode);
print(unicode.dtype)

['❤' '😂' '🤣' '♻' '♥' '🌹' '🔥' '🤦' '✰' '♤']
<U1


In [202]:
unicode=np.array(['\u2764','\U0001f602','\U0001f923','\u267b','\u2665','\U0001f339','\U0001f525','\U0001f926','\u2730','\u2664'], dtype='U');
print(unicode);
print(unicode.dtype);
print(unicode.itemsize);

['❤' '😂' '🤣' '♻' '♥' '🌹' '🔥' '🤦' '✰' '♤']
<U1
4


***********

### Numpy ndarray Datatypes

- np.bool_

In [12]:
import numpy as np;

In [13]:
i=np.array(4);

In [14]:
i.dtype

dtype('int32')

In [15]:
i.shape

()

In [16]:
i.ndim

0

In [17]:
i.size

1

In [18]:
isinstance(i,np.integer)

False

In [19]:
type(i)

numpy.ndarray

In [20]:
s=np.array("hi there");
print(s.dtype);
print(s.ndim);
print(s.shape);
print(s.size)

<U8
0
()
1


In [21]:
isinstance(4, np.integer)

False

In [22]:
type(s)

numpy.ndarray

In [23]:
s1=np.float32(34);
print(s1.dtype);
print(s1.ndim);
print(s1.size);
print(s1.shape)

float32
0
1
()


In [24]:
f16=np.float16(0.1);
f32=np.float32(f16);
f64=np.float64(f16);

print(f16==f32==f64)

f16,f32,f64

True


(0.1, 0.099975586, 0.0999755859375)

In [25]:
sc=np.array([('khan',34)], dtype=[('name','|U5'),('marks',int)])

In [26]:
sc

array([('khan', 34)], dtype=[('name', '<U5'), ('marks', '<i4')])

In [27]:
type(sc)

numpy.ndarray

In [28]:
type(sc[0])

numpy.void

In [171]:
sclr=np.int_(34);
print("Scalar : ",sclr);
print("Dtype : ",sclr.dtype);
print("Size : ",sclr.size);
print("Itemsize : ",sclr.itemsize);
print("Shape : ",sclr.shape);
print("ndim : ",sclr.ndim);
#print("Flags : ",sclr.flags);
print("Strides : ",sclr.strides);
print("Data : ",sclr.data);
print("Real : ",sclr.real);
print("Imag : ",sclr.imag);
print("T : ",sclr.T);
print("flat : ",sclr.flat);
print("Base : ",sclr.base);

Scalar :  34
Dtype :  int32
Size :  1
Itemsize :  4
Shape :  ()
ndim :  0
Strides :  ()
Data :  <memory at 0x0000020782FB7880>
Real :  34
Imag :  0
T :  34
flat :  <numpy.flatiter object at 0x0000020781272CF0>
Base :  None


In [162]:
a=np.array([[43,52,52,42],[45,23,62,23]])

In [168]:
a[slice(None,None,1),slice(None,None,2)]

array([[43, 52],
       [45, 62]])