In [1]:
import numpy as np;

### newaxis

In [26]:
arr1=np.arange(5);

In [5]:
arr1

array([0, 1, 2, 3, 4])

In [7]:
arr1[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [8]:
arr1[np.newaxis,:]

array([[0, 1, 2, 3, 4]])

In [9]:
arr1[:,np.newaxis]+arr1[np.newaxis,:]

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [10]:
arr1

array([0, 1, 2, 3, 4])

In [11]:
arr1[np.newaxis,:].shape

(1, 5)

In [12]:
arr1=np.arange(12).reshape(2,6);

In [13]:
arr1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [14]:
arr1[np.newaxis,:,:]

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]])

In [15]:
arr1[:,np.newaxis,:]

array([[[ 0,  1,  2,  3,  4,  5]],

       [[ 6,  7,  8,  9, 10, 11]]])

In [16]:
arr1[:,:,np.newaxis]

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]]])

### Ellipsis

In [17]:
arr1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [19]:
arr1[...,0]                    ## this means that i don't care about previous indices i care about last indix

array([0, 6])

In [21]:
arr1[0,...]                    ## i just care about first index

array([0, 1, 2, 3, 4, 5])

In [22]:
arr1.shape=(2,2,3);

In [23]:
arr1

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [25]:
arr1[...,2]

array([[ 2,  5],
       [ 8, 11]])

In [50]:
arr1D=np.random.randint(low=0,high=100,size=50);

In [51]:
arr1D

array([51, 74, 56, 39, 94, 91, 25, 84, 76, 36, 88, 85, 69, 52, 71,  0, 78,
        7, 93, 42, 35,  6, 32, 89, 44, 72, 95,  4, 15, 20, 19, 36, 17,  1,
        2,  0, 35, 24, 97, 28, 42, 95, 34, 19,  6, 94, 89, 56, 12, 18])

In [52]:
arr1D[0]

51

In [53]:
arr1D[-1]

18

In [54]:
arr1D[[0,1,2,3,4,5,6]]

array([51, 74, 56, 39, 94, 91, 25])

In [55]:
arr1D[[-1,-2,-3,-4,-5]]

array([18, 12, 56, 89, 94])

In [56]:
obj=np.array([4,5,20,23,29,40,42,49])
arr1D[obj]

array([94, 91, 35, 89, 20, 42, 34, 18])

In [57]:
arr1D[np.array([5,2,2,6,3,7,2])]

array([91, 56, 56, 25, 39, 84, 56])

In [58]:
arr1D[0:30]

array([51, 74, 56, 39, 94, 91, 25, 84, 76, 36, 88, 85, 69, 52, 71,  0, 78,
        7, 93, 42, 35,  6, 32, 89, 44, 72, 95,  4, 15, 20])

In [59]:
arr1D[:20]

array([51, 74, 56, 39, 94, 91, 25, 84, 76, 36, 88, 85, 69, 52, 71,  0, 78,
        7, 93, 42])

In [60]:
arr1D[:15:-1]

array([18, 12, 56, 89, 94,  6, 19, 34, 95, 42, 28, 97, 24, 35,  0,  2,  1,
       17, 36, 19, 20, 15,  4, 95, 72, 44, 89, 32,  6, 35, 42, 93,  7, 78])

In [61]:
arr1D[15::-1]

array([ 0, 71, 52, 69, 85, 88, 36, 76, 84, 25, 91, 94, 39, 56, 74, 51])

In [62]:
arr1D[arr1D<50]

array([39, 25, 36,  0,  7, 42, 35,  6, 32, 44,  4, 15, 20, 19, 36, 17,  1,
        2,  0, 35, 24, 28, 42, 34, 19,  6, 12, 18])

In [63]:
arr1D[(arr1D<50) & (arr1D%2==0)]

array([36,  0, 42,  6, 32, 44,  4, 20, 36,  2,  0, 24, 28, 42, 34,  6, 12,
       18])

In [64]:
arr1D[True,False,True,False]

array([], shape=(0, 50), dtype=int32)

In [66]:
arr1D<50

array([False, False, False,  True, False, False,  True, False, False,
        True, False, False, False, False, False,  True, False,  True,
       False,  True,  True,  True,  True, False,  True, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True, False,  True,  True,  True,
       False, False, False,  True,  True])

In [72]:
arr1D[True]

array([[51, 74, 56, 39, 94, 91, 25, 84, 76, 36, 88, 85, 69, 52, 71,  0,
        78,  7, 93, 42, 35,  6, 32, 89, 44, 72, 95,  4, 15, 20, 19, 36,
        17,  1,  2,  0, 35, 24, 97, 28, 42, 95, 34, 19,  6, 94, 89, 56,
        12, 18]])

In [73]:
arr1D[slice(2,19,1)]

array([56, 39, 94, 91, 25, 84, 76, 36, 88, 85, 69, 52, 71,  0, 78,  7, 93])

In [74]:
arr1D[slice(None,None,-1)]

array([18, 12, 56, 89, 94,  6, 19, 34, 95, 42, 28, 97, 24, 35,  0,  2,  1,
       17, 36, 19, 20, 15,  4, 95, 72, 44, 89, 32,  6, 35, 42, 93,  7, 78,
        0, 71, 52, 69, 85, 88, 36, 76, 84, 25, 91, 94, 39, 56, 74, 51])

In [78]:
arr3D=arr1D[:].reshape(2,5,5)

In [79]:
arr3D

array([[[51, 74, 56, 39, 94],
        [91, 25, 84, 76, 36],
        [88, 85, 69, 52, 71],
        [ 0, 78,  7, 93, 42],
        [35,  6, 32, 89, 44]],

       [[72, 95,  4, 15, 20],
        [19, 36, 17,  1,  2],
        [ 0, 35, 24, 97, 28],
        [42, 95, 34, 19,  6],
        [94, 89, 56, 12, 18]]])

In [80]:
arr3D[1,1,:]

array([19, 36, 17,  1,  2])

In [81]:
arr3D[1]

array([[72, 95,  4, 15, 20],
       [19, 36, 17,  1,  2],
       [ 0, 35, 24, 97, 28],
       [42, 95, 34, 19,  6],
       [94, 89, 56, 12, 18]])

In [82]:
arr3D[0,-1]

array([35,  6, 32, 89, 44])

In [83]:
arr3D

array([[[51, 74, 56, 39, 94],
        [91, 25, 84, 76, 36],
        [88, 85, 69, 52, 71],
        [ 0, 78,  7, 93, 42],
        [35,  6, 32, 89, 44]],

       [[72, 95,  4, 15, 20],
        [19, 36, 17,  1,  2],
        [ 0, 35, 24, 97, 28],
        [42, 95, 34, 19,  6],
        [94, 89, 56, 12, 18]]])

In [84]:
arr3D[np.array([0,0,0,1,1]),np.array([2,3,4,0,1])]

array([[88, 85, 69, 52, 71],
       [ 0, 78,  7, 93, 42],
       [35,  6, 32, 89, 44],
       [72, 95,  4, 15, 20],
       [19, 36, 17,  1,  2]])

In [85]:
arr3D[(slice(1,None,-1),slice(None,None,-1))]

array([[[94, 89, 56, 12, 18],
        [42, 95, 34, 19,  6],
        [ 0, 35, 24, 97, 28],
        [19, 36, 17,  1,  2],
        [72, 95,  4, 15, 20]],

       [[35,  6, 32, 89, 44],
        [ 0, 78,  7, 93, 42],
        [88, 85, 69, 52, 71],
        [91, 25, 84, 76, 36],
        [51, 74, 56, 39, 94]]])

In [86]:
arr3D[(slice(None,None,-1),slice(None,None,-1),slice(None,None,-1))]

array([[[18, 12, 56, 89, 94],
        [ 6, 19, 34, 95, 42],
        [28, 97, 24, 35,  0],
        [ 2,  1, 17, 36, 19],
        [20, 15,  4, 95, 72]],

       [[44, 89, 32,  6, 35],
        [42, 93,  7, 78,  0],
        [71, 52, 69, 85, 88],
        [36, 76, 84, 25, 91],
        [94, 39, 56, 74, 51]]])

In [87]:
arr3D[arr3D<50]

array([39, 25, 36,  0,  7, 42, 35,  6, 32, 44,  4, 15, 20, 19, 36, 17,  1,
        2,  0, 35, 24, 28, 42, 34, 19,  6, 12, 18])

In [91]:
arr3D

array([[[51, 74, 56, 39, 94],
        [91, 25, 84, 76, 36],
        [88, 85, 69, 52, 71],
        [ 0, 78,  7, 93, 42],
        [35,  6, 32, 89, 44]],

       [[72, 95,  4, 15, 20],
        [19, 36, 17,  1,  2],
        [ 0, 35, 24, 97, 28],
        [42, 95, 34, 19,  6],
        [94, 89, 56, 12, 18]]])

In [89]:
d=np.array([[0,0,0,0],[1,1,1,1]])
rows=np.array([[0,0,4,4],[0,0,4,4]])
columns=np.array([[0,4,0,4],[0,4,0,4]])
arr3D[d,rows,columns]

array([[51, 94, 35, 44],
       [72, 20, 94, 18]])