### Fancy Indexing

In [2]:
import numpy as np;

In [3]:
arr=np.arange(24).reshape(4,6);

In [4]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [5]:
arr[[0,2,3]]

array([[ 0,  1,  2,  3,  4,  5],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [7]:
arr[[0,3],[3,4]]

array([ 3, 22])

In [11]:
arr[[0,1,2],[2,4,5]]

array([ 2, 10, 17])

In [15]:
arr[[3]]

array([[18, 19, 20, 21, 22, 23]])

### Indexing using boolean arrays

In [16]:
arr1=np.random.randint(low=0,high=100,size=20).reshape(4,5);

In [17]:
arr1

array([[33, 58, 60, 15, 69],
       [66, 10, 89, 68, 56],
       [71, 61, 63, 85,  9],
       [ 9, 19, 67, 15, 91]])

In [18]:
arr1>40

array([[False,  True,  True, False,  True],
       [ True, False,  True,  True,  True],
       [ True,  True,  True,  True, False],
       [False, False,  True, False,  True]])

In [19]:
arr1[arr1>40]

array([58, 60, 69, 66, 89, 68, 56, 71, 61, 63, 85, 67, 91])

In [20]:
arr1[(arr1>40) & (arr1%2==0)]

array([58, 60, 66, 68, 56])

In [23]:
arr1[(arr1>30) & (arr1%2==0)]=0

In [24]:
arr1

array([[33,  0,  0, 15, 69],
       [ 0, 10, 89,  0,  0],
       [71, 61, 63, 85,  9],
       [ 9, 19, 67, 15, 91]])