In [1]:
import numpy as np;

In [2]:
arr=np.random.randint(low=0,high=100,size=(4,4,5))

In [3]:
arr

array([[[39, 96,  6, 45, 40],
        [27,  5, 13, 52, 34],
        [69, 57, 29, 45, 75],
        [26, 58, 29,  2, 47]],

       [[82, 36, 55, 86, 55],
        [68, 72, 64, 54, 97],
        [ 8, 25, 17, 85, 18],
        [81,  5, 22, 15, 32]],

       [[41,  6,  9, 51, 25],
        [ 9, 98, 72, 45,  0],
        [41, 15, 87, 63, 98],
        [47, 48, 86, 52, 97]],

       [[25, 71, 76, 48, 41],
        [52,  1, 30, 30, 83],
        [30, 64, 84, 44, 67],
        [12,  2, 84, 71, 93]]])

In [4]:
arr[0,2:4]

array([[69, 57, 29, 45, 75],
       [26, 58, 29,  2, 47]])

In [5]:
arr[np.newaxis,0,2:4]

array([[[69, 57, 29, 45, 75],
        [26, 58, 29,  2, 47]]])

In [6]:
arr[0,np.newaxis,2:4]

array([[[69, 57, 29, 45, 75],
        [26, 58, 29,  2, 47]]])

In [7]:
arr[0,2:4,np.newaxis]

array([[[69, 57, 29, 45, 75]],

       [[26, 58, 29,  2, 47]]])

In [8]:
arr[0,2:4,np.newaxis].shape

(2, 1, 5)

In [9]:
arr[0,2:4,np.newaxis,np.newaxis]

array([[[[69, 57, 29, 45, 75]]],


       [[[26, 58, 29,  2, 47]]]])

In [10]:
arr[(slice(1,2,1),slice(2,5,1))]

array([[[ 8, 25, 17, 85, 18],
        [81,  5, 22, 15, 32]]])

In [11]:
arr

array([[[39, 96,  6, 45, 40],
        [27,  5, 13, 52, 34],
        [69, 57, 29, 45, 75],
        [26, 58, 29,  2, 47]],

       [[82, 36, 55, 86, 55],
        [68, 72, 64, 54, 97],
        [ 8, 25, 17, 85, 18],
        [81,  5, 22, 15, 32]],

       [[41,  6,  9, 51, 25],
        [ 9, 98, 72, 45,  0],
        [41, 15, 87, 63, 98],
        [47, 48, 86, 52, 97]],

       [[25, 71, 76, 48, 41],
        [52,  1, 30, 30, 83],
        [30, 64, 84, 44, 67],
        [12,  2, 84, 71, 93]]])

In [14]:
a=arr[0,0]

In [15]:
a

array([100,  96,   6,  45,  40])

In [16]:
a[:]=[11,22,33,44,55]

In [17]:
a

array([11, 22, 33, 44, 55])

In [18]:
arr

array([[[11, 22, 33, 44, 55],
        [27,  5, 13, 52, 34],
        [69, 57, 29, 45, 75],
        [26, 58, 29,  2, 47]],

       [[82, 36, 55, 86, 55],
        [68, 72, 64, 54, 97],
        [ 8, 25, 17, 85, 18],
        [81,  5, 22, 15, 32]],

       [[41,  6,  9, 51, 25],
        [ 9, 98, 72, 45,  0],
        [41, 15, 87, 63, 98],
        [47, 48, 86, 52, 97]],

       [[25, 71, 76, 48, 41],
        [52,  1, 30, 30, 83],
        [30, 64, 84, 44, 67],
        [12,  2, 84, 71, 93]]])

In [19]:
arr1=arr[np.array([0,1]),np.array([2,2])]

In [20]:
arr1

array([[69, 57, 29, 45, 75],
       [ 8, 25, 17, 85, 18]])

In [21]:
arr1[1]=np.arange(5)

In [22]:
arr1

array([[69, 57, 29, 45, 75],
       [ 0,  1,  2,  3,  4]])

In [24]:
arr

array([[[11, 22, 33, 44, 55],
        [27,  5, 13, 52, 34],
        [69, 57, 29, 45, 75],
        [26, 58, 29,  2, 47]],

       [[82, 36, 55, 86, 55],
        [68, 72, 64, 54, 97],
        [ 8, 25, 17, 85, 18],
        [81,  5, 22, 15, 32]],

       [[41,  6,  9, 51, 25],
        [ 9, 98, 72, 45,  0],
        [41, 15, 87, 63, 98],
        [47, 48, 86, 52, 97]],

       [[25, 71, 76, 48, 41],
        [52,  1, 30, 30, 83],
        [30, 64, 84, 44, 67],
        [12,  2, 84, 71, 93]]])

In [25]:
arr1

array([[69, 57, 29, 45, 75],
       [ 0,  1,  2,  3,  4]])

In [26]:
arr2=arr1[slice(0,1,1)]

In [27]:
arr2

array([[69, 57, 29, 45, 75]])

In [28]:
arr2[:]=0

In [29]:
arr2

array([[0, 0, 0, 0, 0]])

In [30]:
arr1

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4]])

In [31]:
del arr2

In [33]:
arr2=arr1[arr1==0]

In [34]:
arr2

array([0, 0, 0, 0, 0, 0])

In [35]:
arr2[:]=1

In [36]:
arr2

array([1, 1, 1, 1, 1, 1])

In [37]:
arr1

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4]])

In [39]:
arr

array([[[11, 22, 33, 44, 55],
        [27,  5, 13, 52, 34],
        [69, 57, 29, 45, 75],
        [26, 58, 29,  2, 47]],

       [[82, 36, 55, 86, 55],
        [68, 72, 64, 54, 97],
        [ 8, 25, 17, 85, 18],
        [81,  5, 22, 15, 32]],

       [[41,  6,  9, 51, 25],
        [ 9, 98, 72, 45,  0],
        [41, 15, 87, 63, 98],
        [47, 48, 86, 52, 97]],

       [[25, 71, 76, 48, 41],
        [52,  1, 30, 30, 83],
        [30, 64, 84, 44, 67],
        [12,  2, 84, 71, 93]]])

In [46]:
arr[...,4]                               ## Last column from each dimension

array([[55, 34, 75, 47],
       [55, 97, 18, 32],
       [25,  0, 98, 97],
       [41, 83, 67, 93]])

In [47]:
arr[0,...]                                 ## all the thing from 0 dimension

array([[11, 22, 33, 44, 55],
       [27,  5, 13, 52, 34],
       [69, 57, 29, 45, 75],
       [26, 58, 29,  2, 47]])

In [51]:
arr[0,...,2:5]

array([[33, 44, 55],
       [13, 52, 34],
       [29, 45, 75],
       [29,  2, 47]])

In [52]:
arr[np.newaxis,0,...,2:5]

array([[[33, 44, 55],
        [13, 52, 34],
        [29, 45, 75],
        [29,  2, 47]]])

In [53]:
arr[0,...,2:5,np.newaxis]

array([[[33],
        [44],
        [55]],

       [[13],
        [52],
        [34]],

       [[29],
        [45],
        [75]],

       [[29],
        [ 2],
        [47]]])

In [55]:
arr[0,...,np.newaxis,2:5]

array([[[33, 44, 55]],

       [[13, 52, 34]],

       [[29, 45, 75]],

       [[29,  2, 47]]])