In [1]:
import numpy as np

In [2]:
arr1=np.identity(4);

In [4]:
arr1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [3]:
for i in range(4):
    for j in range(4):
        print(arr1[i][j]);

1.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
1.0


In [5]:
arr1.shape

(4, 4)

In [7]:
a=arr1.shape

In [9]:
a[0]

4

In [10]:
arr1.shape[0]

4

In [11]:
for i in range(arr1.shape[0]):
    for j in range(arr1.shape[1]):
        print(arr1[i][j]);

1.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
1.0


In [12]:
arr1.ndim

2

In [13]:
arr1.size

16

In [14]:
arr1.dtype

dtype('float64')

In [15]:
arr1.itemsize

8

In [17]:
arr1.astype('int')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [18]:
arr2=np.zeros((2,3,4)); 

In [19]:
arr2

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [20]:
arr2.size

24

In [21]:
arr2.shape

(2, 3, 4)

In [22]:
arr2.ndim

3

In [24]:
for i in range(arr2.shape[0]):
    for j in range(arr2.shape[1]):
        for k in range(arr2.shape[2]):
            print(arr2[i][j][k],end=' ');
        print();
    print();

0.0 0.0 0.0 0.0 
0.0 0.0 0.0 0.0 
0.0 0.0 0.0 0.0 

0.0 0.0 0.0 0.0 
0.0 0.0 0.0 0.0 
0.0 0.0 0.0 0.0 



In [37]:
for i in arr2:
    print(i)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### Slicing

In [25]:
arr3=np.array([2,3,5,6,73,7]);

In [26]:
print(arr3[:])

[ 2  3  5  6 73  7]


In [27]:
print(arr3)

[ 2  3  5  6 73  7]


In [29]:
print(arr3[2:])

[ 5  6 73  7]


In [30]:
print(arr3[2:3])

[5]


In [31]:
print(arr3[::-1])

[ 7 73  6  5  3  2]


In [32]:
print(arr3[-4:])

[ 5  6 73  7]


In [33]:
print(arr3[-1])

7


In [36]:
for i in arr3[::-1]:
    print(i,end=' ')

7 73 6 5 3 2 

In [38]:
arr4=np.arange(24).reshape(4,6);

In [39]:
arr4

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [41]:
arr4[0,0]

0

In [42]:
arr4[0][0]

0

In [44]:
arr4[0]                        ## Row 0 of array 4

array([0, 1, 2, 3, 4, 5])

In [46]:
arr4[3]                         ## Row 3 of array4

array([18, 19, 20, 21, 22, 23])

In [48]:
arr4[:]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [51]:
arr4[:,0]                      ## Column 0 of array4

array([ 0,  6, 12, 18])

In [53]:
arr4[:,5]                       ## Column 5 of array4

array([ 5, 11, 17, 23])

In [55]:
arr4[1:3,2:4]

array([[ 8,  9],
       [14, 15]])

In [56]:
arr4[-2:,-2:]

array([[16, 17],
       [22, 23]])

In [57]:
arr4[2:,4]

array([16, 22])

In [58]:
for i in np.nditer(arr4):
    print(i);

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [62]:
print(np.array(np.nditer(arr4)));

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
