## Basic Indexing

### Single Element Indexing

In [1]:
import numpy as np;

In [2]:
arr=np.arange(16);

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [4]:
arr[0]

0

In [5]:
arr[-1]

15

In [6]:
arr[9]

9

In [7]:
for i in range(arr.size):
    print(arr[i],end=' ');

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 

In [8]:
arr.shape=(4,4);

In [9]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
arr[0]

array([0, 1, 2, 3])

In [11]:
arr[0,1]

1

In [12]:
arr[3,-1]

15

In [13]:
arr[-1,-1]

15

In [14]:
arr[:,1]

array([ 1,  5,  9, 13])

In [15]:
arr[3]

array([12, 13, 14, 15])

In [16]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [17]:
arr[[0,1,2,3],[0,1,2,3]]                    # diagnal Elements

array([ 0,  5, 10, 15])

### Striding

- Striding is a mechanism by which Numpy accessing and operating on arrays. Stides define the number of step in each dimension when iterating over the array.

In [18]:
import numpy as np;

In [19]:
arr_strides=np.array([[[23,45,54],[64,23,64]],[[56,23,74],[54,94,45]],[[95,58,44],[95,86,38]]]);

In [20]:
arr_strides

array([[[23, 45, 54],
        [64, 23, 64]],

       [[56, 23, 74],
        [54, 94, 45]],

       [[95, 58, 44],
        [95, 86, 38]]])

In [21]:
arr_strides.strides          # it means that to move from one elements to another in the dimension(1) numpy jumps total 24Bytes, and to move from one element to another in dimension(2,row), Numpy jumps total 12Bytes. and to move from one element to the next in the second dimension Numpy Jumps total 4bytes.  

(24, 12, 4)

In [22]:
# Another Example

In [23]:
arr_strides.shape=(3,6);

In [24]:
arr_strides

array([[23, 45, 54, 64, 23, 64],
       [56, 23, 74, 54, 94, 45],
       [95, 58, 44, 95, 86, 38]])

In [25]:
arr_strides.strides

(24, 4)

## Slicing

In [26]:
import numpy as np;
arr1=np.random.randint(low=0,high=100,size=24);

In [27]:
arr1

array([56, 68, 79, 46, 50, 41, 99,  1, 99, 50, 42, 67, 73, 21, 67, 23, 15,
       57, 59, 71, 58, 69, 91, 95])

In [28]:
arr1[0:5]

array([56, 68, 79, 46, 50])

In [29]:
arr1[-10:]

array([67, 23, 15, 57, 59, 71, 58, 69, 91, 95])

In [30]:
arr1[-10::-1]

array([67, 21, 73, 67, 42, 50, 99,  1, 99, 41, 50, 46, 79, 68, 56])

### Two Dimensional Array

In [31]:
arr1.shape=(4,6);

In [32]:
arr1

array([[56, 68, 79, 46, 50, 41],
       [99,  1, 99, 50, 42, 67],
       [73, 21, 67, 23, 15, 57],
       [59, 71, 58, 69, 91, 95]])

In [33]:
arr1[0]                                  #Row 0

array([56, 68, 79, 46, 50, 41])

In [34]:
arr1[3]                                 #Row  3

array([59, 71, 58, 69, 91, 95])

In [35]:
arr1[:,4]                               #Column 4

array([50, 42, 15, 91])

In [36]:
arr1[:,[1,3,5]]                       # Column  1,3,5

array([[68, 46, 41],
       [ 1, 50, 67],
       [21, 23, 57],
       [71, 69, 95]])

In [37]:
arr1[1:,3:]                            # From Row 1 to Last Row & From Column 3 to Last Column

array([[50, 42, 67],
       [23, 15, 57],
       [69, 91, 95]])

In [38]:
arr1[2,::-1]                            # Reverse the 2 row of arr1

array([57, 15, 23, 67, 21, 73])

In [39]:
arr1[:,::-1]                             # Reverse all the rows

array([[41, 50, 46, 79, 68, 56],
       [67, 42, 50, 99,  1, 99],
       [57, 15, 23, 67, 21, 73],
       [95, 91, 69, 58, 71, 59]])

In [40]:
arr1[::-1,1]                                 # Reverse all the rows of Column 1                 

array([71, 21,  1, 68])

### Three Dimensional Array

In [41]:
arr1.shape=(2,3,4);

In [42]:
arr1

array([[[56, 68, 79, 46],
        [50, 41, 99,  1],
        [99, 50, 42, 67]],

       [[73, 21, 67, 23],
        [15, 57, 59, 71],
        [58, 69, 91, 95]]])

In [43]:
arr1[:]

array([[[56, 68, 79, 46],
        [50, 41, 99,  1],
        [99, 50, 42, 67]],

       [[73, 21, 67, 23],
        [15, 57, 59, 71],
        [58, 69, 91, 95]]])

In [44]:
arr1[0]                                 # 0 Dimensional

array([[56, 68, 79, 46],
       [50, 41, 99,  1],
       [99, 50, 42, 67]])

In [45]:
arr1[1]                                   # 1 Dimensional

array([[73, 21, 67, 23],
       [15, 57, 59, 71],
       [58, 69, 91, 95]])

In [46]:
arr1[1,2]                               # 1 Dimensional, 2 Row

array([58, 69, 91, 95])

In [47]:
arr1[0,:,3]                              # 0 Dimensional ,  all rows ,  3 column

array([46,  1, 67])

In [48]:
arr1[1,:,::-1]

array([[23, 67, 21, 73],
       [71, 59, 57, 15],
       [95, 91, 69, 58]])

In [49]:
arr1[0:1]                                  # print Dimensional 0

array([[[56, 68, 79, 46],
        [50, 41, 99,  1],
        [99, 50, 42, 67]]])

In [50]:
arr1[1:4]                                    # Start from 1 Dimensional till 4 , but we have only 1 so it will be printed

array([[[73, 21, 67, 23],
        [15, 57, 59, 71],
        [58, 69, 91, 95]]])

In [51]:
arr1[1:1+1]

array([[[73, 21, 67, 23],
        [15, 57, 59, 71],
        [58, 69, 91, 95]]])

### Three Dimensional Array

In [52]:
arr3D=np.random.randint(low=0,high=100,size=30).reshape(5,2,3);

In [53]:
arr3D

array([[[14, 88, 19],
        [74, 47, 53]],

       [[17, 14, 52],
        [27,  0, 10]],

       [[99, 22, 73],
        [84, 95, 81]],

       [[59, 81, 63],
        [20,  8, 14]],

       [[ 6,  0,  3],
        [ 9, 19, 80]]])

In [54]:
arr3D[0:]

array([[[14, 88, 19],
        [74, 47, 53]],

       [[17, 14, 52],
        [27,  0, 10]],

       [[99, 22, 73],
        [84, 95, 81]],

       [[59, 81, 63],
        [20,  8, 14]],

       [[ 6,  0,  3],
        [ 9, 19, 80]]])

In [55]:
arr3D[2]                                  # get 2 Dimensional

array([[99, 22, 73],
       [84, 95, 81]])

In [56]:
arr3D[2]=0                                # Set the value of 2 dimensional to 0

In [57]:
arr3D

array([[[14, 88, 19],
        [74, 47, 53]],

       [[17, 14, 52],
        [27,  0, 10]],

       [[ 0,  0,  0],
        [ 0,  0,  0]],

       [[59, 81, 63],
        [20,  8, 14]],

       [[ 6,  0,  3],
        [ 9, 19, 80]]])

In [58]:
arr3D[:,:,::-1]                         ## Reverse all the rows of all the dimensional

array([[[19, 88, 14],
        [53, 47, 74]],

       [[52, 14, 17],
        [10,  0, 27]],

       [[ 0,  0,  0],
        [ 0,  0,  0]],

       [[63, 81, 59],
        [14,  8, 20]],

       [[ 3,  0,  6],
        [80, 19,  9]]])

In [59]:
arr3D

array([[[14, 88, 19],
        [74, 47, 53]],

       [[17, 14, 52],
        [27,  0, 10]],

       [[ 0,  0,  0],
        [ 0,  0,  0]],

       [[59, 81, 63],
        [20,  8, 14]],

       [[ 6,  0,  3],
        [ 9, 19, 80]]])

In [60]:
arr3D[3,:,2]                             # 3 Dimensional , all rows , column 2

array([63, 14])

In [61]:
arr3D[3,:,2::-1]                        # 3 Dimensional , all rows, start from 2 column end will -n-1=-4 , go in reverse order

array([[63, 81, 59],
       [14,  8, 20]])

In [62]:
obj = (slice(1, 10, 5), slice(None, None, -1)); arr3D[obj]

array([[[27,  0, 10],
        [17, 14, 52]]])

In [63]:
obj = (slice(1, 10, 1), slice(None, None, -1)); arr3D[obj]

array([[[27,  0, 10],
        [17, 14, 52]],

       [[ 0,  0,  0],
        [ 0,  0,  0]],

       [[20,  8, 14],
        [59, 81, 63]],

       [[ 9, 19, 80],
        [ 6,  0,  3]]])

In [64]:
arr3D[1:10:5, ::-1]

array([[[27,  0, 10],
        [17, 14, 52]]])

In [65]:
arr3D

array([[[14, 88, 19],
        [74, 47, 53]],

       [[17, 14, 52],
        [27,  0, 10]],

       [[ 0,  0,  0],
        [ 0,  0,  0]],

       [[59, 81, 63],
        [20,  8, 14]],

       [[ 6,  0,  3],
        [ 9, 19, 80]]])

In [66]:
arr3D[1,1::-1]                                # reverse the order of rows in 1 dimensional

array([[27,  0, 10],
       [17, 14, 52]])

In [67]:
arr3D[1,1::-1,::-1]                          # reverse the 1 dimensional row and column wise

array([[10,  0, 27],
       [52, 14, 17]])

In [68]:
arr3D[::-1,1::-1,::-1]                       # reverse all dimension,  reverse all the rows,   reverse all the colums  

array([[[80, 19,  9],
        [ 3,  0,  6]],

       [[14,  8, 20],
        [63, 81, 59]],

       [[ 0,  0,  0],
        [ 0,  0,  0]],

       [[10,  0, 27],
        [52, 14, 17]],

       [[53, 47, 74],
        [19, 88, 14]]])

### Using slice object

In [69]:
arr3D

array([[[14, 88, 19],
        [74, 47, 53]],

       [[17, 14, 52],
        [27,  0, 10]],

       [[ 0,  0,  0],
        [ 0,  0,  0]],

       [[59, 81, 63],
        [20,  8, 14]],

       [[ 6,  0,  3],
        [ 9, 19, 80]]])

In [70]:
obj=(slice(1,2,1),slice(1,None,-1));            # reverse the order of rows in 1 dimensional    slice(start,stop,step)
arr3D[obj]                               # Here the first slice is for dimension  and second slice is for rows in that dimension

array([[[27,  0, 10],
        [17, 14, 52]]])

In [71]:
obj=(slice(None,None,-1),slice(None,None,-1),slice(None,None,-1));   # reverse all dimension,  reverse all the rows,   reverse all the colums 
arr3D[obj]

array([[[80, 19,  9],
        [ 3,  0,  6]],

       [[14,  8, 20],
        [63, 81, 59]],

       [[ 0,  0,  0],
        [ 0,  0,  0]],

       [[10,  0, 27],
        [52, 14, 17]],

       [[53, 47, 74],
        [19, 88, 14]]])

## newaxis

- np.newaxis add a new axis to the array

In [72]:
arr1=np.arange(5);

In [73]:
arr1

array([0, 1, 2, 3, 4])

In [74]:
arr1[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [75]:
arr1[np.newaxis,:]

array([[0, 1, 2, 3, 4]])

In [76]:
arr1[:,np.newaxis]+arr1[np.newaxis,:]

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [77]:
arr1

array([0, 1, 2, 3, 4])

In [78]:
arr1[np.newaxis,:].shape

(1, 5)

In [79]:
arr1=np.arange(12).reshape(2,6);

In [80]:
arr1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [81]:
arr1[np.newaxis,:,:]

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]])

In [82]:
arr1[:,np.newaxis,:]

array([[[ 0,  1,  2,  3,  4,  5]],

       [[ 6,  7,  8,  9, 10, 11]]])

In [83]:
arr1[:,:,np.newaxis]

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]]])

## Ellipsis

In [84]:
arr1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [85]:
arr1[...,0]                    ## this means that i don't care about previous indices i care about last indix

array([0, 6])

In [86]:
arr1[0,...]                    ## i just care about first index

array([0, 1, 2, 3, 4, 5])

In [87]:
arr1.shape=(2,2,3);

In [88]:
arr1

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [89]:
arr1[...,2]

array([[ 2,  5],
       [ 8, 11]])

## Advance Indexing

### Integer array indexing

In [90]:
arr1D=np.arange(10,0,-1);

In [91]:
arr1D

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [92]:
arr1D[np.array([0,-2,3,-6])]                      ## get Elements of index (0,-2,3,-6)

array([10,  2,  7,  6])

In [93]:
arr1D[np.array([2,3,4,5])]                      ## index (2,3,4,5)

array([8, 7, 6, 5])

In [94]:
arr1D[np.array([-10,-9,-8,-7,-6,-5,-4])]

array([10,  9,  8,  7,  6,  5,  4])

In [95]:
arr2D=arr1D.reshape(5,2)

In [96]:
arr2D

array([[10,  9],
       [ 8,  7],
       [ 6,  5],
       [ 4,  3],
       [ 2,  1]])

In [97]:
arr2D[np.array([0,0]),np.array([0,1])]              ##   arr2D[0][0]  and arr2D[0,1]

array([10,  9])

In [98]:
arr2D[np.array([2])]                                ##      arr2D[2]

array([[6, 5]])

In [99]:
arr2D[np.array([0,1,2,3,4]),np.array([1,1,1,1,1])]

array([9, 7, 5, 3, 1])

In [100]:
arr2D[np.array([-1,-1,-2,-2]),np.array([-1,-2,-1,-2])]

array([1, 2, 3, 4])

In [101]:
arr2D[np.array([-1,-1,-2,-2]),np.array([-1,-2,-1,-2])].ndim

1

In [102]:
arr2D

array([[10,  9],
       [ 8,  7],
       [ 6,  5],
       [ 4,  3],
       [ 2,  1]])

In [103]:
arr2D[np.array([1,2,3]),1]                            # arr2D[1,1]  arr2D[2,1]  arr2D[3,1]

array([7, 5, 3])

In [104]:
arr2D[0,np.array([0,1])]                            # arr2D[0,0]  arr2D[0,1]

array([10,  9])

In [105]:
arr2D[0,np.array([0])]

array([10])

In [106]:
arr2D[[-1,3,1],[1,0,1]]

array([1, 4, 7])

In [107]:
arr2D

array([[10,  9],
       [ 8,  7],
       [ 6,  5],
       [ 4,  3],
       [ 2,  1]])

In [108]:
arr2D[np.array([[0,0],[4,4]]),np.array([[0,1],[0,1]])]

array([[10,  9],
       [ 2,  1]])

In [109]:
arr2D[np.array([[3,3],[4,4]]),np.array([[0,1],[0,1]])]

array([[4, 3],
       [2, 1]])

In [110]:
rows=np.array([[2,2],[4,4]]);
columns=np.array([[0,1],[0,1]]);
arr2D[rows,columns]

array([[6, 5],
       [2, 1]])

In [176]:
arr2D

array([[10,  9],
       [ 8,  7],
       [ 6,  5],
       [ 4,  3],
       [ 2,  1]])

In [182]:
row=np.arange(2,4);
col=np.arange(0,2);

In [183]:
obj=(row,col)

In [186]:
print(arr2D[np.arange(2,4),np.arange(0,2)]);

# OR

print(arr2D[row,col]);

# OR

print(arr2D[obj]);

[6 3]
[6 3]
[6 3]


In [187]:
arr3D

array([[[14, 88, 19],
        [74, 47, 53]],

       [[17, 14, 52],
        [27,  0, 10]],

       [[ 0,  0,  0],
        [ 0,  0,  0]],

       [[59, 81, 63],
        [20,  8, 14]],

       [[ 6,  0,  3],
        [ 9, 19, 80]]])

In [188]:
arr3D[np.arange(0,2),np.arange(0,2)]

array([[14, 88, 19],
       [27,  0, 10]])

In [189]:
arr3D[np.array([0,3,4]),np.array([0,1,0])]

array([[14, 88, 19],
       [20,  8, 14],
       [ 6,  0,  3]])

###  Boolean Array Indexing

In [111]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [112]:
arr.nonzero()

(array([0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3], dtype=int64),
 array([1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))

In [113]:
type(arr.nonzero())

tuple

In [114]:
obj=(np.array([2,2,3,3]),np.array([2,3,2,3]))

In [115]:
obj

(array([2, 2, 3, 3]), array([2, 3, 2, 3]))

In [116]:
arr[obj]

array([10, 11, 14, 15])

In [117]:
arr[arr<10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
arr<10

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [119]:
arr[arr<10]+=30;

In [120]:
arr

array([[30, 31, 32, 33],
       [34, 35, 36, 37],
       [38, 39, 10, 11],
       [12, 13, 14, 15]])

In [121]:
x=np.array([[np.nan,3],[5,np.nan],[np.nan,np.nan]])

In [122]:
x

array([[nan,  3.],
       [ 5., nan],
       [nan, nan]])

In [123]:
x[np.isnan(x)]

array([nan, nan, nan, nan])

In [124]:
x[~np.isnan(x)]

array([3., 5.])

In [125]:
arr

array([[30, 31, 32, 33],
       [34, 35, 36, 37],
       [38, 39, 10, 11],
       [12, 13, 14, 15]])

In [126]:
arr[arr%3==0]

array([30, 33, 36, 39, 12, 15])

In [127]:
arr%3==0

array([[ True, False, False,  True],
       [False, False,  True, False],
       [False,  True, False, False],
       [ True, False, False,  True]])

In [128]:
b=arr>30

In [129]:
b

array([[False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [130]:
b[:,0]

array([False,  True,  True, False])

In [131]:
arr[b[:,0]]

array([[34, 35, 36, 37],
       [38, 39, 10, 11]])

In [132]:
b[0]

array([False,  True,  True,  True])

In [133]:
arr[b[0]]

array([[34, 35, 36, 37],
       [38, 39, 10, 11],
       [12, 13, 14, 15]])

In [134]:
arr[True]

array([[[30, 31, 32, 33],
        [34, 35, 36, 37],
        [38, 39, 10, 11],
        [12, 13, 14, 15]]])

In [135]:
arr[True,True]

array([[[30, 31, 32, 33],
        [34, 35, 36, 37],
        [38, 39, 10, 11],
        [12, 13, 14, 15]]])

In [136]:
arr[True,False]

array([], shape=(0, 4, 4), dtype=int32)

In [137]:
arr[[True,True,True,True],[True,True,True,True]]

array([30, 35, 10, 15])

In [138]:
arr

array([[30, 31, 32, 33],
       [34, 35, 36, 37],
       [38, 39, 10, 11],
       [12, 13, 14, 15]])

In [139]:
arr.sum()

420

In [140]:
arr.sum(-1)

array([126, 142,  98,  54])

In [141]:
arr.sum(0)

array([114, 118,  92,  96])

In [142]:
arr.sum(1)

array([126, 142,  98,  54])

In [143]:
rowsum=arr.sum(-1);
arr[rowsum<100,:]

array([[38, 39, 10, 11],
       [12, 13, 14, 15]])

In [144]:
arr[rowsum<100,0:2]

array([[38, 39],
       [12, 13]])

In [145]:
rowsum

array([126, 142,  98,  54])

In [146]:
rowsum<100

array([False, False,  True,  True])

## Field Access

- In NumPy, field access refers to the process of accessing specific elements or columns of structured arrays.

#### Exmple 1

In [147]:
student=np.array([('Usman',20,45.5),('Kausar',22,50),('Noman',23,40)], dtype=[('name',np.str_,20),('age',np.int16),('marks',np.float32)]);

In [148]:
student

array([('Usman', 20, 45.5), ('Kausar', 22, 50. ), ('Noman', 23, 40. )],
      dtype=[('name', '<U20'), ('age', '<i2'), ('marks', '<f4')])

In [149]:
student['name']

array(['Usman', 'Kausar', 'Noman'], dtype='<U20')

In [150]:
student['age']

array([20, 22, 23], dtype=int16)

In [151]:
student['marks']

array([45.5, 50. , 40. ], dtype=float32)

#### Example 2

In [152]:
x=np.zeros((2,2), dtype=[('a',np.int32),('b',np.float32)]);

In [153]:
x

array([[(0, 0.), (0, 0.)],
       [(0, 0.), (0, 0.)]], dtype=[('a', '<i4'), ('b', '<f4')])

In [154]:
x['a']

array([[0, 0],
       [0, 0]])

In [155]:
x['b']

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [156]:
x['a'].shape

(2, 2)

In [157]:
x['b'].shape

(2, 2)

In [158]:
x['a'].size

4

In [159]:
x['b'].size

4

In [160]:
x=np.zeros((2,2), dtype=[('a',np.int32),('b',np.float64,(3,3))])

In [161]:
x

array([[(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]),
        (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])],
       [(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]),
        (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])]],
      dtype=[('a', '<i4'), ('b', '<f8', (3, 3))])

In [162]:
x['a']

array([[0, 0],
       [0, 0]])

In [163]:
x['b']

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

#### Example 3

In [164]:
data_type=np.dtype([('name',np.str_,30),('age',np.int8),('salary',np.float32),('dept',np.int8)])

In [165]:
employee=np.array([('abbas',20,3000000,10),('sajid',24,34000,20),('kamran',40,350000,30),('kareem',30,23000,10),('saleem',25,200000,20)],dtype=data_type)

In [166]:
employee

array([('abbas', 20, 3000000., 10), ('sajid', 24,   34000., 20),
       ('kamran', 40,  350000., 30), ('kareem', 30,   23000., 10),
       ('saleem', 25,  200000., 20)],
      dtype=[('name', '<U30'), ('age', 'i1'), ('salary', '<f4'), ('dept', 'i1')])

In [167]:
employee['name']

array(['abbas', 'sajid', 'kamran', 'kareem', 'saleem'], dtype='<U30')

In [168]:
employee['salary']

array([3000000.,   34000.,  350000.,   23000.,  200000.], dtype=float32)

In [169]:
employee['age']

array([20, 24, 40, 30, 25], dtype=int8)

In [170]:
employee['dept']

array([10, 20, 30, 10, 20], dtype=int8)

In [171]:
np.min(employee['age'])

20

In [172]:
np.max(employee['age'])

40

In [173]:
np.min(employee['salary'])

23000.0

In [174]:
np.max(employee['salary'])

3000000.0

In [175]:
for i in range(len(employee['name'])):
    print('Name : ',employee['name'][i],'Sallary : ',employee['salary'][i],'Age : ',employee['age'][i],'Dept : ',employee['dept'][i])

Name :  abbas Sallary :  3000000.0 Age :  20 Dept :  10
Name :  sajid Sallary :  34000.0 Age :  24 Dept :  20
Name :  kamran Sallary :  350000.0 Age :  40 Dept :  30
Name :  kareem Sallary :  23000.0 Age :  30 Dept :  10
Name :  saleem Sallary :  200000.0 Age :  25 Dept :  20
