In [1]:
import numpy as np;

In [2]:
arr=np.array([[[23,45,54],[64,23,64]],[[56,23,74],[54,94,45]],[[95,58,44],[95,86,38]]]);

In [3]:
arr

array([[[23, 45, 54],
        [64, 23, 64]],

       [[56, 23, 74],
        [54, 94, 45]],

       [[95, 58, 44],
        [95, 86, 38]]])

In [4]:
arr.shape

(3, 2, 3)

In [5]:
arr.size

18

In [6]:
arr.ndim

3

In [7]:
arr.strides

(24, 12, 4)

In [8]:
arr

array([[[23, 45, 54],
        [64, 23, 64]],

       [[56, 23, 74],
        [54, 94, 45]],

       [[95, 58, 44],
        [95, 86, 38]]])

In [9]:
arr[0,0]

array([23, 45, 54])

In [10]:
sum(arr)

array([[174, 126, 172],
       [213, 203, 147]])

In [11]:
min(arr[0,0])

23

In [12]:
arr[[0,2,1]]

array([[[23, 45, 54],
        [64, 23, 64]],

       [[95, 58, 44],
        [95, 86, 38]],

       [[56, 23, 74],
        [54, 94, 45]]])

In [13]:
arr[0:2]

array([[[23, 45, 54],
        [64, 23, 64]],

       [[56, 23, 74],
        [54, 94, 45]]])

In [14]:
arr

array([[[23, 45, 54],
        [64, 23, 64]],

       [[56, 23, 74],
        [54, 94, 45]],

       [[95, 58, 44],
        [95, 86, 38]]])

In [15]:
arr[::-1,::-1,::-1]

array([[[38, 86, 95],
        [44, 58, 95]],

       [[45, 94, 54],
        [74, 23, 56]],

       [[64, 23, 64],
        [54, 45, 23]]])

In [16]:
arr

array([[[23, 45, 54],
        [64, 23, 64]],

       [[56, 23, 74],
        [54, 94, 45]],

       [[95, 58, 44],
        [95, 86, 38]]])

In [17]:
arr[np.array([[0,2],[1,2]]),np.array([[0,1],[0,1]])]

array([[[23, 45, 54],
        [95, 86, 38]],

       [[56, 23, 74],
        [95, 86, 38]]])

In [18]:
arr[np.array([[0,2],[1,2]]),np.array([[0,1],[0,1]]),np.array([[1,2],[0,1]])]

array([[45, 38],
       [56, 86]])

In [19]:
arr[np.array([0])]

array([[[23, 45, 54],
        [64, 23, 64]]])

In [20]:
arr[np.array([[0],[2],[1]])]

array([[[[23, 45, 54],
         [64, 23, 64]]],


       [[[95, 58, 44],
         [95, 86, 38]]],


       [[[56, 23, 74],
         [54, 94, 45]]]])

In [21]:
arr[np.array([0,2,1,2]),np.array([0,1,0,1]),np.array([1,2,0,1])]

array([45, 38, 56, 86])

In [22]:
arr[np.array([[0,2],[1,2]]),np.array([[0,1],[0,1]]),np.array([[1,2],[0,1]])]

array([[45, 38],
       [56, 86]])

In [23]:
arr[(np.array([[[0,2],[1,2]]])),(np.array([[[0,1],[0,1]]])),(np.array([[[1,2],[0,1]]]))]

array([[[45, 38],
        [56, 86]]])

In [24]:
arr[np.array([0])]

array([[[23, 45, 54],
        [64, 23, 64]]])

In [25]:
arr[np.array([0]),np.array([1])]

array([[64, 23, 64]])

In [26]:
arr[np.array([0]),np.array([1]),np.array([1])]

array([23])

In [27]:
arr[(slice(0,1,1))]

array([[[23, 45, 54],
        [64, 23, 64]]])

In [28]:
arr[(slice(None,None,-1))]

array([[[95, 58, 44],
        [95, 86, 38]],

       [[56, 23, 74],
        [54, 94, 45]],

       [[23, 45, 54],
        [64, 23, 64]]])

In [29]:
arr

array([[[23, 45, 54],
        [64, 23, 64]],

       [[56, 23, 74],
        [54, 94, 45]],

       [[95, 58, 44],
        [95, 86, 38]]])

In [30]:
arr_even=arr[arr%2==0]

In [31]:
arr_even

array([54, 64, 64, 56, 74, 54, 94, 58, 44, 86, 38])

In [32]:
arr[1,0,1]

23

In [33]:
arr[1,0:2,1:3]

array([[23, 74],
       [94, 45]])

In [34]:
arr

array([[[23, 45, 54],
        [64, 23, 64]],

       [[56, 23, 74],
        [54, 94, 45]],

       [[95, 58, 44],
        [95, 86, 38]]])

In [35]:
arr.sum(axis=1)

array([[ 87,  68, 118],
       [110, 117, 119],
       [190, 144,  82]])

In [36]:
arr.sum(axis=2)

array([[122, 151],
       [153, 193],
       [197, 219]])

In [37]:
for i in arr:
    print(i)

[[23 45 54]
 [64 23 64]]
[[56 23 74]
 [54 94 45]]
[[95 58 44]
 [95 86 38]]


In [38]:
arr

array([[[23, 45, 54],
        [64, 23, 64]],

       [[56, 23, 74],
        [54, 94, 45]],

       [[95, 58, 44],
        [95, 86, 38]]])

In [39]:
arr[[0,1],[1,0]]

array([[64, 23, 64],
       [56, 23, 74]])

In [40]:
arr125=np.random.randint(low=0,high=100,size=125)

In [41]:
arr125

array([ 9, 47, 70, 80, 53, 74, 41, 69, 45, 22,  0,  9, 88, 66, 33,  5, 51,
       98, 86, 43, 52, 12, 97, 55, 47, 44, 56, 80, 17, 72, 36, 54, 49,  3,
       98, 69, 32, 95, 81, 48,  2, 77, 16, 96, 19, 87, 75, 91, 26, 77, 11,
       64, 15, 63, 78, 98, 64, 90, 14, 99, 71, 70, 79, 35, 26, 95, 75, 25,
       61, 21, 49, 86, 53, 38, 88,  7, 66, 66, 49, 78, 53, 69, 51, 39, 79,
       45, 15, 55,  0, 87, 78,  7, 24,  4, 85, 27, 18, 47, 74, 80, 78, 71,
       71, 37, 98, 50, 90, 80,  5, 98, 23,  1, 24, 44, 96,  5, 64, 69, 21,
        5, 83, 10, 93, 50, 74])

In [42]:
arr125.shape=(5,5,5)

In [43]:
arr125

array([[[ 9, 47, 70, 80, 53],
        [74, 41, 69, 45, 22],
        [ 0,  9, 88, 66, 33],
        [ 5, 51, 98, 86, 43],
        [52, 12, 97, 55, 47]],

       [[44, 56, 80, 17, 72],
        [36, 54, 49,  3, 98],
        [69, 32, 95, 81, 48],
        [ 2, 77, 16, 96, 19],
        [87, 75, 91, 26, 77]],

       [[11, 64, 15, 63, 78],
        [98, 64, 90, 14, 99],
        [71, 70, 79, 35, 26],
        [95, 75, 25, 61, 21],
        [49, 86, 53, 38, 88]],

       [[ 7, 66, 66, 49, 78],
        [53, 69, 51, 39, 79],
        [45, 15, 55,  0, 87],
        [78,  7, 24,  4, 85],
        [27, 18, 47, 74, 80]],

       [[78, 71, 71, 37, 98],
        [50, 90, 80,  5, 98],
        [23,  1, 24, 44, 96],
        [ 5, 64, 69, 21,  5],
        [83, 10, 93, 50, 74]]])

In [44]:
arr125[2:2+3,1:1+3,1:1+3]

array([[[64, 90, 14],
        [70, 79, 35],
        [75, 25, 61]],

       [[69, 51, 39],
        [15, 55,  0],
        [ 7, 24,  4]],

       [[90, 80,  5],
        [ 1, 24, 44],
        [64, 69, 21]]])

In [45]:
arr125=np.random.randint(low=-100,high=100,size=125)

In [46]:
arr125

array([ 95, -82,  74, -59,  63, -61,  35, -89,  71, -39,  99,  73, -99,
       -18,  31,  38, -83,  27, -30,  94,   0,  45,  29, -29,  33, -73,
        78, -78, -34,  76,  61, -45, -35,  75,  11,  28,  -4, -20,  70,
       -42, -64,  85, -60, -84, -30, -53,  25,  78,  18,  45,  15,   9,
        28, -78,  23,  92,  79, -83,   3, -59, -63,  92,  21,  79, -80,
        44,  13, -25,  81,  56,  -4, -55,  12,  17, -89,  65,  38, -24,
        84,  42,  75, -64,   5, -87,  27, -68, -90, -41,  70,  62,  22,
         2,  97,  81,  18,  67,  -6,  52,  63, -62, -25, -11, -29,  61,
        59, -80,  85, -69, -80, -23, -80,  74, -57, -70, -42, -28, -73,
       -76,  10,  92,  95,  69, -58,  90, -19])

In [47]:
arr125[arr125<0]=0;

In [48]:
arr125

array([95,  0, 74,  0, 63,  0, 35,  0, 71,  0, 99, 73,  0,  0, 31, 38,  0,
       27,  0, 94,  0, 45, 29,  0, 33,  0, 78,  0,  0, 76, 61,  0,  0, 75,
       11, 28,  0,  0, 70,  0,  0, 85,  0,  0,  0,  0, 25, 78, 18, 45, 15,
        9, 28,  0, 23, 92, 79,  0,  3,  0,  0, 92, 21, 79,  0, 44, 13,  0,
       81, 56,  0,  0, 12, 17,  0, 65, 38,  0, 84, 42, 75,  0,  5,  0, 27,
        0,  0,  0, 70, 62, 22,  2, 97, 81, 18, 67,  0, 52, 63,  0,  0,  0,
        0, 61, 59,  0, 85,  0,  0,  0,  0, 74,  0,  0,  0,  0,  0,  0, 10,
       92, 95, 69,  0, 90,  0])

In [49]:
arr125.sum()

3626

In [50]:
arr125[arr125==0]=-1

In [51]:
arr125

array([95, -1, 74, -1, 63, -1, 35, -1, 71, -1, 99, 73, -1, -1, 31, 38, -1,
       27, -1, 94, -1, 45, 29, -1, 33, -1, 78, -1, -1, 76, 61, -1, -1, 75,
       11, 28, -1, -1, 70, -1, -1, 85, -1, -1, -1, -1, 25, 78, 18, 45, 15,
        9, 28, -1, 23, 92, 79, -1,  3, -1, -1, 92, 21, 79, -1, 44, 13, -1,
       81, 56, -1, -1, 12, 17, -1, 65, 38, -1, 84, 42, 75, -1,  5, -1, 27,
       -1, -1, -1, 70, 62, 22,  2, 97, 81, 18, 67, -1, 52, 63, -1, -1, -1,
       -1, 61, 59, -1, 85, -1, -1, -1, -1, 74, -1, -1, -1, -1, -1, -1, 10,
       92, 95, 69, -1, 90, -1])

In [52]:
arr125.shape=(5,5,5)

In [53]:
arr125[arr125<0]=0

In [54]:
arr125

array([[[95,  0, 74,  0, 63],
        [ 0, 35,  0, 71,  0],
        [99, 73,  0,  0, 31],
        [38,  0, 27,  0, 94],
        [ 0, 45, 29,  0, 33]],

       [[ 0, 78,  0,  0, 76],
        [61,  0,  0, 75, 11],
        [28,  0,  0, 70,  0],
        [ 0, 85,  0,  0,  0],
        [ 0, 25, 78, 18, 45]],

       [[15,  9, 28,  0, 23],
        [92, 79,  0,  3,  0],
        [ 0, 92, 21, 79,  0],
        [44, 13,  0, 81, 56],
        [ 0,  0, 12, 17,  0]],

       [[65, 38,  0, 84, 42],
        [75,  0,  5,  0, 27],
        [ 0,  0,  0, 70, 62],
        [22,  2, 97, 81, 18],
        [67,  0, 52, 63,  0]],

       [[ 0,  0,  0, 61, 59],
        [ 0, 85,  0,  0,  0],
        [ 0, 74,  0,  0,  0],
        [ 0,  0,  0, 10, 92],
        [95, 69,  0, 90,  0]]])

In [55]:
arr125[[0,0,4],[2,2,0],[1,3,3]]

array([73,  0, 61])

In [56]:
arr125.sum(axis=1)

array([[232, 153, 130,  71, 221],
       [ 89, 188,  78, 163, 132],
       [151, 193,  61, 180,  79],
       [229,  40, 154, 298, 149],
       [ 95, 228,   0, 161, 151]])

In [57]:
arr125.sum(axis=0)

array([[175, 125, 102, 145, 263],
       [228, 199,   5, 149,  38],
       [127, 239,  21, 219,  93],
       [104, 100, 124, 172, 260],
       [162, 139, 171, 188,  78]])

In [58]:
arr125.sum(axis=2)

array([[232, 106, 203, 159, 107],
       [154, 147,  98,  85, 166],
       [ 75, 174, 192, 194,  29],
       [229, 107, 132, 220, 182],
       [120,  85,  74, 102, 254]])

In [59]:
arr125.sum(axis=0).sum(axis=1).sum()

3626

In [60]:
arr125[0][True]

array([[[95,  0, 74,  0, 63],
        [ 0, 35,  0, 71,  0],
        [99, 73,  0,  0, 31],
        [38,  0, 27,  0, 94],
        [ 0, 45, 29,  0, 33]]])

In [61]:
bool_arr=np.array([[False,False,True,True,True],[False,False,True,True,True],[False,False,True,True,True],[False,False,True,True,True],[False,False,True,True,True]])

In [62]:
bool_arr

array([[False, False,  True,  True,  True],
       [False, False,  True,  True,  True],
       [False, False,  True,  True,  True],
       [False, False,  True,  True,  True],
       [False, False,  True,  True,  True]])

In [63]:
arr125[0][bool_arr]

array([74,  0, 63,  0, 71,  0,  0,  0, 31, 27,  0, 94, 29,  0, 33])

In [64]:
arr125[0][bool_arr].reshape(5,3)

array([[74,  0, 63],
       [ 0, 71,  0],
       [ 0,  0, 31],
       [27,  0, 94],
       [29,  0, 33]])

In [65]:
arr125

array([[[95,  0, 74,  0, 63],
        [ 0, 35,  0, 71,  0],
        [99, 73,  0,  0, 31],
        [38,  0, 27,  0, 94],
        [ 0, 45, 29,  0, 33]],

       [[ 0, 78,  0,  0, 76],
        [61,  0,  0, 75, 11],
        [28,  0,  0, 70,  0],
        [ 0, 85,  0,  0,  0],
        [ 0, 25, 78, 18, 45]],

       [[15,  9, 28,  0, 23],
        [92, 79,  0,  3,  0],
        [ 0, 92, 21, 79,  0],
        [44, 13,  0, 81, 56],
        [ 0,  0, 12, 17,  0]],

       [[65, 38,  0, 84, 42],
        [75,  0,  5,  0, 27],
        [ 0,  0,  0, 70, 62],
        [22,  2, 97, 81, 18],
        [67,  0, 52, 63,  0]],

       [[ 0,  0,  0, 61, 59],
        [ 0, 85,  0,  0,  0],
        [ 0, 74,  0,  0,  0],
        [ 0,  0,  0, 10, 92],
        [95, 69,  0, 90,  0]]])

In [66]:
arr125[4][bool_arr].reshape(5,3)

array([[ 0, 61, 59],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0, 10, 92],
       [ 0, 90,  0]])

In [67]:
np.min(arr125)

0

In [68]:
np.max(arr125)

99

In [69]:
np.max(arr125,axis=0)

array([[95, 78, 74, 84, 76],
       [92, 85,  5, 75, 27],
       [99, 92, 21, 79, 62],
       [44, 85, 97, 81, 94],
       [95, 69, 78, 90, 45]])

In [70]:
np.max(arr125,axis=1)

array([[99, 73, 74, 71, 94],
       [61, 85, 78, 75, 76],
       [92, 92, 28, 81, 56],
       [75, 38, 97, 84, 62],
       [95, 85,  0, 90, 92]])

In [71]:
np.max(arr125,axis=2)

array([[95, 71, 99, 94, 45],
       [78, 75, 70, 85, 78],
       [28, 92, 92, 81, 17],
       [84, 75, 70, 97, 67],
       [61, 85, 74, 92, 95]])

In [72]:
np.sum(arr125)

3626

In [73]:
arr125

array([[[95,  0, 74,  0, 63],
        [ 0, 35,  0, 71,  0],
        [99, 73,  0,  0, 31],
        [38,  0, 27,  0, 94],
        [ 0, 45, 29,  0, 33]],

       [[ 0, 78,  0,  0, 76],
        [61,  0,  0, 75, 11],
        [28,  0,  0, 70,  0],
        [ 0, 85,  0,  0,  0],
        [ 0, 25, 78, 18, 45]],

       [[15,  9, 28,  0, 23],
        [92, 79,  0,  3,  0],
        [ 0, 92, 21, 79,  0],
        [44, 13,  0, 81, 56],
        [ 0,  0, 12, 17,  0]],

       [[65, 38,  0, 84, 42],
        [75,  0,  5,  0, 27],
        [ 0,  0,  0, 70, 62],
        [22,  2, 97, 81, 18],
        [67,  0, 52, 63,  0]],

       [[ 0,  0,  0, 61, 59],
        [ 0, 85,  0,  0,  0],
        [ 0, 74,  0,  0,  0],
        [ 0,  0,  0, 10, 92],
        [95, 69,  0, 90,  0]]])

In [74]:
arr125[np.array([0,3,4]),np.array([1,2,3]),:]

array([[ 0, 35,  0, 71,  0],
       [ 0,  0,  0, 70, 62],
       [ 0,  0,  0, 10, 92]])

In [75]:
arr125[np.array([0,3,4]),np.array([1,2,3])][:]

array([[ 0, 35,  0, 71,  0],
       [ 0,  0,  0, 70, 62],
       [ 0,  0,  0, 10, 92]])

In [76]:
arr125[arr125==0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [77]:
arr125[arr125==0].size

57

In [78]:
arr125.size-arr125[arr125==0].size

68

In [79]:
arr125[0][[True,False,True,False,True]]

array([[95,  0, 74,  0, 63],
       [99, 73,  0,  0, 31],
       [ 0, 45, 29,  0, 33]])

In [112]:
x=np.zeros((2,2),dtype=[('a',np.int32),('b',np.float64,(3,3))])

In [113]:
x

array([[(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]),
        (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])],
       [(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]),
        (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])]],
      dtype=[('a', '<i4'), ('b', '<f8', (3, 3))])

In [114]:
x['a']

array([[0, 0],
       [0, 0]])

In [115]:
x['b']

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [82]:
x['a']

array([[0, 0],
       [0, 0]])

In [83]:
x['b']

array([[0., 0.],
       [0., 0.]])

In [89]:
y=np.array([2,3,5,6,7],dtype=[('a',np.int32)])

In [90]:
y

array([(2,), (3,), (5,), (6,), (7,)], dtype=[('a', '<i4')])

In [94]:
y=np.array([2,3,5,6,7],dtype=[('a',np.int32),('b',np.float64)])

In [95]:
y

array([(2, 2.), (3, 3.), (5, 5.), (6, 6.), (7, 7.)],
      dtype=[('a', '<i4'), ('b', '<f8')])

In [96]:
y['a']

array([2, 3, 5, 6, 7])

In [100]:
y=np.array([2,3,5,6,7],dtype=[('a',np.int32),('b','str'),('c',np.float64)])

In [101]:
y

array([(2, '', 2.), (3, '', 3.), (5, '', 5.), (6, '', 6.), (7, '', 7.)],
      dtype=[('a', '<i4'), ('b', '<U'), ('c', '<f8')])

In [102]:
y['c']

array([2., 3., 5., 6., 7.])

In [103]:
y['b']

array(['', '', '', '', ''], dtype='<U0')

In [109]:
y=np.array([(1,2,3),(4,5,6),(7,8,9)], dtype=[('a',np.int32),('b',np.float64),('c',np.float64)])

In [110]:
y

array([(1, 2., 3.), (4, 5., 6.), (7, 8., 9.)],
      dtype=[('a', '<i4'), ('b', '<f8'), ('c', '<f8')])

In [111]:
y['c']

array([3., 6., 9.])

In [122]:
student=np.array([('Usman',20,45.5),('Kausar',22,50),('Noman',23,40)], dtype=[('name',np.str_,20),('age',np.int16),('marks',np.float32)]);

In [123]:
student

array([('Usman', 20, 45.5), ('Kausar', 22, 50. ), ('Noman', 23, 40. )],
      dtype=[('name', '<U20'), ('age', '<i2'), ('marks', '<f4')])

In [124]:
student['name']

array(['Usman', 'Kausar', 'Noman'], dtype='<U20')

In [125]:
student['age']

array([20, 22, 23], dtype=int16)

In [126]:
student['marks']

array([45.5, 50. , 40. ], dtype=float32)

In [127]:
import numpy as np
from io import StringIO

In [128]:
data = u"1, 2, 3\n4, 5, 6"
np.genfromtxt(StringIO(data), delimiter=",")

array([[1., 2., 3.],
       [4., 5., 6.]])

In [129]:
data

'1, 2, 3\n4, 5, 6'

In [130]:
array=np.genfromtxt(StringIO(data), delimiter=",")

In [131]:
array

array([[1., 2., 3.],
       [4., 5., 6.]])

In [132]:
array.dtype

dtype('float64')

In [165]:
arr1=np.ones((2,4))+4

In [166]:
arr1

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [176]:
arr4=np.array([1,2,3,4,5])

In [181]:
arr4[:,np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [182]:
arr

array([[[ 3,  4,  5],
        [64, 23, 64]],

       [[56, 23, 74],
        [54, 94, 45]],

       [[95, 58, 44],
        [95, 86, 38]]])

In [186]:
arr[:,np.newaxis]

array([[[[ 3,  4,  5],
         [64, 23, 64]]],


       [[[56, 23, 74],
         [54, 94, 45]]],


       [[[95, 58, 44],
         [95, 86, 38]]]])