In [1]:
import numpy as np;

In [2]:
arr=np.arange(24).reshape(4,6);
for i in np.nditer(arr):
    print(i, end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 

In [3]:
for i in np.nditer(arr, flags=['external_loop']):
    print(i, end=' ')

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23] 

In [4]:
for i in np.nditer(arr, order='F', flags=['external_loop']):
    print(i, end=' ')

[ 0  6 12 18] [ 1  7 13 19] [ 2  8 14 20] [ 3  9 15 21] [ 4 10 16 22] [ 5 11 17 23] 

In [5]:
for i in np.nditer(arr, order='C', flags=['external_loop']):
    print(i, end=' ')

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23] 

In [6]:
arr.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [7]:
for i in np.nditer(arr.T):
    print(i , end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 

In [8]:
for i in np.nditer(arr.T, flags=['external_loop']):
    print(i, end=' ')

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23] 

In [9]:
for i in np.nditer(arr.T.copy()):
    print(i,end=' ')

0 6 12 18 1 7 13 19 2 8 14 20 3 9 15 21 4 10 16 22 5 11 17 23 

In [10]:
for i in np.nditer(arr.T.copy('F')):
    print(i, end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 

In [11]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [12]:
for i in np.nditer(arr, order='C', flags=['external_loop'], op_flags=['readwrite']):
    i[...]=45;
    print(i, end=' ')

[45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45] 

In [13]:
arr

array([[45, 45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45, 45]])

In [14]:
print('%d for %s '% (1,'apple'))

1 for apple 


### Tracking an Index or Multi-Index

In [15]:
arr

array([[45, 45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45, 45]])

In [16]:
it=np.nditer(arr, flags=['multi_index']);
while not it.finished:
    print("Index : %s   value : %d" % (it.multi_index, it[0]));
    it.iternext();

Index : (0, 0)   value : 45
Index : (0, 1)   value : 45
Index : (0, 2)   value : 45
Index : (0, 3)   value : 45
Index : (0, 4)   value : 45
Index : (0, 5)   value : 45
Index : (1, 0)   value : 45
Index : (1, 1)   value : 45
Index : (1, 2)   value : 45
Index : (1, 3)   value : 45
Index : (1, 4)   value : 45
Index : (1, 5)   value : 45
Index : (2, 0)   value : 45
Index : (2, 1)   value : 45
Index : (2, 2)   value : 45
Index : (2, 3)   value : 45
Index : (2, 4)   value : 45
Index : (2, 5)   value : 45
Index : (3, 0)   value : 45
Index : (3, 1)   value : 45
Index : (3, 2)   value : 45
Index : (3, 3)   value : 45
Index : (3, 4)   value : 45
Index : (3, 5)   value : 45


In [17]:
oneDarr=np.arange(20);

In [18]:
oneDarr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [19]:
it=np.nditer(oneDarr, flags=['f_index']);
for i in it:
    print("Index : <%d>   value : %d" % (it.index, it[0])); # not need of it.iternext() because for loop automatically call the next functio for it.

Index : <0>   value : 0
Index : <1>   value : 1
Index : <2>   value : 2
Index : <3>   value : 3
Index : <4>   value : 4
Index : <5>   value : 5
Index : <6>   value : 6
Index : <7>   value : 7
Index : <8>   value : 8
Index : <9>   value : 9
Index : <10>   value : 10
Index : <11>   value : 11
Index : <12>   value : 12
Index : <13>   value : 13
Index : <14>   value : 14
Index : <15>   value : 15
Index : <16>   value : 16
Index : <17>   value : 17
Index : <18>   value : 18
Index : <19>   value : 19


In [20]:
arr=np.arange(24).reshape(4,6);
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [21]:
# For multi Dimensional array

it=np.nditer(arr, flags=['f_index']);
for i in it:
    print("Index : <%d>   value : %d" % (it.index, it[0]));   # not need of it.iternext() because for loop automatically call the next functio for it.

Index : <0>   value : 0
Index : <4>   value : 1
Index : <8>   value : 2
Index : <12>   value : 3
Index : <16>   value : 4
Index : <20>   value : 5
Index : <1>   value : 6
Index : <5>   value : 7
Index : <9>   value : 8
Index : <13>   value : 9
Index : <17>   value : 10
Index : <21>   value : 11
Index : <2>   value : 12
Index : <6>   value : 13
Index : <10>   value : 14
Index : <14>   value : 15
Index : <18>   value : 16
Index : <22>   value : 17
Index : <3>   value : 18
Index : <7>   value : 19
Index : <11>   value : 20
Index : <15>   value : 21
Index : <19>   value : 22
Index : <23>   value : 23


In [22]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [23]:
iterator=np.nditer(arr, flags=['multi_index']);
while not iterator.finished:
    print("Value : %d   Index : %s" % (iterator[0], iterator.multi_index));
    iterator.iternext();

Value : 0   Index : (0, 0)
Value : 1   Index : (0, 1)
Value : 2   Index : (0, 2)
Value : 3   Index : (0, 3)
Value : 4   Index : (0, 4)
Value : 5   Index : (0, 5)
Value : 6   Index : (1, 0)
Value : 7   Index : (1, 1)
Value : 8   Index : (1, 2)
Value : 9   Index : (1, 3)
Value : 10   Index : (1, 4)
Value : 11   Index : (1, 5)
Value : 12   Index : (2, 0)
Value : 13   Index : (2, 1)
Value : 14   Index : (2, 2)
Value : 15   Index : (2, 3)
Value : 16   Index : (2, 4)
Value : 17   Index : (2, 5)
Value : 18   Index : (3, 0)
Value : 19   Index : (3, 1)
Value : 20   Index : (3, 2)
Value : 21   Index : (3, 3)
Value : 22   Index : (3, 4)
Value : 23   Index : (3, 5)


#### Iterator.iternext() Function

In [80]:
arrr=np.array([23,634,542,3]);
it=np.nditer(arrr)

In [81]:
it.__next__()

array(23)

In [82]:
it[0]

array(23)

In [84]:
it.__next__()

array(634)

In [85]:
it[0]

array(634)

In [86]:
it.iternext()

True

In [87]:
it[0]

array(542)

In [88]:
it.iternext()

True

In [89]:
it[0]

array(3)

In [90]:
it.iternext()

False

### Iterating as a Specific Data Type

In [177]:
ar=np.arange(12);
for i in np.nditer(ar, flags=['external_loop'], op_flags=['readonly','copy'], op_dtypes=[np.int64]):
    print(i);
print(ar.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
int32


In [178]:
for i in np.nditer(ar, flags=['external_loop'], op_flags=['readonly', 'copy'], op_dtypes=[np.complex128]):
    print(i)

[ 0.+0.j  1.+0.j  2.+0.j  3.+0.j  4.+0.j  5.+0.j  6.+0.j  7.+0.j  8.+0.j
  9.+0.j 10.+0.j 11.+0.j]


In [179]:
for i in np.nditer(ar, flags=['external_loop', 'buffered'], op_dtypes=[np.float64]):
    print(i)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]


In [180]:
for i in np.nditer(ar, flags=['external_loop', 'buffered'], op_dtypes=[np.int32]):
    print(i)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [181]:
for i in np.nditer(ar, flags=['external_loop', 'buffered'], op_dtypes=[np.int16], casting='same_kind'):
    print(i);

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [182]:
a=np.array([i for i in np.nditer(ar, flags=['external_loop', 'buffered'], op_dtypes=[np.int16], casting='same_kind')]);

In [183]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]], dtype=int16)

In [184]:
a.shape

(1, 12)

In [187]:
array=np.arange(12).reshape(2,6);
for i in np.nditer(array, flags=['buffered'], op_dtypes=[np.float64]):
    print(i, end=' ');

0.0 1.0 2.0 3.0 4.0 5.0 6.0 7.0 8.0 9.0 10.0 11.0 

In [201]:
def ftn():
    array=np.arange(12).reshape(2,6);
    for i in np.nditer(array, flags=['external_loop'], op_flags=['readonly', 'copy'], op_dtypes=[np.float64]):
        print(i**i, end=' ');
    print();

In [202]:
%time ftn();

[1.00000000e+00 1.00000000e+00 4.00000000e+00 2.70000000e+01
 2.56000000e+02 3.12500000e+03 4.66560000e+04 8.23543000e+05
 1.67772160e+07 3.87420489e+08 1.00000000e+10 2.85311671e+11] 
CPU times: total: 0 ns
Wall time: 1e+03 µs


In [203]:
def ftn1():
    array=np.arange(12).reshape(2,6);
    for i in np.nditer(array):
        print(np.float64(i**i), end=' ');
    print();

In [204]:
%time ftn1();

1.0 1.0 4.0 27.0 256.0 3125.0 46656.0 823543.0 16777216.0 387420489.0 1410065408.0 1843829075.0 
CPU times: total: 0 ns
Wall time: 2 ms
