## Iterating Over Array

### numpy.nditer object

In [1]:
import numpy as np;

In [2]:
l=[43,53,5,34,56];

In [3]:
iter(l)

In [4]:
i=iter(l)

In [5]:
i.__next__()

43

In [6]:
i.__next__()

53

In [7]:
a=np.array([34,63,234,5]);

In [8]:
i=np.nditer(a)

In [9]:
i.__next__()

array(34)

In [10]:
i.__next__()

array(63)

In [11]:
arr=np.arange(3,21).reshape(3,6);
for x in np.nditer(arr):
    print(x,end=' ');

3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 

In [12]:
l=list(np.nditer(arr))

In [13]:
l

[array(3),
 array(4),
 array(5),
 array(6),
 array(7),
 array(8),
 array(9),
 array(10),
 array(11),
 array(12),
 array(13),
 array(14),
 array(15),
 array(16),
 array(17),
 array(18),
 array(19),
 array(20)]

In [14]:
type(l)

list

In [15]:
17 in np.nditer(arr)

True

In [16]:
arr=np.linspace(1,20,15,endpoint=True).reshape(3,5);
for x in np.nditer(arr):
    print(x,end='   ');

print("\n\n");

for x in np.nditer(arr.T):
    print(x,end='    ');

1.0   2.357142857142857   3.7142857142857144   5.071428571428571   6.428571428571429   7.7857142857142865   9.142857142857142   10.5   11.857142857142858   13.214285714285715   14.571428571428573   15.928571428571429   17.285714285714285   18.642857142857142   20.0   


1.0    2.357142857142857    3.7142857142857144    5.071428571428571    6.428571428571429    7.7857142857142865    9.142857142857142    10.5    11.857142857142858    13.214285714285715    14.571428571428573    15.928571428571429    17.285714285714285    18.642857142857142    20.0    

In [17]:
arr=np.arange(9).reshape(3,3);
print(arr,"\n");

for x in np.nditer(arr):
    print(x,end=' ');
    
print("\n");

for x in np.nditer(arr.T):
    print(x,end=' ');
    
print("\n");

for x in np.nditer(arr.T.copy(order='C')):
    print(x,end=' ');
    
print("\n");
    
for x in np.nditer(arr.T.copy()):
    print(x,end=' ');

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

0 1 2 3 4 5 6 7 8 

0 1 2 3 4 5 6 7 8 

0 3 6 1 4 7 2 5 8 

0 3 6 1 4 7 2 5 8 

### Controlling Iteration Order
- Order refer to how elements are stored in memory.
- Numpy supports two primary memory orders for array
- C-Contiguous (Row-Major) Order
- Fortran-Contiguous (Column-Major) Order
- An important thing to be aware of for this iteration is that the order is chosen to match the memory layout of the array
instead of using a standard C or Fortran ordering

In [18]:
## Note default order='K' which mean keep the existing order

arr=np.arange(10).reshape(2,5);
print(arr);
print();
for x in np.nditer(arr, order='F'):     # order='F' represet column major order
    print(x,end=' ');
    
print("\n\n");

for x in np.nditer(arr, order='C'):     # orde='C' represent row major order
    print(x,end=' ');

[[0 1 2 3 4]
 [5 6 7 8 9]]

0 5 1 6 2 7 3 8 4 9 


0 1 2 3 4 5 6 7 8 9 

In [19]:
arr.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

### Modifying Array Values
- Default mode of np.nditer is read-only
- read-write mode op_flags=['readwrite']
- read-only mode  op_flags=['readonly']
- writeonly mode  op_flags=['writeonly']
- To actually modify the element of the array, x should be indexed with the ellipsis.  e.g : x[...]=1000

In [20]:
# understanding that assingment in python simply changes a reference in the local or global variable dictionary instead of modifying an existing variable in place.

arr=np.full((3,2), 45, dtype='i4');
print(arr);
for x in np.nditer(arr):
    x=1000;
    
print("\n",arr);

[[45 45]
 [45 45]
 [45 45]]

 [[45 45]
 [45 45]
 [45 45]]


In [21]:
# understanding that nditer object treats the input array as read-only object.

arr=np.full_like(arr, 34, dtype='i8', subok=True);
print(arr,"\n");

for x in np.nditer(arr):
    x[...]=100;

[[34 34]
 [34 34]
 [34 34]] 



ValueError: assignment destination is read-only

In [22]:
# To modify the array elements, you must specify either read-write or read-only mode. this is controlled with per-operand flags.

arr=np.zeros((3,4), dtype=np.single);
print(arr,'\n');

for x in np.nditer(arr, op_flags=['readwrite']):
    x[...]=x+20;
    
print(arr);

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[[20. 20. 20. 20.]
 [20. 20. 20. 20.]
 [20. 20. 20. 20.]]


### Using an External Loop
- A better approach is to move the one-dimensional innsermost loop into your code, external to the iterator.
- The nditer will try to provide chunks that are as large as possible to the inner loop.
- This mode is enabled by specifying an iterator flags..

In [23]:
arr=np.logspace(1.0,3.0,10,endpoint=True, base=10.0, dtype=np.single).reshape(2,5);
for x in np.nditer(arr, op_flags=['readwrite'], flags=['external_loop']):
    print(x,end=' ')
    
print("\n\n");

for x in np.nditer(arr, op_flags=['readonly'], flags=['external_loop'], order='F'):
    print(x,end=' ')
    
print("\n\n");

for x in np.nditer(arr, op_flags=['readonly'], flags=['external_loop'], order='C'):
    print(x,end=' ')

[  10.         16.681005   27.825594   46.41589    77.42637   129.15497
  215.44347   359.38138   599.48425  1000.      ] 


[ 10.      129.15497] [ 16.681005 215.44347 ] [ 27.825594 359.38138 ] [ 46.41589 599.48425] [  77.42637 1000.     ] 


[  10.         16.681005   27.825594   46.41589    77.42637   129.15497
  215.44347   359.38138   599.48425  1000.      ] 

In [24]:
arr1=np.random.randint(low=0, high=100, size=(4,6));
print(arr1,end='\n');
for column in np.nditer(arr1, order='F', op_flags=['readwrite'], flags=['external_loop']):
    print("Column : ",column);

[[ 0 24 45 33 60 24]
 [88 95 63 48 57 47]
 [33 19 46  3 16 39]
 [15 12 77 95 14 57]]
Column :  [ 0 88 33 15]
Column :  [24 95 19 12]
Column :  [45 63 46 77]
Column :  [33 48  3 95]
Column :  [60 57 16 14]
Column :  [24 47 39 57]


### Buffering the Array Elements
- By enabling buffering mode, the chunks provided by the iterator to the inner loop can be made larger, significantly
reducing the overhead of the Python interpreter.

In [25]:
arr=np.arange(24).reshape(4,6);
for i in np.nditer(arr, order='F', flags=['external_loop'], op_flags=['readwrite']):
    print(i,end=' ');
    
print('\n\n');
print('After Enabling Buffering Mode : \n');

for i in np.nditer(arr, order='F', flags=['external_loop', 'buffered'], op_flags=['readonly']):
    print(i, end=' ');

[ 0  6 12 18] [ 1  7 13 19] [ 2  8 14 20] [ 3  9 15 21] [ 4 10 16 22] [ 5 11 17 23] 


After Enabling Buffering Mode : 

[ 0  6 12 18  1  7 13 19  2  8 14 20  3  9 15 21  4 10 16 22  5 11 17 23] 

### np.ndenumerate(array_object)  Function

In [26]:
for i,v in np.ndenumerate(arr1):
    print("Index : {}   Value : {}".format(i,v));

Index : (0, 0)   Value : 0
Index : (0, 1)   Value : 24
Index : (0, 2)   Value : 45
Index : (0, 3)   Value : 33
Index : (0, 4)   Value : 60
Index : (0, 5)   Value : 24
Index : (1, 0)   Value : 88
Index : (1, 1)   Value : 95
Index : (1, 2)   Value : 63
Index : (1, 3)   Value : 48
Index : (1, 4)   Value : 57
Index : (1, 5)   Value : 47
Index : (2, 0)   Value : 33
Index : (2, 1)   Value : 19
Index : (2, 2)   Value : 46
Index : (2, 3)   Value : 3
Index : (2, 4)   Value : 16
Index : (2, 5)   Value : 39
Index : (3, 0)   Value : 15
Index : (3, 1)   Value : 12
Index : (3, 2)   Value : 77
Index : (3, 3)   Value : 95
Index : (3, 4)   Value : 14
Index : (3, 5)   Value : 57


In [28]:
# how to find index of a particular item
item=np.int32(input("Enter item : "));
for i,v in np.ndenumerate(arr1):
    if v==item:
        print(f"Value : {v}   Index : {i}");

Enter item : 15
Value : 15   Index : (3, 0)
