## Masked Array
- Masked arrays are arrays that may have missing or invalid entries.
- A masked array is the combination of a standard numpy.ndarray and a mask. 

### mask 
- 1. **nomask**
    - indicating that no value of the associated array is invalid.
- 2. **booleans array**
    - A booleans that determines for each element of the associated array whether the value is valid or not.
    - False -> Valid  ,    True -> Invalid

In [1]:
import numpy as np;
import numpy.ma as ma;

In [2]:
arr = np.array([1,5,-2,5,-6,23]);
arr

array([ 1,  5, -2,  5, -6, 23])

In [9]:
m_arr = ma.array(arr, mask=[0,0,1,0,1,0]);  # third and fifth value are masked
m_arr

masked_array(data=[1, 5, --, 5, --, 23],
             mask=[False, False,  True, False,  True, False],
       fill_value=999999)

In [11]:
m_arr.mean()   # calculate mean without considering invalid values

8.5

In [12]:
arr.mean()

4.333333333333333

In [16]:
# To create a masked array where all values close to 1.e20 are invalid,
arr = ma.masked_values([5.2, 62.4, 4.e20, 4, 34e43, 34], 4.e20);

In [17]:
arr

masked_array(data=[5.2, 62.4, --, 4.0, 3.4e+44, 34.0],
             mask=[False, False,  True, False, False, False],
       fill_value=4e+20)

In [28]:
arr = ma.masked_array([34, np.nan, np.inf, 353, 534]);
arr

masked_array(data=[ 34.,  nan,  inf, 353., 534.],
             mask=False,
       fill_value=1e+20)

In [29]:
m_arr = ma.masked_array([34, np.nan, np.inf, 353, 534], mask=[0,1,1,0,0]);
m_arr

masked_array(data=[34.0, --, --, 353.0, 534.0],
             mask=[False,  True,  True, False, False],
       fill_value=1e+20)

In [35]:
arr.mean()  # not masked array

nan

In [36]:
arr.std()     # not masked array

masked

In [37]:
m_arr.mean()   # masked array

307.0

In [38]:
m_arr.std()    # masked array

206.69945976384813

In [45]:
m_arr = ma.masked_values([43, np.inf, np.nan, 43.3, 345, np.inf], np.inf);
m_arr

masked_array(data=[43.0, --, nan, 43.3, 345.0, --],
             mask=[False,  True, False, False, False,  True],
       fill_value=inf)

### Constructing masked array using view of exsiting array

In [48]:
arr = np.array([43,53,12,53,-43]);
arr

array([ 43,  53,  12,  53, -43])

In [50]:
arr.view(ma.MaskedArray)

masked_array(data=[ 43,  53,  12,  53, -43],
             mask=False,
       fill_value=999999)

In [88]:
arr = np.array([[(3,4.6)],[(5,6.2)]], dtype=[('a', np.int32),('b', np.float16)])

In [89]:
arr.view(ma.MaskedArray)

masked_array(
  data=[[(3, 4.6015625)],
        [(5, 6.19921875)]],
  mask=[[(False, False)],
        [(False, False)]],
  fill_value=(999999, inf),
  dtype=[('a', '<i4'), ('b', '<f2')])

In [90]:
arr

array([[(3, 4.6)],
       [(5, 6.2)]], dtype=[('a', '<i4'), ('b', '<f2')])

In [91]:
arr.shape

(2, 1)

In [92]:
arr=np.array([4,5,5], dtype=("i1,i2,f2"))

In [93]:
arr

array([(4, 4, 4.), (5, 5, 5.), (5, 5, 5.)],
      dtype=[('f0', 'i1'), ('f1', '<i2'), ('f2', '<f2')])

In [60]:
arr = np.arange(10);
print(arr);
print(arr.dtype);
print(arr.dtype.byteorder);
print(arr.flags);
print(arr.base);
print(arr.ndim);
print(arr.shape);
print(arr.copy())
print(np.info(arr))

[0 1 2 3 4 5 6 7 8 9]
int32
=
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

None
1
(10,)
[0 1 2 3 4 5 6 7 8 9]
class:  ndarray
shape:  (10,)
strides:  (4,)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x2049972d7a0
byteorder:  little
byteswap:  False
type: int32
None


In [69]:
m_arr = ma.masked_array(arr, dtype=np.int16, mask=np.zeros((1,10)), copy=False, ndmin=2, keep_mask=False, fill_value=0, order='F',)

In [70]:
m_arr

masked_array(data=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]],
             mask=[[False, False, False, False, False, False, False,
                    False, False, False]],
       fill_value=0,
            dtype=int16)

In [71]:
m_arr.shape

(1, 10)

In [72]:
np.info(m_arr)

class:  MaskedArray
shape:  (1, 10)
strides:  (2, 2)
itemsize:  2
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x204983d5e90
byteorder:  little
byteswap:  False
type: int16


## Different ways of creating masked array

### numpy.ma.asarray(a, dtype=None, order=None)
- Convert the input to a masked array of the given data-type.

In [96]:
a = np.arange(10,20)
print(a);
print(a.dtype)

[10 11 12 13 14 15 16 17 18 19]
int32


In [97]:
ma.asarray(a, dtype=np.int16, order=None)

masked_array(data=[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
             mask=False,
       fill_value=999999,
            dtype=int16)

In [99]:
a = np.linspace(2,3,20, dtype='e');
print(a);
print(a.dtype)

[2.    2.053 2.105 2.158 2.21  2.264 2.316 2.37  2.422 2.475 2.525 2.578
 2.63  2.684 2.736 2.79  2.842 2.895 2.947 3.   ]
float16


In [100]:
ma.asarray(a, dtype='f')

masked_array(data=[2.       , 2.0527344, 2.1054688, 2.1582031, 2.2109375,
                   2.2636719, 2.3164062, 2.3691406, 2.421875 , 2.4746094,
                   2.5253906, 2.578125 , 2.6308594, 2.6835938, 2.7363281,
                   2.7890625, 2.8417969, 2.8945312, 2.9472656, 3.       ],
             mask=False,
       fill_value=1e+20,
            dtype=float32)

In [101]:
a = np.array([34,53,23], dtype='i2');
print(a);
print(a.dtype);

[34 53 23]
int16


In [106]:
ma.asarray(a, dtype=np.float16)

masked_array(data=[34., 53., 23.],
             mask=False,
       fill_value=1e+20,
            dtype=float16)

### numpy.ma.asanyarray(a, dtype=None)
- Convert the input to a masked array, conserving subclasses.


In [107]:
a = np.array([43,4,53,34]);
print(a);
print(a.dtype);

[43  4 53 34]
int32


In [110]:
ma.asanyarray(a, dtype=np.float16)

masked_array(data=[43.,  4., 53., 34.],
             mask=False,
       fill_value=1e+20,
            dtype=float16)

In [111]:
a=np.zeros((3,3), dtype='l');
print(a);
print(a.dtype);

[[0 0 0]
 [0 0 0]
 [0 0 0]]
int32


In [112]:
ma.asanyarray(a, dtype='b')

masked_array(
  data=[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],
  mask=False,
  fill_value=999999,
  dtype=int8)

### numpy.ma.fix_invalid(a, mask=False, copy=True, fill_value=None)
- Return input with invalid data masked and replaced by a fill value.

In [113]:
a = np.array([34,53,-34,-42,35,-23,43]);
print(a);
print(a.dtype)

[ 34  53 -34 -42  35 -23  43]
int32


In [123]:
m_arr = ma.masked_array(a, mask=[0,0,1,1,0,1,0], copy=True, fill_value=0)

In [124]:
m_arr

masked_array(data=[34, 53, --, --, 35, --, 43],
             mask=[False, False,  True,  True, False,  True, False],
       fill_value=0)

In [125]:
ma.fix_invalid(m_arr)

masked_array(data=[34, 53, --, --, 35, --, 43],
             mask=[False, False,  True,  True, False,  True, False],
       fill_value=0)

In [132]:
arr = np.array([np.nan,53,np.inf, np.nan,343, np.inf]);
print(arr);
print(arr.dtype);

[ nan  53.  inf  nan 343.  inf]
float64


In [133]:
ma.fix_invalid(arr)

masked_array(data=[--, 53.0, --, --, 343.0, --],
             mask=[ True, False,  True,  True, False,  True],
       fill_value=1e+20)

In [134]:
ma.fix_invalid(arr, fill_value=0)

masked_array(data=[--, 53.0, --, --, 343.0, --],
             mask=[ True, False,  True,  True, False,  True],
       fill_value=1e+20)

### numpy.ma.masked_equal(x, value, copy=True)
- Mask an array where equal to a given value.

In [135]:
arr = np.arange(1,21).reshape(4,5);
print(arr);
print(arr.dtype)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
int32


In [136]:
ma.masked_equal(arr, value=12)

masked_array(
  data=[[1, 2, 3, 4, 5],
        [6, 7, 8, 9, 10],
        [11, --, 13, 14, 15],
        [16, 17, 18, 19, 20]],
  mask=[[False, False, False, False, False],
        [False, False, False, False, False],
        [False,  True, False, False, False],
        [False, False, False, False, False]],
  fill_value=12)

In [139]:
ma.masked_equal(arr, value=20)

masked_array(
  data=[[1, 2, 3, 4, 5],
        [6, 7, 8, 9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, --]],
  mask=[[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False,  True]],
  fill_value=20)

In [140]:
ma.masked_greater(arr, 10)

masked_array(
  data=[[1, 2, 3, 4, 5],
        [6, 7, 8, 9, 10],
        [--, --, --, --, --],
        [--, --, --, --, --]],
  mask=[[False, False, False, False, False],
        [False, False, False, False, False],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],
  fill_value=999999)

In [141]:
ma.masked_greater(arr, 12)

masked_array(
  data=[[1, 2, 3, 4, 5],
        [6, 7, 8, 9, 10],
        [11, 12, --, --, --],
        [--, --, --, --, --]],
  mask=[[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False,  True,  True,  True],
        [ True,  True,  True,  True,  True]],
  fill_value=999999)

In [143]:
ma.masked_greater(arr, 3)

masked_array(
  data=[[1, 2, 3, --, --],
        [--, --, --, --, --],
        [--, --, --, --, --],
        [--, --, --, --, --]],
  mask=[[False, False, False,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],
  fill_value=999999)

In [144]:
ma.masked_greater_equal(arr, 12)

masked_array(
  data=[[1, 2, 3, 4, 5],
        [6, 7, 8, 9, 10],
        [11, --, --, --, --],
        [--, --, --, --, --]],
  mask=[[False, False, False, False, False],
        [False, False, False, False, False],
        [False,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],
  fill_value=999999)

In [146]:
ma.masked_greater_equal(arr,20)

masked_array(
  data=[[1, 2, 3, 4, 5],
        [6, 7, 8, 9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, --]],
  mask=[[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False,  True]],
  fill_value=999999)

In [149]:
ma.masked_greater_equal(arr, 10)

masked_array(
  data=[[1, 2, 3, 4, 5],
        [6, 7, 8, 9, --],
        [--, --, --, --, --],
        [--, --, --, --, --]],
  mask=[[False, False, False, False, False],
        [False, False, False, False,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],
  fill_value=999999)

In [151]:
ma.masked_less(arr, 10)

masked_array(
  data=[[--, --, --, --, --],
        [--, --, --, --, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],
  mask=[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],
  fill_value=999999)

In [152]:
ma.masked_less(arr, 5)

masked_array(
  data=[[--, --, --, --, 5],
        [6, 7, 8, 9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],
  mask=[[ True,  True,  True,  True, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],
  fill_value=999999)

In [153]:
ma.masked_less(arr, 2)

masked_array(
  data=[[--, 2, 3, 4, 5],
        [6, 7, 8, 9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],
  mask=[[ True, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],
  fill_value=999999)

In [154]:
ma.masked_less_equal(arr, 5)

masked_array(
  data=[[--, --, --, --, --],
        [6, 7, 8, 9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],
  mask=[[ True,  True,  True,  True,  True],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],
  fill_value=999999)

In [156]:
ma.masked_less_equal(arr, 10)

masked_array(
  data=[[--, --, --, --, --],
        [--, --, --, --, --],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],
  mask=[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [False, False, False, False, False],
        [False, False, False, False, False]],
  fill_value=999999)

In [157]:
ma.masked_less_equal(arr,3)

masked_array(
  data=[[--, --, --, 4, 5],
        [6, 7, 8, 9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],
  mask=[[ True,  True,  True, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],
  fill_value=999999)

In [158]:
ma.masked_invalid(arr)

masked_array(
  data=[[1, 2, 3, 4, 5],
        [6, 7, 8, 9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],
  mask=[[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],
  fill_value=999999)

In [160]:
ma.masked_invalid([34,53,np.nan, np.inf])

masked_array(data=[34.0, 53.0, --, --],
             mask=[False, False,  True,  True],
       fill_value=1e+20)

In [162]:
ma.masked_invalid([34,np.nan, np.inf, np.nan, 3434, 434, np.inf])

masked_array(data=[34.0, --, --, --, 3434.0, 434.0, --],
             mask=[False,  True,  True,  True, False, False,  True],
       fill_value=1e+20)

In [163]:
ma.masked_not_equal(arr, 20)

masked_array(
  data=[[--, --, --, --, --],
        [--, --, --, --, --],
        [--, --, --, --, --],
        [--, --, --, --, 20]],
  mask=[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True, False]],
  fill_value=999999)

In [164]:
ma.masked_not_equal(arr, 1)

masked_array(
  data=[[1, --, --, --, --],
        [--, --, --, --, --],
        [--, --, --, --, --],
        [--, --, --, --, --]],
  mask=[[False,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],
  fill_value=999999)

In [165]:
ma.masked_not_equal(arr, 12)

masked_array(
  data=[[--, --, --, --, --],
        [--, --, --, --, --],
        [--, 12, --, --, --],
        [--, --, --, --, --]],
  mask=[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True, False,  True,  True,  True],
        [ True,  True,  True,  True,  True]],
  fill_value=999999)

In [166]:
ma.masked_inside(arr, 12, 18)

masked_array(
  data=[[1, 2, 3, 4, 5],
        [6, 7, 8, 9, 10],
        [11, --, --, --, --],
        [--, --, --, 19, 20]],
  mask=[[False, False, False, False, False],
        [False, False, False, False, False],
        [False,  True,  True,  True,  True],
        [ True,  True,  True, False, False]],
  fill_value=999999)

In [167]:
ma.masked_inside(arr, 12, 19)

masked_array(
  data=[[1, 2, 3, 4, 5],
        [6, 7, 8, 9, 10],
        [11, --, --, --, --],
        [--, --, --, --, 20]],
  mask=[[False, False, False, False, False],
        [False, False, False, False, False],
        [False,  True,  True,  True,  True],
        [ True,  True,  True,  True, False]],
  fill_value=999999)

In [168]:
ma.masked_inside(arr, 10, 15)

masked_array(
  data=[[1, 2, 3, 4, 5],
        [6, 7, 8, 9, --],
        [--, --, --, --, --],
        [16, 17, 18, 19, 20]],
  mask=[[False, False, False, False, False],
        [False, False, False, False,  True],
        [ True,  True,  True,  True,  True],
        [False, False, False, False, False]],
  fill_value=999999)

In [169]:
ma.masked_outside(arr, 2, 5)

masked_array(
  data=[[--, 2, 3, 4, 5],
        [--, --, --, --, --],
        [--, --, --, --, --],
        [--, --, --, --, --]],
  mask=[[ True, False, False, False, False],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],
  fill_value=999999)

In [171]:
ma.masked_outside(arr, 4, 12)

masked_array(
  data=[[--, --, --, 4, 5],
        [6, 7, 8, 9, 10],
        [11, 12, --, --, --],
        [--, --, --, --, --]],
  mask=[[ True,  True,  True, False, False],
        [False, False, False, False, False],
        [False, False,  True,  True,  True],
        [ True,  True,  True,  True,  True]],
  fill_value=999999)

In [173]:
ma.masked_outside(arr, 10, 20)

masked_array(
  data=[[--, --, --, --, --],
        [--, --, --, --, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],
  mask=[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],
  fill_value=999999)

In [174]:
ma.masked_outside(arr, 10 , 30)

masked_array(
  data=[[--, --, --, --, --],
        [--, --, --, --, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],
  mask=[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],
  fill_value=999999)