In [7]:
import numpy as np;
import numpy.ma as ma

In [8]:
arr = np.arange(5);
arr

array([0, 1, 2, 3, 4])

In [9]:
m_arr = np.ma.array(arr, mask=[1,0,0,1,1]);
m_arr

masked_array(data=[--, 1, 2, --, --],
             mask=[ True, False, False,  True,  True],
       fill_value=999999)

In [10]:
m_arr.shape

(5,)

In [11]:
m_arr.size

5

In [13]:
arr1 = np.linspace(1,2,12, dtype=np.half).reshape(3,4);
arr1

array([[1.   , 1.091, 1.182, 1.272],
       [1.363, 1.454, 1.546, 1.637],
       [1.728, 1.818, 1.909, 2.   ]], dtype=float16)

In [14]:
m_arr1 = ma.masked_values(arr1, 1.454);
m_arr1

masked_array(
  data=[[1.0, 1.0908203125, 1.181640625, 1.2724609375],
        [1.36328125, --, 1.5458984375, 1.63671875],
        [1.7275390625, 1.818359375, 1.9091796875, 2.0]],
  mask=[[False, False, False, False],
        [False,  True, False, False],
        [False, False, False, False]],
  fill_value=1.454,
  dtype=float16)

In [17]:
m_arr2 = ma.MaskedArray(arr, mask=[0,1,1,0,1]);
m_arr2

masked_array(data=[0, --, --, 3, --],
             mask=[False,  True,  True, False,  True],
       fill_value=999999)

In [21]:
m_arr3 = ma.masked_array(m_arr, keep_mask=True);
m_arr3

masked_array(data=[--, 1, 2, --, --],
             mask=[ True, False, False,  True,  True],
       fill_value=999999)

In [22]:
arr

array([0, 1, 2, 3, 4])

In [23]:
m_arr4 = arr.view(ma.MaskedArray)

In [24]:
m_arr4

masked_array(data=[0, 1, 2, 3, 4],
             mask=False,
       fill_value=999999)

In [26]:
ma.asarray(arr, dtype=np.int32)

masked_array(data=[0, 1, 2, 3, 4],
             mask=False,
       fill_value=999999)

In [28]:
ma.asanyarray(arr, dtype=np.float16)

masked_array(data=[0., 1., 2., 3., 4.],
             mask=False,
       fill_value=1e+20,
            dtype=float16)

In [31]:
ma.fix_invalid(arr, mask=[0,1,0,1,1], fill_value=3)

masked_array(data=[0, --, 2, --, --],
             mask=[False,  True, False,  True,  True],
       fill_value=999999)

In [32]:
ma.fix_invalid(arr, mask=[0,0,0,0,1], copy=False, fill_value=30)

masked_array(data=[0, 1, 2, 3, --],
             mask=[False, False, False, False,  True],
       fill_value=999999)

In [33]:
ma.masked_equal(arr, 2)

masked_array(data=[0, 1, --, 3, 4],
             mask=[False, False,  True, False, False],
       fill_value=2)

In [34]:
ma.masked_greater(arr,3)

masked_array(data=[0, 1, 2, 3, --],
             mask=[False, False, False, False,  True],
       fill_value=999999)

In [35]:
ma.masked_greater_equal(arr, 3)

masked_array(data=[0, 1, 2, --, --],
             mask=[False, False, False,  True,  True],
       fill_value=999999)

In [36]:
ma.masked_less(arr, 3)

masked_array(data=[--, --, --, 3, 4],
             mask=[ True,  True,  True, False, False],
       fill_value=999999)

In [37]:
ma.masked_less_equal(arr, 4)

masked_array(data=[--, --, --, --, --],
             mask=[ True,  True,  True,  True,  True],
       fill_value=999999,
            dtype=int32)

In [38]:
ma.masked_inside(arr, 2,4)

masked_array(data=[0, 1, --, --, --],
             mask=[False, False,  True,  True,  True],
       fill_value=999999)

In [39]:
ma.masked_outside(arr, 1,2)

masked_array(data=[--, 1, 2, --, --],
             mask=[ True, False, False,  True,  True],
       fill_value=999999)

In [40]:
ma.masked_invalid(arr)

masked_array(data=[0, 1, 2, 3, 4],
             mask=[False, False, False, False, False],
       fill_value=999999)

In [41]:
ma.masked_object(arr, 3)

masked_array(data=[0, 1, 2, --, 4],
             mask=[False, False, False,  True, False],
       fill_value=3)

In [42]:
ma.masked_values(arr, 2)

masked_array(data=[0, 1, --, 3, 4],
             mask=[False, False,  True, False, False],
       fill_value=2)

In [43]:
ma.masked_where(arr==2, arr)

masked_array(data=[0, 1, --, 3, 4],
             mask=[False, False,  True, False, False],
       fill_value=999999)

In [44]:
ma.masked_where(m_arr==2, m_arr)

masked_array(data=[--, 1, --, --, --],
             mask=[ True, False,  True,  True,  True],
       fill_value=999999)

In [46]:
ma.masked_where(m_arr2, m_arr2)

masked_array(data=[0, --, --, --, --],
             mask=[False,  True,  True,  True,  True],
       fill_value=999999)

In [47]:
m_arr.data

array([0, 1, 2, 3, 4])

In [48]:
m_arr.mask

array([ True, False, False,  True,  True])

In [49]:
m_arr.recordmask

array([ True, False, False,  True,  True])

In [50]:
m_arr.fill_value

999999

In [52]:
m_arr.baseclass

numpy.ndarray

In [54]:
m_arr.sharedmask

True

In [56]:
m_arr.hardmask

False

In [57]:
m_arr.__array_priority__

15