## Matrix Object

matrix objects inherit from the ndarray and therefore, they have the same attributes and methods of ndarrays. There are six important differences of matrix objects, however, that may lead to unexpected results when you use matrices but expect them to act like arrays:
1. Matrix objects can be created using a string notation to allow Matlab-style syntax where spaces separate columns and - semicolons (‘;’) separate rows.

2. Matrix objects are always two-dimensional. This has far-reaching implications, in that m.ravel() is still twodimensional (with a 1 in the first dimension) and item selection returns two-dimensional objects so that sequence behavior is fundamentally different than arrays.

3. Matrix objects over-ride multiplication to be matrix-multiplication. Make sure you understand this for functions that you may want to receive matrices. Especially in light of the fact that asanyarray(m) returns a matrix when m is a matrix.

4. Matrix objects over-ride power to be matrix raised to a power. The same warning about using power inside a function that uses asanyarray(...) to get an array object holds for this fact.

5. The default __array_priority__ of matrix objects is 10.0, and therefore mixed operations with ndarrays always produce matrices.

6. Matrices have special attributes which make calculations easier. These are

### First Difference

In [1]:
import numpy as np;

In [2]:
matrix = np.matrix('[23 23 52; 12 23 64]');
matrix

matrix([[23, 23, 52],
        [12, 23, 64]])

In [3]:
matrix = np.matrix('[32,56,23; 54 63,23]')

In [4]:
matrix

matrix([[32, 56, 23],
        [54, 63, 23]])

In [5]:
matrix.size

6

In [6]:
matrix.shape

(2, 3)

### Fifth Difference 

In [7]:
arr = np.array([[345,525,632],[346,235,744]]);
print(arr);
print(type(arr))

[[345 525 632]
 [346 235 744]]
<class 'numpy.ndarray'>


In [8]:
matrix = np.matrix('[352 562 634; 638 378 593]');
print(matrix);
print(type(matrix));

[[352 562 634]
 [638 378 593]]
<class 'numpy.matrix'>


In [9]:
print(arr+matrix);
print(type(arr+matrix));

[[ 697 1087 1266]
 [ 984  613 1337]]
<class 'numpy.matrix'>


#### matrix.T
- Returns the transpose of the matrix.

In [10]:
matrix

matrix([[352, 562, 634],
        [638, 378, 593]])

In [11]:
matrix.T

matrix([[352, 638],
        [562, 378],
        [634, 593]])

In [12]:
type(matrix)

numpy.matrix

In [13]:
matrix.getT()     # matrix.getT()  method retrun transopose of a matrix

matrix([[352, 638],
        [562, 378],
        [634, 593]])

In [14]:
a = np.array([[34,563,23,52,34],[63,23,63,23,53]]);
print(a);
print(type(a));

[[ 34 563  23  52  34]
 [ 63  23  63  23  53]]
<class 'numpy.ndarray'>


In [15]:
m = np.matrix(a);
print(m);
print(type(m));
print(m.size);
print(m.shape);

[[ 34 563  23  52  34]
 [ 63  23  63  23  53]]
<class 'numpy.matrix'>
10
(2, 5)


### Second difference

In [16]:
m.ravel()

matrix([[ 34, 563,  23,  52,  34,  63,  23,  63,  23,  53]])

In [17]:
m.ravel(order='F')

matrix([[ 34,  63, 563,  23,  23,  63,  52,  23,  34,  53]])

In [18]:
m_arr = np.asanyarray(m);
print(m_arr);
print(type(m_arr));

[[ 34 563  23  52  34]
 [ 63  23  63  23  53]]
<class 'numpy.matrix'>


In [19]:
matrix

matrix([[352, 562, 634],
        [638, 378, 593]])

In [20]:
m

matrix([[ 34, 563,  23,  52,  34],
        [ 63,  23,  63,  23,  53]])

In [21]:
m = np.matrix('[23 23; 62 23; 63 12]')
m

matrix([[23, 23],
        [62, 23],
        [63, 12]])

### Third difference

In [22]:
m2 = matrix*m    # it peroform matrix multiplication
print(m2);
print(type(m2))

[[82882 28630]
 [75469 30484]]
<class 'numpy.matrix'>


#### This is the difference between np.asarray() and np.asanyarray() method

In [23]:
type(np.asanyarray(m2))

numpy.matrix

In [24]:
type(np.asarray(m2))

numpy.ndarray

#### matrix.H
- Returns the (complex) conjugate transpose of self.

In [25]:
matrix = np.matrix(np.arange(12)).reshape(3,4)

In [26]:
matrix

matrix([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [27]:
matrix = matrix - 1j*matrix;

In [28]:
matrix

matrix([[ 0. +0.j,  1. -1.j,  2. -2.j,  3. -3.j],
        [ 4. -4.j,  5. -5.j,  6. -6.j,  7. -7.j],
        [ 8. -8.j,  9. -9.j, 10.-10.j, 11.-11.j]])

In [29]:
matrix.H

matrix([[ 0. -0.j,  4. +4.j,  8. +8.j],
        [ 1. +1.j,  5. +5.j,  9. +9.j],
        [ 2. +2.j,  6. +6.j, 10.+10.j],
        [ 3. +3.j,  7. +7.j, 11.+11.j]])

In [30]:
matrix = np.matrix(np.arange(12) + 1j * np.linspace(1,2,12).round(2));

In [31]:
matrix.shape=(3,4)
matrix

matrix([[ 0.+1.j  ,  1.+1.09j,  2.+1.18j,  3.+1.27j],
        [ 4.+1.36j,  5.+1.45j,  6.+1.55j,  7.+1.64j],
        [ 8.+1.73j,  9.+1.82j, 10.+1.91j, 11.+2.j  ]])

In [32]:
matrix.dtype

dtype('complex128')

In [33]:
matrix.getH()

matrix([[ 0.-1.j  ,  4.-1.36j,  8.-1.73j],
        [ 1.-1.09j,  5.-1.45j,  9.-1.82j],
        [ 2.-1.18j,  6.-1.55j, 10.-1.91j],
        [ 3.-1.27j,  7.-1.64j, 11.-2.j  ]])

#### matrix.I
- Returns the (multiplicative) inverse of invertible self.

In [34]:
m = np.matrix('[2,5; 6,2]')

In [35]:
m.I

matrix([[-0.07692308,  0.19230769],
        [ 0.23076923, -0.07692308]])

#### matrix.A
- Return self as an ndarray object

In [36]:
m = np.matrix(np.arange(20).reshape(4,5));
print(m);
print(type(m));

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
<class 'numpy.matrix'>


In [37]:
print(m.A);
print(type(m.A))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
<class 'numpy.ndarray'>


#### matrix.A1
- Return self as a flattened ndarray.

In [38]:
matrix = np.matrix('[345 384 235 523; 538 378 383 594]');
print(matrix);
print(matrix.A1);

[[345 384 235 523]
 [538 378 383 594]]
[345 384 235 523 538 378 383 594]


In [39]:
np.asarray(matrix).ravel()

array([345, 384, 235, 523, 538, 378, 383, 594])

- The matrix class is a Python subclass of the ndarray and can be used as a reference for how to construct your own subclass of the ndarray. Matrices can be created from other matrices, strings, and anything else that can be converted to an ndarray . The name “mat “is an alias for “matrix “in NumPy.


### class numpy.matrix
- Returns a matrix from an array-like object, or from a string of data. 
- **A matrix is a specialized 2-D array that retains its 2-D nature through operations. It has certain special operators, such as * (matrix multiplication) and ** (matrix power).**

In [40]:
m1 = np.matrix('[235 632 523 466; 958 494 387 958; 339 495 349 934]', dtype=np.int32);
print(m1)

[[235 632 523 466]
 [958 494 387 958]
 [339 495 349 934]]


In [41]:
print("Data type :", m1.dtype);
print("Shape : ", m1.shape);
print("Strides : ", m1.strides);
print("Size : ", m1.size);
print("Itemsize : ", m1.itemsize);
print("Flat : ", m1.flat[0]);
print("Flags : \n", m1.flags);
print("Data : ", m1.data)
print("ndim : ", m1.ndim);
print("nbytes : ", m1.nbytes);
print("Base : ", type(m1.base));

Data type : int32
Shape :  (3, 4)
Strides :  (16, 4)
Size :  12
Itemsize :  4
Flat :  235
Flags : 
   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

Data :  <memory at 0x00000232F29F9A40>
ndim :  2
nbytes :  48
Base :  <class 'numpy.ndarray'>


In [42]:
np.info(m1)

class:  matrix
shape:  (3, 4)
strides:  (16, 4)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x232f094b7f0
byteorder:  little
byteswap:  False
type: int32


In [43]:
m2 = np.matrix([[548,395,395],[593,356,356]]);
m2

matrix([[548, 395, 395],
        [593, 356, 356]])

In [44]:
m2.real

matrix([[548, 395, 395],
        [593, 356, 356]])

In [45]:
m2.imag

matrix([[0, 0, 0],
        [0, 0, 0]])

In [46]:
type(m2.base)

numpy.ndarray

In [47]:
m2.base is None

False

# Methods

In [48]:
matrix = np.matrix(np.arange(20).reshape(4,5));
print(matrix);

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [49]:
matrix.all()

False

In [50]:
matrix.all(axis=0)

matrix([[False,  True,  True,  True,  True]])

In [51]:
matrix.all(axis=1)

matrix([[False],
        [ True],
        [ True],
        [ True]])

In [52]:
matrix.any()

True

In [53]:
matrix.any(axis=0)

matrix([[ True,  True,  True,  True,  True]])

In [54]:
matrix.any(axis=1)

matrix([[ True],
        [ True],
        [ True],
        [ True]])

In [60]:
matrix[matrix!=0]

matrix([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
         17, 18, 19]])

In [63]:
matrix.argmin()

0

In [65]:
matrix.argmin(axis=0)

matrix([[0, 0, 0, 0, 0]], dtype=int64)

In [66]:
matrix.argmin(axis=1)

matrix([[0],
        [0],
        [0],
        [0]], dtype=int64)

In [64]:
matrix.argmax()

19

In [67]:
matrix.argmax(axis=0)

matrix([[3, 3, 3, 3, 3]], dtype=int64)

In [68]:
matrix.argmax(axis=1)

matrix([[4],
        [4],
        [4],
        [4]], dtype=int64)

In [80]:
#argpartition(kth[, axis, kind, order])
matrix = np.matrix(np.random.randint(low=0, high=100, size=(4,5)))
print(matrix)

matrix.argpartition(2)

[[97 87 57 79 87]
 [24  2 67 64 37]
 [63  5 51 23 42]
 [51 37 50 99 54]]


matrix([[2, 3, 1, 0, 4],
        [1, 0, 4, 3, 2],
        [1, 3, 4, 0, 2],
        [1, 2, 0, 3, 4]], dtype=int64)

In [81]:
# partition
matrix.partition(1);
matrix

matrix([[57, 79, 97, 87, 87],
        [ 2, 24, 67, 64, 37],
        [ 5, 23, 51, 63, 42],
        [37, 50, 51, 99, 54]])

In [86]:
matrix = np.matrix(np.random.randint(0,100,(5,6)));
matrix

matrix([[56, 79, 35, 56, 14, 98],
        [35, 97, 46, 47, 13, 36],
        [75, 49, 51, 97, 59, 15],
        [29, 69, 53, 86, 11, 28],
        [60, 51, 23, 97, 58, 68]])

In [87]:
matrix.partition(2, axis=1);
matrix

matrix([[14, 35, 56, 79, 56, 98],
        [13, 35, 36, 47, 97, 46],
        [15, 49, 51, 97, 59, 75],
        [11, 28, 29, 86, 53, 69],
        [23, 51, 58, 97, 60, 68]])

In [88]:
matrix.partition(2, axis=0);
matrix

matrix([[11, 28, 29, 47, 53, 46],
        [13, 35, 36, 79, 56, 68],
        [14, 35, 51, 86, 59, 69],
        [15, 49, 56, 97, 97, 75],
        [23, 51, 58, 97, 60, 98]])

In [111]:
#argsort([axis, kind, order])
matrix.argsort()

matrix([[0, 1, 2, 3, 4, 5],
        [0, 1, 2, 3, 4, 5],
        [0, 1, 2, 3, 4, 5],
        [0, 1, 2, 3, 4, 5],
        [0, 1, 2, 3, 4, 5]], dtype=int64)

In [113]:
matrix.argsort(axis=0)

matrix([[0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4, 4]], dtype=int64)

In [114]:
matrix.argsort(axis=1)

matrix([[0, 1, 2, 3, 4, 5],
        [0, 1, 2, 3, 4, 5],
        [0, 1, 2, 3, 4, 5],
        [0, 1, 2, 3, 4, 5],
        [0, 1, 2, 3, 4, 5]], dtype=int64)

In [96]:
#sort([axis, kind, order])

In [89]:
matrix

matrix([[11, 28, 29, 47, 53, 46],
        [13, 35, 36, 79, 56, 68],
        [14, 35, 51, 86, 59, 69],
        [15, 49, 56, 97, 97, 75],
        [23, 51, 58, 97, 60, 98]])

In [91]:
matrix.sort();
matrix

matrix([[11, 28, 29, 46, 47, 53],
        [13, 35, 36, 56, 68, 79],
        [14, 35, 51, 59, 69, 86],
        [15, 49, 56, 75, 97, 97],
        [23, 51, 58, 60, 97, 98]])

In [92]:
matrix.sort(axis=1)

In [93]:
matrix

matrix([[11, 28, 29, 46, 47, 53],
        [13, 35, 36, 56, 68, 79],
        [14, 35, 51, 59, 69, 86],
        [15, 49, 56, 75, 97, 97],
        [23, 51, 58, 60, 97, 98]])

In [94]:
matrix.sort(axis=0)

In [95]:
matrix

matrix([[11, 28, 29, 46, 47, 53],
        [13, 35, 36, 56, 68, 79],
        [14, 35, 51, 59, 69, 86],
        [15, 49, 56, 60, 97, 97],
        [23, 51, 58, 75, 97, 98]])

In [ ]:
#astype(dtype[, order, casting, subok, copy]) 

In [97]:
matrix.dtype

dtype('int32')

In [105]:
matrix.astype(float, order='F', casting='safe')

matrix([[11., 28., 29., 46., 47., 53.],
        [13., 35., 36., 56., 68., 79.],
        [14., 35., 51., 59., 69., 86.],
        [15., 49., 56., 60., 97., 97.],
        [23., 51., 58., 75., 97., 98.]])

In [101]:
matrix.astype(float, order='F', casting='safe').dtype

dtype('float64')

In [106]:
matrix.astype(float, order='F', casting='safe').flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [109]:
matrix.astype(np.int64, order='C', casting='unsafe')

matrix([[11, 28, 29, 46, 47, 53],
        [13, 35, 36, 56, 68, 79],
        [14, 35, 51, 59, 69, 86],
        [15, 49, 56, 60, 97, 97],
        [23, 51, 58, 75, 97, 98]], dtype=int64)

In [116]:
#diagonal([offset, axis1, axis2])
print(matrix);
matrix.diagonal()

[[11 28 29 46 47 53]
 [13 35 36 56 68 79]
 [14 35 51 59 69 86]
 [15 49 56 60 97 97]
 [23 51 58 75 97 98]]


matrix([[11, 35, 51, 60, 97]])

In [117]:
matrix.diagonal(0)

matrix([[11, 35, 51, 60, 97]])

In [118]:
matrix.diagonal(1)

matrix([[28, 36, 59, 97, 98]])

In [119]:
matrix.diagonal(-1)

matrix([[13, 35, 56, 75]])

In [120]:
matrix.diagonal(1,0)

matrix([[28, 36, 59, 97, 98]])

In [122]:
matrix.diagonal(1,1,0)

matrix([[13, 35, 56, 75]])

In [126]:
# choose(choices[, out, mode])
index_mat = np.matrix('[2,3,0,1]');
choices = np.matrix([[34,52,123,54],[532,3,52,12],[52,12,52,52],[52,23,63,23]])
print(choices);

index_mat.choose(choices)

[[ 34  52 123  54]
 [532   3  52  12]
 [ 52  12  52  52]
 [ 52  23  63  23]]


matrix([[ 52,  23, 123,  12]])

In [132]:
# clip([min, max, out])
matrix = np.matrix('[12 24 62; 50 42 56]');
print(matrix);

[[12 24 62]
 [50 42 56]]


In [133]:
matrix.clip(20,50)

matrix([[20, 24, 50],
        [50, 42, 50]])

In [137]:
matrix = np.matrix(np.round(np.random.randn(4,5),2));
matrix

matrix([[ 0.2 , -1.09, -1.59, -0.58, -0.53],
        [ 1.37,  0.77,  0.26,  0.37, -1.69],
        [-1.83, -0.25, -1.22,  0.69,  0.62],
        [-0.61, -1.84, -0.68, -0.21, -0.16]])

In [138]:
type(matrix)

numpy.matrix

In [139]:
matrix.clip(0,1)

matrix([[0.2 , 0.  , 0.  , 0.  , 0.  ],
        [1.  , 0.77, 0.26, 0.37, 0.  ],
        [0.  , 0.  , 0.  , 0.69, 0.62],
        [0.  , 0.  , 0.  , 0.  , 0.  ]])

In [144]:
# compress(condition[, axis, out])

print(matrix);

condition = (matrix<0).A1

matrix.compress(condition)

[[ 0.2  -1.09 -1.59 -0.58 -0.53]
 [ 1.37  0.77  0.26  0.37 -1.69]
 [-1.83 -0.25 -1.22  0.69  0.62]
 [-0.61 -1.84 -0.68 -0.21 -0.16]]


matrix([[-1.09, -1.59, -0.58, -0.53, -1.69, -1.83, -0.25, -1.22, -0.61,
         -1.84, -0.68, -0.21, -0.16]])

In [150]:
# conj();
# conjugate();

In [155]:
matrix = np.matrix(np.ones((3,3))) - 1j * np.round(np.random.ranf(size=(3,3)),2);

In [156]:
matrix

matrix([[1.-1.j  , 1.-0.37j, 1.-0.59j],
        [1.-0.39j, 1.-0.37j, 1.-0.45j],
        [1.-0.14j, 1.-0.4j , 1.-0.38j]])

In [157]:
matrix.conj()

matrix([[1.+1.j  , 1.+0.37j, 1.+0.59j],
        [1.+0.39j, 1.+0.37j, 1.+0.45j],
        [1.+0.14j, 1.+0.4j , 1.+0.38j]])

In [158]:
matrix

matrix([[1.-1.j  , 1.-0.37j, 1.-0.59j],
        [1.-0.39j, 1.-0.37j, 1.-0.45j],
        [1.-0.14j, 1.-0.4j , 1.-0.38j]])

In [159]:
matrix.conjugate()

matrix([[1.+1.j  , 1.+0.37j, 1.+0.59j],
        [1.+0.39j, 1.+0.37j, 1.+0.45j],
        [1.+0.14j, 1.+0.4j , 1.+0.38j]])

In [1]:
import numpy as np;

### matrix.byteswap(inplace=False)
- Swap the bytes of the array elements

In [7]:
var = np.array(34, dtype=np.int32);
var

array(34)

In [8]:
var.byteswap(inplace=True);

In [9]:
var

array(570425344)

In [10]:
var.dtype.byteorder

'='

In [11]:
var.byteswap(inplace=True);

In [12]:
var

array(34)

In [14]:
np.binary_repr(34)

'100010'

In [18]:
np.binary_repr(570425344)

'100010000000000000000000000000'

In [19]:
len(bin(570425344))

32

In [39]:
matrix = np.matrix('[1,2,3; 4,5,6; 7,8,9]', dtype=np.uint16);
print(matrix);
print(matrix.dtype);
print(matrix.dtype.byteorder);

[[1 2 3]
 [4 5 6]
 [7 8 9]]
uint16
=


In [40]:
import sys

In [41]:
sys.byteorder

'little'

In [42]:
matrix

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=uint16)

In [43]:
matrix.byteswap()

matrix([[ 256,  512,  768],
        [1024, 1280, 1536],
        [1792, 2048, 2304]], dtype=uint16)

In [62]:
bin(matrix[0,0])     # actually 1 is stored in little endian order (0000000000000001). if we change the byte order it will bcm.
                                                            # (100000000000000)

'0b1'

In [63]:
bin(matrix.byteswap()[0,0])

'0b100000000'

### matrix.clip(min=None, max=None, out=None, **kwargs)
- Return an array whose values are limited to [min, max]. One of max or min must be given.

In [64]:
matrix

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=uint16)

In [65]:
matrix.clip(20,30)

matrix([[20, 20, 20],
        [20, 20, 20],
        [20, 20, 20]], dtype=uint16)

In [66]:
matrix.clip(40,50)

matrix([[40, 40, 40],
        [40, 40, 40],
        [40, 40, 40]], dtype=uint16)

In [67]:
matrix.clip(2,10)

matrix([[2, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=uint16)

In [69]:
matrix.clip(2,7)                   ## any value less than min will be cliped to min and greater to max

matrix([[2, 2, 3],
        [4, 5, 6],
        [7, 7, 7]], dtype=uint16)

### ndarray.compress(condition, axis=None, out=None)
- Return selected slices of this array along given axis.

In [72]:
matrix = np.matrix(np.random.random_sample((4,4)));
matrix

matrix([[0.35547716, 0.65260285, 0.73450856, 0.66040897],
        [0.12600653, 0.23238911, 0.59654511, 0.21978676],
        [0.74480202, 0.25306059, 0.42199978, 0.22100842],
        [0.12146966, 0.42376598, 0.37077888, 0.63012535]])

In [83]:
cond = (matrix<0.5).A1
matrix.compress(cond)

matrix([[0.35547716, 0.12600653, 0.23238911, 0.21978676, 0.25306059,
         0.42199978, 0.22100842, 0.12146966, 0.42376598, 0.37077888]])

### matrix.setflags(write=None, align=None, uic=None)
- Set array flags WRITEABLE, ALIGNED, WRITEBACKIFCOPY, respectively.

In [4]:
matrix = np.matrix('[534,523,236; 643 748 395; 538 789 948]');
matrix

matrix([[534, 523, 236],
        [643, 748, 395],
        [538, 789, 948]])

In [5]:
matrix.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [8]:
matrix.setflags(align=True);
matrix

matrix([[534, 523, 236],
        [643, 748, 395],
        [538, 789, 948]])

In [9]:
matrix.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [12]:
matrix.setflags(align=False);
matrix

matrix([[534, 523, 236],
        [643, 748, 395],
        [538, 789, 948]])

In [13]:
matrix.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : False
  WRITEBACKIFCOPY : False

In [14]:
matrix.setflags(uic=True);
matrix

ValueError: cannot set WRITEBACKIFCOPY flag to True

In [15]:
matrix[0]=100;
matrix

matrix([[100, 100, 100],
        [643, 748, 395],
        [538, 789, 948]])

In [16]:
matrix.setflags(write=False);
matrix

matrix([[100, 100, 100],
        [643, 748, 395],
        [538, 789, 948]])

In [17]:
matrix[0,0]=200;
matrix

ValueError: assignment destination is read-only

In [18]:
matrix.flags.f_contiguous

False

In [19]:
matrix.setflags(align=True);

In [20]:
matrix.flags.f_contiguous

False

In [25]:
matrix.setflags(write=True)

In [57]:
matrix = np.matrix(np.arange(20).reshape(4,5))
matrix

matrix([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [58]:
matrix.dtype

dtype('int32')

In [59]:
matrix.setfield(3, dtype=np.int16, offset=0);
matrix

matrix([[3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3]])

In [78]:
matrix.dtype

dtype('int32')

In [79]:
arr = np.array([('wajahat', 20, 3.4), ('kamran', 19, 3.6)], dtype=[('name', np.str_), ('age', np.int16), ('gpa',np.half)]);
arr

array([('', 20, 3.4), ('', 19, 3.6)],
      dtype=[('name', '<U'), ('age', '<i2'), ('gpa', '<f2')])

In [80]:
arr.setfield(3 , dtype=np.float32)

In [81]:
arr

array([('', 0, 2.125), ('', 0, 2.125)],
      dtype=[('name', '<U'), ('age', '<i2'), ('gpa', '<f2')])

In [85]:
arr.dtype.fields['name'][1]

0

In [86]:
arr.dtype.fields

mappingproxy({'name': (dtype('<U'), 0),
              'age': (dtype('int16'), 0),
              'gpa': (dtype('float16'), 2)})