In [1]:
import numpy as np;

In [2]:
arr = np.array([[[342,234],[345,734]],[[643,632],[672,226]]], dtype='>i4');

for i in arr:
    for j in i: 
        for k in j:
            print(k, end=' ')

342 234 345 734 643 632 672 226 

In [3]:
arr.shape

(2, 2, 2)

In [4]:
arr.dtype

dtype('>i4')

In [5]:
arr.size

8

In [6]:
arr.itemsize

4

In [7]:
id(arr)

1495693586768

In [8]:
type(arr)

numpy.ndarray

In [9]:
arr.nbytes

32

In [10]:
arr.ndim

3

In [11]:
arr.mean()

478.5

In [12]:
arr.std()

197.9065436007612

In [13]:
arr.astype('i8')

array([[[342, 234],
        [345, 734]],

       [[643, 632],
        [672, 226]]], dtype=int64)

In [14]:
arr.dtype

dtype('>i4')

In [15]:
arr.min()

226

In [16]:
arr.max()

734

In [17]:
arr.newbyteorder('L')

array([[[ 1442906112,  -369098752],
        [ 1493237760,  -570294272]],

       [[-2097020928,  2013396992],
        [-1610481664,  -503316480]]])

In [18]:
arr.dtype

dtype('>i4')

In [19]:
arr.sum

<function ndarray.sum>

In [20]:
arr.sum()

3828

In [21]:
arr

array([[[342, 234],
        [345, 734]],

       [[643, 632],
        [672, 226]]])

In [22]:
arr.sum(axis=0)

array([[ 985,  866],
       [1017,  960]])

In [23]:
arr.sum(axis=1)

array([[ 687,  968],
       [1315,  858]])

In [24]:
arr.sum(axis=2)

array([[ 576, 1079],
       [1275,  898]])

In [25]:
arr.dtype.byteorder

'>'

In [26]:
arr

array([[[342, 234],
        [345, 734]],

       [[643, 632],
        [672, 226]]])

In [27]:
for item in np.nditer(arr):
    print(item)

342
234
345
734
643
632
672
226


In [28]:
for index, item in np.ndenumerate(arr):
    print(f"Index : {index}   Item : {item}")

Index : (0, 0, 0)   Item : 342
Index : (0, 0, 1)   Item : 234
Index : (0, 1, 0)   Item : 345
Index : (0, 1, 1)   Item : 734
Index : (1, 0, 0)   Item : 643
Index : (1, 0, 1)   Item : 632
Index : (1, 1, 0)   Item : 672
Index : (1, 1, 1)   Item : 226


In [29]:
arr.strides

(16, 8, 4)

In [30]:
arr.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [31]:
arr.flags['C_CONTIGUOUS']

True

### ndarray.resize()

In [32]:
arr

array([[[342, 234],
        [345, 734]],

       [[643, 632],
        [672, 226]]])

In [33]:
arr.base is None

True

In [80]:
arr1 = np.array([[63,62,23,56],[94,45,94,69]]);

In [81]:
id(arr1)

1495731883152

In [82]:
arr1.resize(3,3)

In [83]:
arr1

array([[63, 62, 23],
       [56, 94, 45],
       [94, 69,  0]])

In [84]:
id(arr1)

1495731883152

In [86]:
arr2 = np.array([[63,62,23,56],[94,45,94,69]], order='C')

In [87]:
arr2.resize(3,3)

In [88]:
arr2

array([[63, 62, 23],
       [56, 94, 45],
       [94, 69,  0]])

In [89]:
arr3 = np.array([[63,62,23,56],[94,45,94,69]], order='F')

In [90]:
arr3.resize(2,4)

In [91]:
arr3

array([[63, 62, 23, 56],
       [94, 45, 94, 69]])

#### refcheck parameter
- The purpose of the reference count check is to make sure you do not use this array as a buffer for another Python object and then reallocate the memory

In [96]:
a = np.random.random(size=(2,6)).round(2);
a

array([[0.7 , 0.36, 0.66, 0.81, 0.85, 0.9 ],
       [0.15, 0.97, 0.03, 0.33, 0.44, 0.26]])

In [97]:
id(a)

1495731891888

In [98]:
a.resize(3,4, refcheck=True);
a

array([[0.7 , 0.36, 0.66, 0.81],
       [0.85, 0.9 , 0.15, 0.97],
       [0.03, 0.33, 0.44, 0.26]])

In [99]:
id(a)

1495731891888

In [106]:
A = np.random.random_sample(size=(4,5));
A

array([[0.24863862, 0.84713666, 0.63545856, 0.71373183, 0.08116723],
       [0.67734254, 0.82646093, 0.10869719, 0.61571331, 0.60762562],
       [0.11059493, 0.15264845, 0.57428474, 0.67625477, 0.67595452],
       [0.33007499, 0.88921305, 0.44759721, 0.75812389, 0.70092799]])

In [107]:
id(A)

1495731890928

In [108]:
A.size

20

In [109]:
A.resize(2,10, refcheck=False);

In [110]:
A

array([[0.24863862, 0.84713666, 0.63545856, 0.71373183, 0.08116723,
        0.67734254, 0.82646093, 0.10869719, 0.61571331, 0.60762562],
       [0.11059493, 0.15264845, 0.57428474, 0.67625477, 0.67595452,
        0.33007499, 0.88921305, 0.44759721, 0.75812389, 0.70092799]])

In [111]:
id(A)

1495731890928

### ndarray.transpose(axis)

In [114]:
np.zeros((3,5), dtype=np.int32).transpose()

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [115]:
a = np.zeros((3,5), dtype=np.float16, order='C');

In [116]:
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float16)

In [117]:
a.transpose(1,0)      # It means the 0th axis of a become the 1th axis of a.transpose() and vice versa.

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float16)

In [118]:
a.transpose(0,1)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float16)

In [119]:
a.T   # It is an attribute used for transpose

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float16)

In [120]:
np.random.sample(size=(2,3)).transpose()

array([[0.38478962, 0.53722615],
       [0.484337  , 0.95196758],
       [0.72888508, 0.81298097]])

### ndarray.swapaxes(axis1, axis2)
- Return a view of the array with axis1 and axis2 interchanged

In [121]:
a = np.linspace(1,5,20).reshape(4,5)

In [122]:
a

array([[1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526],
       [2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684],
       [3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842],
       [4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ]])

In [123]:
a.swapaxes(0,1)

array([[1.        , 2.05263158, 3.10526316, 4.15789474],
       [1.21052632, 2.26315789, 3.31578947, 4.36842105],
       [1.42105263, 2.47368421, 3.52631579, 4.57894737],
       [1.63157895, 2.68421053, 3.73684211, 4.78947368],
       [1.84210526, 2.89473684, 3.94736842, 5.        ]])

In [124]:
a

array([[1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526],
       [2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684],
       [3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842],
       [4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ]])

In [127]:
np.random.randn(3,2).swapaxes(1,0)

array([[ 0.70184916,  1.12990355,  0.12387377],
       [ 1.04709128, -0.5049776 ,  1.30291974]])

### ndarray.flatten(order=’C’)


In [128]:
a = np.arange(20,30,0.5).reshape(2,10);

In [129]:
a

array([[20. , 20.5, 21. , 21.5, 22. , 22.5, 23. , 23.5, 24. , 24.5],
       [25. , 25.5, 26. , 26.5, 27. , 27.5, 28. , 28.5, 29. , 29.5]])

In [130]:
a.flatten()

array([20. , 20.5, 21. , 21.5, 22. , 22.5, 23. , 23.5, 24. , 24.5, 25. ,
       25.5, 26. , 26.5, 27. , 27.5, 28. , 28.5, 29. , 29.5])

In [131]:
a.flatten(order='C')

array([20. , 20.5, 21. , 21.5, 22. , 22.5, 23. , 23.5, 24. , 24.5, 25. ,
       25.5, 26. , 26.5, 27. , 27.5, 28. , 28.5, 29. , 29.5])

In [132]:
a.flatten(order='F')

array([20. , 25. , 20.5, 25.5, 21. , 26. , 21.5, 26.5, 22. , 27. , 22.5,
       27.5, 23. , 28. , 23.5, 28.5, 24. , 29. , 24.5, 29.5])

In [133]:
np.round(np.random.rand(3,3), 2).flatten()

array([0.94, 0.01, 0.74, 0.22, 0.33, 0.5 , 0.35, 0.96, 0.43])

### ndarray.ravel([order])


In [134]:
a

array([[20. , 20.5, 21. , 21.5, 22. , 22.5, 23. , 23.5, 24. , 24.5],
       [25. , 25.5, 26. , 26.5, 27. , 27.5, 28. , 28.5, 29. , 29.5]])

In [135]:
a.ravel()

array([20. , 20.5, 21. , 21.5, 22. , 22.5, 23. , 23.5, 24. , 24.5, 25. ,
       25.5, 26. , 26.5, 27. , 27.5, 28. , 28.5, 29. , 29.5])

In [136]:
a.ravel(order='C')

array([20. , 20.5, 21. , 21.5, 22. , 22.5, 23. , 23.5, 24. , 24.5, 25. ,
       25.5, 26. , 26.5, 27. , 27.5, 28. , 28.5, 29. , 29.5])

In [137]:
a.ravel(order='F')

array([20. , 25. , 20.5, 25.5, 21. , 26. , 21.5, 26.5, 22. , 27. , 22.5,
       27.5, 23. , 28. , 23.5, 28.5, 24. , 29. , 24.5, 29.5])

In [138]:
a.ravel(order='K')

array([20. , 20.5, 21. , 21.5, 22. , 22.5, 23. , 23.5, 24. , 24.5, 25. ,
       25.5, 26. , 26.5, 27. , 27.5, 28. , 28.5, 29. , 29.5])

In [143]:
np.random.randint(low=0, high=300, size=(3,4)).ravel()

array([194, 124, 132,  54, 165, 282, 251, 285,  51, 288,  11,  63])

In [144]:
ord('a')

97

In [145]:
bin(23)

'0b10111'

### ndarray.take(indices, axis=None, out=None, mode=’raise’)

In [146]:
import numpy as np;

In [147]:
arr = np. arange(2,10,1);

In [148]:
arr

array([2, 3, 4, 5, 6, 7, 8, 9])

In [149]:
arr.take([0,1,2])

array([2, 3, 4])

In [150]:
arr.take([5,6,7])

array([7, 8, 9])

In [151]:
arr = np.arange(2,20,1).reshape(3,6);

In [152]:
arr

array([[ 2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19]])

In [153]:
arr.take([0,1,2], axis=0)

array([[ 2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19]])

In [154]:
arr.take([0,1], axis=0)

array([[ 2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13]])

In [155]:
arr.take([0,3,5], axis=1)

array([[ 2,  5,  7],
       [ 8, 11, 13],
       [14, 17, 19]])

In [156]:
arr

array([[ 2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19]])

In [157]:
arr.take([2,2,2], axis=1)

array([[ 4,  4,  4],
       [10, 10, 10],
       [16, 16, 16]])

In [158]:
arr.take([2], axis=1)

array([[ 4],
       [10],
       [16]])

In [159]:
arr.take([2,8,14])

array([ 4, 10, 16])

In [169]:
a= np.random.random_sample(size=(3,3))
a

array([[0.85811787, 0.86531886, 0.53059607],
       [0.50963834, 0.29770367, 0.8388744 ],
       [0.37997761, 0.89562781, 0.47847856]])

In [170]:
a.take([0,2], axis=1)

array([[0.85811787, 0.53059607],
       [0.50963834, 0.8388744 ],
       [0.37997761, 0.47847856]])

### ndarray.put(indices, values, mode=’raise’)


In [171]:
arr

array([[ 2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19]])

In [172]:
arr.put([0,1,2], [34,6,23])

In [173]:
arr

array([[34,  6, 23,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19]])

In [174]:
arr.put([6,7,8],[34,63,23])

In [175]:
arr

array([[34,  6, 23,  5,  6,  7],
       [34, 63, 23, 11, 12, 13],
       [14, 15, 16, 17, 18, 19]])

In [176]:
arr.put([18,19],[0,0], mode='wrap')

In [177]:
arr

array([[ 0,  0, 23,  5,  6,  7],
       [34, 63, 23, 11, 12, 13],
       [14, 15, 16, 17, 18, 19]])

In [178]:
arr.put([16,17,18,19],[9,9,9,9], mode='clip')

In [179]:
arr

array([[ 0,  0, 23,  5,  6,  7],
       [34, 63, 23, 11, 12, 13],
       [14, 15, 16, 17,  9,  9]])

In [180]:
arr.put([18,19],[34,23], mode='clip')

In [181]:
arr

array([[ 0,  0, 23,  5,  6,  7],
       [34, 63, 23, 11, 12, 13],
       [14, 15, 16, 17,  9, 23]])

In [182]:
arr.put([-1,-2],[43,23])

In [183]:
arr

array([[ 0,  0, 23,  5,  6,  7],
       [34, 63, 23, 11, 12, 13],
       [14, 15, 16, 17, 23, 43]])

In [184]:
arr.put([-5,-4,-3,-2,-1],[100,100,100,100,100]);

In [185]:
arr

array([[  0,   0,  23,   5,   6,   7],
       [ 34,  63,  23,  11,  12,  13],
       [ 14, 100, 100, 100, 100, 100]])

In [186]:
a = np.random.randint(3,300, (3,4));
a

array([[229,  67, 173, 263],
       [191,  21, 145, 230],
       [107, 220,  72, 211]])

In [189]:
a.put([(1,1)], [300]);
a

array([[229, 300,  33, 263],
       [191,  21, 145, 230],
       [107, 220,  72, 211]])

### ndarray.repeat(repeats, axis=None)
- Repeat each element of an array after themselves

In [190]:
arr = np.array([3,4]);

In [191]:
np.repeat(3,4)

array([3, 3, 3, 3])

In [192]:
np.repeat(5,2)

array([5, 5])

In [193]:
np.repeat(arr, 1)

array([3, 4])

In [194]:
np.repeat(arr, 2)

array([3, 3, 4, 4])

In [195]:
np.repeat(arr, 5)

array([3, 3, 3, 3, 3, 4, 4, 4, 4, 4])

In [198]:
arr = np.array([[4,6],[7,9]])
print(arr)

[[4 6]
 [7 9]]


In [199]:
np.repeat(arr, 2, axis=1)

array([[4, 4, 6, 6],
       [7, 7, 9, 9]])

In [200]:
arr = np.array([[3,4,5],[7,8,9]])

In [201]:
arr

array([[3, 4, 5],
       [7, 8, 9]])

In [202]:
arr.repeat(3, axis=1)

array([[3, 3, 3, 4, 4, 4, 5, 5, 5],
       [7, 7, 7, 8, 8, 8, 9, 9, 9]])

In [203]:
arr.repeat(3, axis=0)

array([[3, 4, 5],
       [3, 4, 5],
       [3, 4, 5],
       [7, 8, 9],
       [7, 8, 9],
       [7, 8, 9]])

### ndarray.sort(axis=-1, kind=’quicksort’, order=None)


In [204]:
arr

array([[3, 4, 5],
       [7, 8, 9]])

In [205]:
arr.sort(axis=0, kind='quicksort')

In [206]:
arr

array([[3, 4, 5],
       [7, 8, 9]])

In [207]:
arr.sort(axis=1, kind='mergesort')

In [208]:
arr

array([[3, 4, 5],
       [7, 8, 9]])

In [209]:
arr = np.arange(24,0,-1).reshape(2,12);

In [210]:
arr

array([[24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13],
       [12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1]])

In [211]:
arr.sort(axis=0, kind='quicksort')

In [212]:
arr

array([[12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1],
       [24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13]])

In [213]:
arr.sort(axis=1, kind='heapsort')

In [214]:
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [215]:
a = np.random.randint(0,1000, size=(4,4));
a

array([[659, 190, 943, 747],
       [665, 290, 619, 374],
       [854, 349, 360, 205],
       [825,  37, 116, 243]])

In [217]:
a.sort()
a

array([[190, 659, 747, 943],
       [290, 374, 619, 665],
       [205, 349, 360, 854],
       [ 37, 116, 243, 825]])

In [218]:
a.sort(axis=0, kind='headsort');
a

array([[ 37, 116, 243, 665],
       [190, 349, 360, 825],
       [205, 374, 619, 854],
       [290, 659, 747, 943]])

In [219]:
a.sort(axis=1, kind='quicksort');
a

array([[ 37, 116, 243, 665],
       [190, 349, 360, 825],
       [205, 374, 619, 854],
       [290, 659, 747, 943]])

### ndarray.argsort(axis=-1, kind=’quicksort’, order=None)


In [220]:
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [221]:
arr.argsort()

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]], dtype=int64)

### ndarray.argmax(axis=None, out=None)
- Return indices of the maximum values along the given axis.

In [222]:
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [223]:
arr.argmax()

23

In [224]:
arr.argmax(axis=0)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [225]:
arr.argmax(axis=1)

array([11, 11], dtype=int64)

In [228]:
np.random.randint(4,100,size=(4,4)).argmax()

15

In [229]:
np.random.randint(4, 100, size=(3,4)).argmax(axis=0)

array([0, 2, 2, 2], dtype=int64)

### ndarray.min(axis=None, out=None, keepdims=False)
- Return the minimum along a given axis.

In [230]:
arr = np.random.randint(low=0 ,high=100, size=(4,5));

In [231]:
arr.min()

2

In [232]:
arr.min(axis=0)

array([ 9,  2, 21,  3, 61])

In [233]:
arr.min(axis=1)

array([ 9,  2, 37,  3])

### ndarray.argmin(axis=None, out=None)
- Return indices of the minimum values along the given axis of a.


In [234]:
arr

array([[ 9, 26, 95, 49, 61],
       [76,  2, 21, 47, 92],
       [37, 46, 53, 47, 94],
       [84, 19, 35,  3, 70]])

In [235]:
arr.argmin()

6

In [236]:
arr.argmin(axis=0)

array([0, 1, 1, 3, 0], dtype=int64)

In [237]:
arr.argmin(axis=1)

array([0, 1, 0, 3], dtype=int64)

### ndarray.ptp(axis=None, out=None)
- Peak to peak (maximum - minimum) value along a given axis

In [238]:
arr

array([[ 9, 26, 95, 49, 61],
       [76,  2, 21, 47, 92],
       [37, 46, 53, 47, 94],
       [84, 19, 35,  3, 70]])

In [239]:
arr.ptp()

93

In [240]:
arr.ptp(axis=0)

array([75, 44, 74, 46, 33])

In [241]:
arr.ptp(axis=1)

array([86, 90, 57, 81])

In [242]:
arr

array([[ 9, 26, 95, 49, 61],
       [76,  2, 21, 47, 92],
       [37, 46, 53, 47, 94],
       [84, 19, 35,  3, 70]])

In [243]:
arr.ptp()

93

In [244]:
arr.max()-arr.min()

93

In [245]:
arr.ptp(axis=1)

array([86, 90, 57, 81])

### ndarray.clip(min=None, max=None, out=None)
- Return an array whose values are limited to [min, max]. One of max or min must be given.

In [246]:
arr.clip(min=2)

array([[ 9, 26, 95, 49, 61],
       [76,  2, 21, 47, 92],
       [37, 46, 53, 47, 94],
       [84, 19, 35,  3, 70]])

In [248]:
arr.clip(min=1, max=30)

array([[ 9, 26, 30, 30, 30],
       [30,  2, 21, 30, 30],
       [30, 30, 30, 30, 30],
       [30, 19, 30,  3, 30]])

In [250]:
arr.clip(min=100, max=200)

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

### ndarray.conj()
- Complex-conjugate all elements

In [251]:
arr

array([[ 9, 26, 95, 49, 61],
       [76,  2, 21, 47, 92],
       [37, 46, 53, 47, 94],
       [84, 19, 35,  3, 70]])

In [252]:
arr.conj()

array([[ 9, 26, 95, 49, 61],
       [76,  2, 21, 47, 92],
       [37, 46, 53, 47, 94],
       [84, 19, 35,  3, 70]])

In [253]:
np.conjugate(arr)

array([[ 9, 26, 95, 49, 61],
       [76,  2, 21, 47, 92],
       [37, 46, 53, 47, 94],
       [84, 19, 35,  3, 70]])

In [254]:
np.conjugate([[4,3],[5,6]])

array([[4, 3],
       [5, 6]])

### ndarray.any(axis=None, out=None, keepdims=False)
- Returns True if any of the elements of a evaluate to True.

In [255]:
arr

array([[ 9, 26, 95, 49, 61],
       [76,  2, 21, 47, 92],
       [37, 46, 53, 47, 94],
       [84, 19, 35,  3, 70]])

In [256]:
arr.any()

True

In [257]:
arr.any(axis=0)

array([ True,  True,  True,  True,  True])

In [258]:
arr.any(axis=1)

array([ True,  True,  True,  True])

In [259]:
arr.put([2,3,4],[-43, -64, -86])

In [260]:
arr

array([[  9,  26, -43, -64, -86],
       [ 76,   2,  21,  47,  92],
       [ 37,  46,  53,  47,  94],
       [ 84,  19,  35,   3,  70]])

In [261]:
arr.put([0,1],[-48,-84])

In [262]:
arr

array([[-48, -84, -43, -64, -86],
       [ 76,   2,  21,  47,  92],
       [ 37,  46,  53,  47,  94],
       [ 84,  19,  35,   3,  70]])

In [263]:
arr.any(axis=1)

array([ True,  True,  True,  True])

In [264]:
arr.put([0,1,2,3,4],[0])

In [265]:
arr

array([[ 0,  0,  0,  0,  0],
       [76,  2, 21, 47, 92],
       [37, 46, 53, 47, 94],
       [84, 19, 35,  3, 70]])

In [266]:
arr.any(axis=1)

array([False,  True,  True,  True])

### ndarray.all(axis=None, out=None, keepdims=False)
- Returns True if all elements evaluate to True.


In [267]:
arr

array([[ 0,  0,  0,  0,  0],
       [76,  2, 21, 47, 92],
       [37, 46, 53, 47, 94],
       [84, 19, 35,  3, 70]])

In [268]:
arr.all()

False

In [269]:
arr.all(axis=0)

array([False, False, False, False, False])

In [270]:
arr.all(axis=1)

array([False,  True,  True,  True])

### ndarray.cumprod(axis=None, dtype=None, out=None)
- Return the cumulative product of the elements along the given axis.


In [271]:
arr

array([[ 0,  0,  0,  0,  0],
       [76,  2, 21, 47, 92],
       [37, 46, 53, 47, 94],
       [84, 19, 35,  3, 70]])

In [272]:
arr.cumprod()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [273]:
arr =np.arange(1,9).reshape(2,4)

In [274]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [275]:
arr.cumprod()

array([    1,     2,     6,    24,   120,   720,  5040, 40320])

In [276]:
arr.cumprod(axis=0)

array([[ 1,  2,  3,  4],
       [ 5, 12, 21, 32]])

In [277]:
arr.cumprod(axis=1)

array([[   1,    2,    6,   24],
       [   5,   30,  210, 1680]])

### ndarray.prod(axis=None, dtype=None, out=None, keepdims=False)
- Return the product of the array elements over the given axis

In [278]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [279]:
arr.prod()

40320

In [280]:
arr.prod(axis=0)

array([ 5, 12, 21, 32])

In [281]:
arr.prod(axis=1)

array([  24, 1680])

### ndarray.std(axis=None, dtype=None, out=None, ddof=0, keepdims=False)
- Returns the standard deviation of the array elements along given axis.


In [282]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [283]:
arr.std()

2.29128784747792

In [284]:
arr.std(axis=0)

array([2., 2., 2., 2.])

In [285]:
arr.std(axis=1 )

array([1.11803399, 1.11803399])

### ndarray.var(axis=None, dtype=None, out=None, ddof=0, keepdims=False)
- Returns the variance of the array elements, along given axis.


In [286]:
arr.var()

5.25

In [287]:
arr.var(axis=0)

array([4., 4., 4., 4.])

In [288]:
arr.var(axis=1)

array([1.25, 1.25])

### ndarray.mean(axis=None, dtype=None, out=None, keepdims=False)
- Returns the average of the array elements along given axis

In [289]:
arr.mean()

4.5

In [290]:
arr.mean(axis=0)

array([3., 4., 5., 6.])

In [291]:
arr.mean(axis=1)

array([2.5, 6.5])

### ndarray.cumsum(axis=None, dtype=None, out=None)
- Return the cumulative sum of the elements along the given axis

In [292]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [293]:
arr.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36])

In [294]:
arr.cumsum(axis=0)

array([[ 1,  2,  3,  4],
       [ 6,  8, 10, 12]])

In [295]:
arr.cumsum(axis=1)

array([[ 1,  3,  6, 10],
       [ 5, 11, 18, 26]])

### ndarray.sum(axis=None, dtype=None, out=None, keepdims=False)
- Return the sum of the array elements over the given axis.

In [296]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [297]:
arr.sum()

36

In [298]:
arr.sum(axis=1)

array([10, 26])

In [299]:
arr.sum(axis=0)

array([ 6,  8, 10, 12])

### ndarray.round(decimals=0, out=None)
- Return a with each element rounded to the given number of decimals.

In [300]:
arr = np.linspace(1, 10, 20).reshape(5,4);

In [301]:
arr

array([[ 1.        ,  1.47368421,  1.94736842,  2.42105263],
       [ 2.89473684,  3.36842105,  3.84210526,  4.31578947],
       [ 4.78947368,  5.26315789,  5.73684211,  6.21052632],
       [ 6.68421053,  7.15789474,  7.63157895,  8.10526316],
       [ 8.57894737,  9.05263158,  9.52631579, 10.        ]])

In [302]:
arr.round(2)

array([[ 1.  ,  1.47,  1.95,  2.42],
       [ 2.89,  3.37,  3.84,  4.32],
       [ 4.79,  5.26,  5.74,  6.21],
       [ 6.68,  7.16,  7.63,  8.11],
       [ 8.58,  9.05,  9.53, 10.  ]])