In [1]:
import numpy as np;

In [2]:
arr = np.ones((3,5), dtype='h', order='C');

for item in np.nditer(arr):
    print(item, end=' ')

1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 

In [3]:
arr = np.arange(2,5,0.1, dtype='e').reshape(5,6);

In [4]:
arr

array([[2.   , 2.1  , 2.2  , 2.299, 2.398, 2.498],
       [2.598, 2.697, 2.797, 2.896, 2.996, 3.096],
       [3.195, 3.295, 3.395, 3.494, 3.594, 3.693],
       [3.793, 3.893, 3.992, 4.094, 4.19 , 4.29 ],
       [4.39 , 4.492, 4.59 , 4.688, 4.79 , 4.89 ]], dtype=float16)

In [5]:
for item in np.nditer(arr):
    print(item, end=' ')

2.0 2.1 2.2 2.299 2.398 2.498 2.598 2.697 2.797 2.896 2.996 3.096 3.195 3.295 3.395 3.494 3.594 3.693 3.793 3.893 3.992 4.094 4.19 4.29 4.39 4.492 4.59 4.688 4.79 4.89 

In [6]:
arr = arr.copy(order='F')

In [7]:
arr

array([[2.   , 2.1  , 2.2  , 2.299, 2.398, 2.498],
       [2.598, 2.697, 2.797, 2.896, 2.996, 3.096],
       [3.195, 3.295, 3.395, 3.494, 3.594, 3.693],
       [3.793, 3.893, 3.992, 4.094, 4.19 , 4.29 ],
       [4.39 , 4.492, 4.59 , 4.688, 4.79 , 4.89 ]], dtype=float16)

In [8]:
for item in np.nditer(arr):
    print(item, end=' ')

2.0 2.598 3.195 3.793 4.39 2.1 2.697 3.295 3.893 4.492 2.2 2.797 3.395 3.992 4.59 2.299 2.896 3.494 4.094 4.688 2.398 2.996 3.594 4.19 4.79 2.498 3.096 3.693 4.29 4.89 

In [9]:
arr

array([[2.   , 2.1  , 2.2  , 2.299, 2.398, 2.498],
       [2.598, 2.697, 2.797, 2.896, 2.996, 3.096],
       [3.195, 3.295, 3.395, 3.494, 3.594, 3.693],
       [3.793, 3.893, 3.992, 4.094, 4.19 , 4.29 ],
       [4.39 , 4.492, 4.59 , 4.688, 4.79 , 4.89 ]], dtype=float16)

In [10]:
for item in np.nditer(arr, order='K'):    # Because the array is stored in F order
    print(item, end=' ')

2.0 2.598 3.195 3.793 4.39 2.1 2.697 3.295 3.893 4.492 2.2 2.797 3.395 3.992 4.59 2.299 2.896 3.494 4.094 4.688 2.398 2.996 3.594 4.19 4.79 2.498 3.096 3.693 4.29 4.89 

In [11]:
for item in np.nditer(arr, order='C'):
    print(item, end=' ')

2.0 2.1 2.2 2.299 2.398 2.498 2.598 2.697 2.797 2.896 2.996 3.096 3.195 3.295 3.395 3.494 3.594 3.693 3.793 3.893 3.992 4.094 4.19 4.29 4.39 4.492 4.59 4.688 4.79 4.89 

In [12]:
# op_flags
# Modifying the element of array

for item in np.nditer(arr):
    item[...]=item+1;

ValueError: assignment destination is read-only

In [13]:
for item in np.nditer(arr, op_flags=['readwrite']):
    item[...]=item+1;

In [14]:
arr

array([[3.   , 3.1  , 3.2  , 3.299, 3.398, 3.498],
       [3.598, 3.697, 3.797, 3.896, 3.996, 4.094],
       [4.195, 4.297, 4.395, 4.492, 4.594, 4.695],
       [4.793, 4.89 , 4.992, 5.094, 5.19 , 5.29 ],
       [5.39 , 5.492, 5.59 , 5.688, 5.79 , 5.89 ]], dtype=float16)

In [15]:
# Using an External Loop

arr

array([[3.   , 3.1  , 3.2  , 3.299, 3.398, 3.498],
       [3.598, 3.697, 3.797, 3.896, 3.996, 4.094],
       [4.195, 4.297, 4.395, 4.492, 4.594, 4.695],
       [4.793, 4.89 , 4.992, 5.094, 5.19 , 5.29 ],
       [5.39 , 5.492, 5.59 , 5.688, 5.79 , 5.89 ]], dtype=float16)

In [16]:
for item in np.nditer(arr, flags=['external_loop']):
    print(item, end=' ')

[3.    3.598 4.195 4.793 5.39  3.1   3.697 4.297 4.89  5.492 3.2   3.797
 4.395 4.992 5.59  3.299 3.896 4.492 5.094 5.688 3.398 3.996 4.594 5.19
 5.79  3.498 4.094 4.695 5.29  5.89 ] 

In [17]:
for item in np.nditer(arr, flags=['external_loop'], order='F'):
    print(item, end=' ')

[3.    3.598 4.195 4.793 5.39  3.1   3.697 4.297 4.89  5.492 3.2   3.797
 4.395 4.992 5.59  3.299 3.896 4.492 5.094 5.688 3.398 3.996 4.594 5.19
 5.79  3.498 4.094 4.695 5.29  5.89 ] 

In [18]:
for item in np.nditer(arr, flags=['external_loop'], order='C'):
    print(item, end=' ')

[3.    3.1   3.2   3.299 3.398 3.498] [3.598 3.697 3.797 3.896 3.996 4.094] [4.195 4.297 4.395 4.492 4.594 4.695] [4.793 4.89  4.992 5.094 5.19  5.29 ] [5.39  5.492 5.59  5.688 5.79  5.89 ] 

In [19]:
arr

array([[3.   , 3.1  , 3.2  , 3.299, 3.398, 3.498],
       [3.598, 3.697, 3.797, 3.896, 3.996, 4.094],
       [4.195, 4.297, 4.395, 4.492, 4.594, 4.695],
       [4.793, 4.89 , 4.992, 5.094, 5.19 , 5.29 ],
       [5.39 , 5.492, 5.59 , 5.688, 5.79 , 5.89 ]], dtype=float16)

In [20]:
# Tracking an Index or Multi-Index

it = np.nditer(arr, flags=['f_index']);

for item in it:
    print('Index %d    value %d'%(it.index, item));

Index 0    value 3
Index 1    value 3
Index 2    value 4
Index 3    value 4
Index 4    value 5
Index 5    value 3
Index 6    value 3
Index 7    value 4
Index 8    value 4
Index 9    value 5
Index 10    value 3
Index 11    value 3
Index 12    value 4
Index 13    value 4
Index 14    value 5
Index 15    value 3
Index 16    value 3
Index 17    value 4
Index 18    value 5
Index 19    value 5
Index 20    value 3
Index 21    value 3
Index 22    value 4
Index 23    value 5
Index 24    value 5
Index 25    value 3
Index 26    value 4
Index 27    value 4
Index 28    value 5
Index 29    value 5


In [21]:
it = np.nditer(arr, flags=['multi_index']);
while not it.finished:
    print('index %s    value %d'%(it.multi_index,  it[0]));
    it.iternext()

index (0, 0)    value 3
index (1, 0)    value 3
index (2, 0)    value 4
index (3, 0)    value 4
index (4, 0)    value 5
index (0, 1)    value 3
index (1, 1)    value 3
index (2, 1)    value 4
index (3, 1)    value 4
index (4, 1)    value 5
index (0, 2)    value 3
index (1, 2)    value 3
index (2, 2)    value 4
index (3, 2)    value 4
index (4, 2)    value 5
index (0, 3)    value 3
index (1, 3)    value 3
index (2, 3)    value 4
index (3, 3)    value 5
index (4, 3)    value 5
index (0, 4)    value 3
index (1, 4)    value 3
index (2, 4)    value 4
index (3, 4)    value 5
index (4, 4)    value 5
index (0, 5)    value 3
index (1, 5)    value 4
index (2, 5)    value 4
index (3, 5)    value 5
index (4, 5)    value 5


In [39]:
arr1 = np.arange(3,9,1).reshape(2,3);

In [40]:
arr1

array([[3, 4, 5],
       [6, 7, 8]])

In [41]:
iterator = np.nditer(arr1, flags=['multi_index'], op_flags=['readwrite']);

while not iterator.finished:
    print(iterator.multi_index[0]);
    iterator.iternext();

0
0
0
1
1
1


In [43]:
iterator = np.nditer(arr1, flags=['multi_index'], op_flags=['readwrite']);

while not iterator.finished:
    print('Index {}   Value {}'.format(iterator.multi_index, iterator[0]))
    iterator.iternext();

Index (0, 0)   Value 3
Index (0, 1)   Value 4
Index (0, 2)   Value 5
Index (1, 0)   Value 6
Index (1, 1)   Value 7
Index (1, 2)   Value 8


In [44]:
arr1

array([[3, 4, 5],
       [6, 7, 8]])

In [45]:
iterator = np.nditer(arr1, flags=['multi_index'], op_flags=['readwrite']);

while not iterator.finished:
    iterator[0]=iterator.multi_index[1]-iterator.multi_index[0]
    iterator.iternext();

In [46]:
arr1

array([[ 0,  1,  2],
       [-1,  0,  1]])