In [1]:
import numpy as np

In [2]:
arr=np.array([4,6,2,62,5]);

In [3]:
print(arr);

[ 4  6  2 62  5]


In [4]:
for i in arr:
    print(i);

4
6
2
62
5


In [5]:
arr.shape

(5,)

In [6]:
arr.size

5

In [7]:
print(arr.max)

<built-in method max of numpy.ndarray object at 0x000001A6B690C030>


In [8]:
print(arr.max());

62


In [9]:
print(arr.min());

2


In [10]:
print(arr.argmax());

3


In [11]:
print(arr);

[ 4  6  2 62  5]


In [14]:
print(arr.dtype)

int32


### N Dimensional Array

In [16]:
ndArray=np.array([[53,63,73,73],[34,63,83,83]],np.int32);

In [17]:
print(ndArray)

[[53 63 73 73]
 [34 63 83 83]]


In [19]:
print(ndArray[0][0]);

53


In [20]:
print(ndArray[1][3]);

83


In [23]:
print(type(ndArray));

<class 'numpy.ndarray'>


In [26]:
print(ndArray.dtype);

int32


In [27]:
print(ndArray.shape)

(2, 4)


In [28]:
print(ndArray.size);

8


In [34]:
for i in range(2):
    for j in range(4):
        print(ndArray[i][j],end=' ');
        j+=1;
    print();
    i+=1;

53 63 73 73 
34 63 83 83 


In [31]:
i=0;
j=0;
print(ndArray[i][j]);

53


In [35]:
ndSlice=ndArray[:1];

In [36]:
print(ndSlice);

[[53 63 73 73]]


In [38]:
print(ndSlice.shape);

(1, 4)


In [39]:
ndSlice[0][0]=10;

In [40]:
print(ndSlice[0][0]);

10


In [41]:
print(ndArray[0][0]);

10
