### Basic Operation on Numpy Array

In [1]:
import numpy as np;

In [2]:
arr1=np.array([4,5,2,6,4,7,3]);

In [3]:
arr2=np.array([6,9,3,5,8,3,7]);

In [4]:
arr1-arr2

array([-2, -4, -1,  1, -4,  4, -4])

In [5]:
arr1+arr2

array([10, 14,  5, 11, 12, 10, 10])

In [6]:
arr1*arr2

array([24, 45,  6, 30, 32, 21, 21])

In [7]:
arr3=np.array([5,3,7,3]);

In [8]:
arr1*arr3

ValueError: operands could not be broadcast together with shapes (7,) (4,) 

In [9]:
arr1

array([4, 5, 2, 6, 4, 7, 3])

In [10]:
3*arr1

array([12, 15,  6, 18, 12, 21,  9])

In [11]:
arr1*3

array([12, 15,  6, 18, 12, 21,  9])

In [13]:
arr1>5

array([False, False, False,  True, False,  True, False])

#### dot()

In [14]:
arr3=np.arange(6).reshape(2,3);

In [31]:
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [15]:
arr4=np.arange(6,12).reshape(3,2);

In [32]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [17]:
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

In [25]:
arr1

array([4, 5, 2, 6, 4, 7, 3])

In [26]:
arr2

array([6, 9, 3, 5, 8, 3, 7])

In [27]:
arr1.max()

7

In [29]:
arr2.min()

3

In [30]:
arr1.min()

2

In [33]:
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [34]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [35]:
arr3.min(axis=0)

array([0, 1, 2])

In [36]:
arr4.max(axis=1)

array([ 7,  9, 11])

In [37]:
arr3.sum()

15

In [38]:
arr4.sum()

51

In [39]:
arr3.sum(axis=1)

array([ 3, 12])

In [40]:
arr3.mean()

2.5

In [41]:
arr4.mean(axis=0)

array([8., 9.])

In [43]:
np.median(arr3)

2.5

In [44]:
arr3.std()

1.707825127659933

In [45]:
np.sin(arr3)

array([[ 0.        ,  0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 , -0.95892427]])

In [46]:
np.exp(arr4)

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])