In [1]:
import numpy as np;

### numpy.insert(arr, obj, values, axis=None)
- Insert values along the given axis before the given indices.

In [18]:
# help(np.insert);

In [3]:
arr = np.arange(10);
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.insert(arr, 2, 20)

array([ 0,  1, 20,  2,  3,  4,  5,  6,  7,  8,  9])

In [8]:
np.insert(arr, 10, 39)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 39])

In [9]:
arr = np.zeros((3,3), dtype=np.short);
arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int16)

In [11]:
np.insert(arr, [1,1], 100)

array([  0, 100, 100,   0,   0,   0,   0,   0,   0,   0,   0], dtype=int16)

In [13]:
np.insert(arr, 2, 55, axis=1)

array([[ 0,  0, 55,  0],
       [ 0,  0, 55,  0],
       [ 0,  0, 55,  0]], dtype=int16)

In [14]:
np.insert(arr, 3, [4,5,6], axis=0)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [4, 5, 6]], dtype=int16)

In [15]:
np.insert(arr=arr, obj=(0,2), values=[32,66,34], axis=0)

array([[32, 66, 34],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [32, 66, 34],
       [ 0,  0,  0]], dtype=int16)

In [20]:
np.insert(arr, 0, 3.3, axis=0)   # type casting

array([[3, 3, 3],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int16)

In [24]:
np.insert(arr, 2, [False, 343.4, 34])

array([  0,   0,   0, 343,  34,   0,   0,   0,   0,   0,   0,   0],
      dtype=int16)

In [26]:
np.insert(arr, 2, [False, 343.4, True], axis=0)

array([[  0,   0,   0],
       [  0,   0,   0],
       [  0, 343,   1],
       [  0,   0,   0]], dtype=int16)

### numpy.append(arr, values, axis=None)
- Append values to the end of an array.

In [27]:
arr = np.random.randint(3,100,size=(4,5));
arr

array([[65, 42, 83, 48,  9],
       [73, 25, 31, 77, 48],
       [11, 69, 75, 17, 59],
       [ 5, 57, 80, 19, 96]])

In [31]:
np.append(arr, 344)

array([ 65,  42,  83,  48,   9,  73,  25,  31,  77,  48,  11,  69,  75,
        17,  59,   5,  57,  80,  19,  96, 344])

In [39]:
np.append(arr, [[43,52,23,52,23]], axis=0)

array([[65, 42, 83, 48,  9],
       [73, 25, 31, 77, 48],
       [11, 69, 75, 17, 59],
       [ 5, 57, 80, 19, 96],
       [43, 52, 23, 52, 23]])

In [36]:
arr1 = np.array([[3,5],[6,3]]);
arr1

array([[3, 5],
       [6, 3]])

In [37]:
np.append(arr1, [[3,4]], axis=0)

array([[3, 5],
       [6, 3],
       [3, 4]])

### numpy.delete(arr, obj, axis=None)
- Return a new array with sub-arrays along an axis deleted. For a one dimensional array, this returns those entries not returned by arr[obj].

In [44]:
arr = np.ones((5,2), dtype='e')
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float16)

In [45]:
np.delete(arr, 1)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float16)

In [46]:
np.delete(arr, (1,2,3,4,5))

array([1., 1., 1., 1., 1.], dtype=float16)

In [47]:
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float16)

In [48]:
np.delete(arr, 1, axis=0)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float16)

In [49]:
np.delete(arr, -1, axis=1)

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]], dtype=float16)