### Practice with emp taken data from oracle database

In [1]:
import numpy as np;
from io import StringIO;

In [5]:
file_name="text_files\emp_file.txt";

In [8]:
emp_data=np.genfromtxt(file_name);

In [9]:
emp_data

array([[       nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan],
       [       nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan],
       [ 7.369e+03,        nan,        nan,  7.902e+03,        nan,
         8.000e+02, -1.000e+00,  2.000e+01],
       [ 7.499e+03,        nan,        nan,  7.698e+03,        nan,
         1.600e+03,  3.000e+02,  3.000e+01],
       [ 7.521e+03,        nan,        nan,  7.698e+03,        nan,
         1.250e+03,  5.000e+02,  3.000e+01],
       [ 7.566e+03,        nan,        nan,  7.839e+03,        nan,
         2.975e+03, -1.000e+00,  2.000e+01],
       [ 7.654e+03,        nan,        nan,  7.698e+03,        nan,
         1.250e+03,  1.400e+03,  3.000e+01],
       [ 7.698e+03,        nan,        nan,  7.839e+03,        nan,
         2.850e+03, -1.000e+00,  3.000e+01],
       [ 7.782e+03,        nan,        nan,  7.839e+03,        nan,
         2.450e+03, -1.000e+

In [18]:
# assigning data types

In [23]:
data_type=(int,'|U8','|U10',int,'|U15',float,int,int)
emp_data=np.genfromtxt(file_name, dtype=data_type);
print(emp_data)

[(  -1, 'ENAME', 'JOB',   -1, 'HIREDATE',   nan,   -1, -1)
 (  -1, '--------', '---------',   -1, '---------',   nan,   -1, -1)
 (7369, 'SMITH', 'CLERK', 7902, '17-DEC-80',  800.,   -1, 20)
 (7499, 'ALLEN', 'SALESMAN', 7698, '20-FEB-81', 1600.,  300, 30)
 (7521, 'WARD', 'SALESMAN', 7698, '22-FEB-81', 1250.,  500, 30)
 (7566, 'JONES', 'MANAGER', 7839, '02-APR-81', 2975.,   -1, 20)
 (7654, 'MARTIN', 'SALESMAN', 7698, '28-SEP-81', 1250., 1400, 30)
 (7698, 'BLAKE', 'MANAGER', 7839, '01-MAY-81', 2850.,   -1, 30)
 (7782, 'CLARK', 'MANAGER', 7839, '09-JUN-81', 2450.,   -1, 10)
 (7788, 'SCOTT', 'ANALYST', 7566, '19-APR-87', 3000.,   -1, 20)
 (7839, 'KING', 'PRESIDENT', 7844, '17-NOV-81', 5000.,   -1, 10)
 (7844, 'TURNER', 'SALESMAN', 7698, '08-SEP-81', 1500.,    0, 30)
 (7876, 'ADAMS', 'CLERK', 7788, '23-MAY-87', 1100.,   -1, 20)
 (7900, 'JAMES', 'CLERK', 7698, '03-DEC-81',  950.,   -1, 30)
 (7902, 'FORD', 'ANALYST', 7566, '03-DEC-81', 3000.,   -1, 20)
 (7934, 'MILLER', 'CLERK', 7782, '23-JAN-

In [24]:
emp_data[0]

(-1, 'ENAME', 'JOB', -1, 'HIREDATE', nan, -1, -1)

In [25]:
emp_data[1]

(-1, '--------', '---------', -1, '---------', nan, -1, -1)

In [26]:
print(emp_data[2:7])

[(7369, 'SMITH', 'CLERK', 7902, '17-DEC-80',  800.,   -1, 20)
 (7499, 'ALLEN', 'SALESMAN', 7698, '20-FEB-81', 1600.,  300, 30)
 (7521, 'WARD', 'SALESMAN', 7698, '22-FEB-81', 1250.,  500, 30)
 (7566, 'JONES', 'MANAGER', 7839, '02-APR-81', 2975.,   -1, 20)
 (7654, 'MARTIN', 'SALESMAN', 7698, '28-SEP-81', 1250., 1400, 30)]


In [27]:
# Adding comment argument

In [28]:
emp_data=np.genfromtxt(file_name, dtype=data_type, comments=r"\\");
print(emp_data)

[(7369, 'SMITH', 'CLERK', 7902, '17-DEC-80',  800.,   -1, 20)
 (7499, 'ALLEN', 'SALESMAN', 7698, '20-FEB-81', 1600.,  300, 30)
 (7521, 'WARD', 'SALESMAN', 7698, '22-FEB-81', 1250.,  500, 30)
 (7566, 'JONES', 'MANAGER', 7839, '02-APR-81', 2975.,   -1, 20)
 (7654, 'MARTIN', 'SALESMAN', 7698, '28-SEP-81', 1250., 1400, 30)
 (7698, 'BLAKE', 'MANAGER', 7839, '01-MAY-81', 2850.,   -1, 30)
 (7782, 'CLARK', 'MANAGER', 7839, '09-JUN-81', 2450.,   -1, 10)
 (7788, 'SCOTT', 'ANALYST', 7566, '19-APR-87', 3000.,   -1, 20)
 (7839, 'KING', 'PRESIDENT', 7844, '17-NOV-81', 5000.,   -1, 10)
 (7844, 'TURNER', 'SALESMAN', 7698, '08-SEP-81', 1500.,    0, 30)
 (7876, 'ADAMS', 'CLERK', 7788, '23-MAY-87', 1100.,   -1, 20)
 (7900, 'JAMES', 'CLERK', 7698, '03-DEC-81',  950.,   -1, 30)
 (7902, 'FORD', 'ANALYST', 7566, '03-DEC-81', 3000.,   -1, 20)
 (7934, 'MILLER', 'CLERK', 7782, '23-JAN-82', 1300.,   -1, 10)]


In [34]:
# default names

In [35]:
emp_data=np.genfromtxt(file_name, dtype=data_type, comments='\\')
emp_data

array([(7369, 'SMITH', 'CLERK', 7902, '17-DEC-80',  800.,   -1, 20),
       (7499, 'ALLEN', 'SALESMAN', 7698, '20-FEB-81', 1600.,  300, 30),
       (7521, 'WARD', 'SALESMAN', 7698, '22-FEB-81', 1250.,  500, 30),
       (7566, 'JONES', 'MANAGER', 7839, '02-APR-81', 2975.,   -1, 20),
       (7654, 'MARTIN', 'SALESMAN', 7698, '28-SEP-81', 1250., 1400, 30),
       (7698, 'BLAKE', 'MANAGER', 7839, '01-MAY-81', 2850.,   -1, 30),
       (7782, 'CLARK', 'MANAGER', 7839, '09-JUN-81', 2450.,   -1, 10),
       (7788, 'SCOTT', 'ANALYST', 7566, '19-APR-87', 3000.,   -1, 20),
       (7839, 'KING', 'PRESIDENT', 7844, '17-NOV-81', 5000.,   -1, 10),
       (7844, 'TURNER', 'SALESMAN', 7698, '08-SEP-81', 1500.,    0, 30),
       (7876, 'ADAMS', 'CLERK', 7788, '23-MAY-87', 1100.,   -1, 20),
       (7900, 'JAMES', 'CLERK', 7698, '03-DEC-81',  950.,   -1, 30),
       (7902, 'FORD', 'ANALYST', 7566, '03-DEC-81', 3000.,   -1, 20),
       (7934, 'MILLER', 'CLERK', 7782, '23-JAN-82', 1300.,   -1, 10)],
      d

In [36]:
emp_data['f0']

array([7369, 7499, 7521, 7566, 7654, 7698, 7782, 7788, 7839, 7844, 7876,
       7900, 7902, 7934])

In [37]:
emp_data['f4']

array(['17-DEC-80', '20-FEB-81', '22-FEB-81', '02-APR-81', '28-SEP-81',
       '01-MAY-81', '09-JUN-81', '19-APR-87', '17-NOV-81', '08-SEP-81',
       '23-MAY-87', '03-DEC-81', '03-DEC-81', '23-JAN-82'], dtype='<U15')

In [33]:
# defaultfmt argument

In [ ]:
# to give our own format names

In [38]:
emp_data=np.genfromtxt(file_name, dtype=data_type, comments='\\',  defaultfmt="val_%02i");
emp_data

array([(7369, 'SMITH', 'CLERK', 7902, '17-DEC-80',  800.,   -1, 20),
       (7499, 'ALLEN', 'SALESMAN', 7698, '20-FEB-81', 1600.,  300, 30),
       (7521, 'WARD', 'SALESMAN', 7698, '22-FEB-81', 1250.,  500, 30),
       (7566, 'JONES', 'MANAGER', 7839, '02-APR-81', 2975.,   -1, 20),
       (7654, 'MARTIN', 'SALESMAN', 7698, '28-SEP-81', 1250., 1400, 30),
       (7698, 'BLAKE', 'MANAGER', 7839, '01-MAY-81', 2850.,   -1, 30),
       (7782, 'CLARK', 'MANAGER', 7839, '09-JUN-81', 2450.,   -1, 10),
       (7788, 'SCOTT', 'ANALYST', 7566, '19-APR-87', 3000.,   -1, 20),
       (7839, 'KING', 'PRESIDENT', 7844, '17-NOV-81', 5000.,   -1, 10),
       (7844, 'TURNER', 'SALESMAN', 7698, '08-SEP-81', 1500.,    0, 30),
       (7876, 'ADAMS', 'CLERK', 7788, '23-MAY-87', 1100.,   -1, 20),
       (7900, 'JAMES', 'CLERK', 7698, '03-DEC-81',  950.,   -1, 30),
       (7902, 'FORD', 'ANALYST', 7566, '03-DEC-81', 3000.,   -1, 20),
       (7934, 'MILLER', 'CLERK', 7782, '23-JAN-82', 1300.,   -1, 10)],
      d

In [39]:
emp_data['val_06']

array([  -1,  300,  500,   -1, 1400,   -1,   -1,   -1,   -1,    0,   -1,
         -1,   -1,   -1])

In [40]:
emp_data['val_04']

array(['17-DEC-80', '20-FEB-81', '22-FEB-81', '02-APR-81', '28-SEP-81',
       '01-MAY-81', '09-JUN-81', '19-APR-87', '17-NOV-81', '08-SEP-81',
       '23-MAY-87', '03-DEC-81', '03-DEC-81', '23-JAN-82'], dtype='<U15')

In [21]:
# Assigning names to each column

In [41]:
name="Empno,ename,job,mgr,hiredate,sallary,comm,dept";
emp_data=np.genfromtxt(file_name, dtype=data_type, comments='\\',  names=name)
emp_data

array([(7369, 'SMITH', 'CLERK', 7902, '17-DEC-80',  800.,   -1, 20),
       (7499, 'ALLEN', 'SALESMAN', 7698, '20-FEB-81', 1600.,  300, 30),
       (7521, 'WARD', 'SALESMAN', 7698, '22-FEB-81', 1250.,  500, 30),
       (7566, 'JONES', 'MANAGER', 7839, '02-APR-81', 2975.,   -1, 20),
       (7654, 'MARTIN', 'SALESMAN', 7698, '28-SEP-81', 1250., 1400, 30),
       (7698, 'BLAKE', 'MANAGER', 7839, '01-MAY-81', 2850.,   -1, 30),
       (7782, 'CLARK', 'MANAGER', 7839, '09-JUN-81', 2450.,   -1, 10),
       (7788, 'SCOTT', 'ANALYST', 7566, '19-APR-87', 3000.,   -1, 20),
       (7839, 'KING', 'PRESIDENT', 7844, '17-NOV-81', 5000.,   -1, 10),
       (7844, 'TURNER', 'SALESMAN', 7698, '08-SEP-81', 1500.,    0, 30),
       (7876, 'ADAMS', 'CLERK', 7788, '23-MAY-87', 1100.,   -1, 20),
       (7900, 'JAMES', 'CLERK', 7698, '03-DEC-81',  950.,   -1, 30),
       (7902, 'FORD', 'ANALYST', 7566, '03-DEC-81', 3000.,   -1, 20),
       (7934, 'MILLER', 'CLERK', 7782, '23-JAN-82', 1300.,   -1, 10)],
      d

In [42]:
emp_data['ename']

array(['SMITH', 'ALLEN', 'WARD', 'JONES', 'MARTIN', 'BLAKE', 'CLARK',
       'SCOTT', 'KING', 'TURNER', 'ADAMS', 'JAMES', 'FORD', 'MILLER'],
      dtype='<U8')

In [43]:
emp_data['sallary']

array([ 800., 1600., 1250., 2975., 1250., 2850., 2450., 3000., 5000.,
       1500., 1100.,  950., 3000., 1300.])

In [44]:
emp_data['comm']

array([  -1,  300,  500,   -1, 1400,   -1,   -1,   -1,   -1,    0,   -1,
         -1,   -1,   -1])

In [45]:
# another way to assign names to to each column

In [47]:
emp_data=np.genfromtxt(file_name, dtype=data_type, comments='\\', names=True);
emp_data

array([(7369, 'SMITH', 'CLERK', 7902, '17-DEC-80',  800.,   -1, 20),
       (7499, 'ALLEN', 'SALESMAN', 7698, '20-FEB-81', 1600.,  300, 30),
       (7521, 'WARD', 'SALESMAN', 7698, '22-FEB-81', 1250.,  500, 30),
       (7566, 'JONES', 'MANAGER', 7839, '02-APR-81', 2975.,   -1, 20),
       (7654, 'MARTIN', 'SALESMAN', 7698, '28-SEP-81', 1250., 1400, 30),
       (7698, 'BLAKE', 'MANAGER', 7839, '01-MAY-81', 2850.,   -1, 30),
       (7782, 'CLARK', 'MANAGER', 7839, '09-JUN-81', 2450.,   -1, 10),
       (7788, 'SCOTT', 'ANALYST', 7566, '19-APR-87', 3000.,   -1, 20),
       (7839, 'KING', 'PRESIDENT', 7844, '17-NOV-81', 5000.,   -1, 10),
       (7844, 'TURNER', 'SALESMAN', 7698, '08-SEP-81', 1500.,    0, 30),
       (7876, 'ADAMS', 'CLERK', 7788, '23-MAY-87', 1100.,   -1, 20),
       (7900, 'JAMES', 'CLERK', 7698, '03-DEC-81',  950.,   -1, 30),
       (7902, 'FORD', 'ANALYST', 7566, '03-DEC-81', 3000.,   -1, 20),
       (7934, 'MILLER', 'CLERK', 7782, '23-JAN-82', 1300.,   -1, 10)],
      d

In [48]:
emp_data['EMPNO']

array([7369, 7499, 7521, 7566, 7654, 7698, 7782, 7788, 7839, 7844, 7876,
       7900, 7902, 7934])

In [49]:
emp_data['COMM']

array([  -1,  300,  500,   -1, 1400,   -1,   -1,   -1,   -1,    0,   -1,
         -1,   -1,   -1])

In [51]:
emp_data["HIREDATE"]  # etc

array(['17-DEC-80', '20-FEB-81', '22-FEB-81', '02-APR-81', '28-SEP-81',
       '01-MAY-81', '09-JUN-81', '19-APR-87', '17-NOV-81', '08-SEP-81',
       '23-MAY-87', '03-DEC-81', '03-DEC-81', '23-JAN-82'], dtype='<U15')

In [53]:
# skip_header and skip_footer argument

In [54]:
emp_data=np.genfromtxt(file_name, dtype=data_type, comments='\\', names=True, skip_header=1, skip_footer=5);
emp_data

array([(7499, 'ALLEN', 'SALESMAN', 7698, '20-FEB-81', 1600.,  300, 30),
       (7521, 'WARD', 'SALESMAN', 7698, '22-FEB-81', 1250.,  500, 30),
       (7566, 'JONES', 'MANAGER', 7839, '02-APR-81', 2975.,   -1, 20),
       (7654, 'MARTIN', 'SALESMAN', 7698, '28-SEP-81', 1250., 1400, 30),
       (7698, 'BLAKE', 'MANAGER', 7839, '01-MAY-81', 2850.,   -1, 30),
       (7782, 'CLARK', 'MANAGER', 7839, '09-JUN-81', 2450.,   -1, 10),
       (7788, 'SCOTT', 'ANALYST', 7566, '19-APR-87', 3000.,   -1, 20),
       (7839, 'KING', 'PRESIDENT', 7844, '17-NOV-81', 5000.,   -1, 10)],
      dtype=[('7369', '<i4'), ('SMITH', '<U8'), ('CLERK', '<U10'), ('7902', '<i4'), ('17DEC80', '<U15'), ('800', '<f8'), ('1', '<i4'), ('20', '<i4')])

In [55]:
emp_data.size

8

In [56]:
emp_data.shape

(8,)

In [57]:
# using usecols argument

In [58]:
emp_data=np.genfromtxt(file_name, dtype=data_type, comments='\\', names=True, usecols=1);
emp_data

array([('SMITH',), ('ALLEN',), ('WARD',), ('JONES',), ('MARTIN',),
       ('BLAKE',), ('CLARK',), ('SCOTT',), ('KING',), ('TURNER',),
       ('ADAMS',), ('JAMES',), ('FORD',), ('MILLER',)],
      dtype=[('ENAME', '<U8')])

In [60]:
emp_data=np.genfromtxt(file_name, dtype=data_type, comments='\\', names=True, usecols=[0,1,2,5]);
print(emp_data)

[(7369, 'SMITH', 'CLERK',  800.) (7499, 'ALLEN', 'SALESMAN', 1600.)
 (7521, 'WARD', 'SALESMAN', 1250.) (7566, 'JONES', 'MANAGER', 2975.)
 (7654, 'MARTIN', 'SALESMAN', 1250.) (7698, 'BLAKE', 'MANAGER', 2850.)
 (7782, 'CLARK', 'MANAGER', 2450.) (7788, 'SCOTT', 'ANALYST', 3000.)
 (7839, 'KING', 'PRESIDENT', 5000.) (7844, 'TURNER', 'SALESMAN', 1500.)
 (7876, 'ADAMS', 'CLERK', 1100.) (7900, 'JAMES', 'CLERK',  950.)
 (7902, 'FORD', 'ANALYST', 3000.) (7934, 'MILLER', 'CLERK', 1300.)]


In [62]:
emp_data=np.genfromtxt(file_name, dtype=data_type, comments='\\', names=True, usecols=['ENAME','SAL','HIREDATE','DEPTNO']);
print(emp_data)

[('SMITH',  800., '17-DEC-80', 20) ('ALLEN', 1600., '20-FEB-81', 30)
 ('WARD', 1250., '22-FEB-81', 30) ('JONES', 2975., '02-APR-81', 20)
 ('MARTIN', 1250., '28-SEP-81', 30) ('BLAKE', 2850., '01-MAY-81', 30)
 ('CLARK', 2450., '09-JUN-81', 10) ('SCOTT', 3000., '19-APR-87', 20)
 ('KING', 5000., '17-NOV-81', 10) ('TURNER', 1500., '08-SEP-81', 30)
 ('ADAMS', 1100., '23-MAY-87', 20) ('JAMES',  950., '03-DEC-81', 30)
 ('FORD', 3000., '03-DEC-81', 20) ('MILLER', 1300., '23-JAN-82', 10)]


In [63]:
# using missing_values and filling_values argument

In [67]:
emp_data=np.genfromtxt(file_name, dtype=data_type, comments='\\', names=True, missing_values={'COMM':'N/A'});
print(emp_data)

[(7369, 'SMITH', 'CLERK', 7902, '17-DEC-80',  800.,   -1, 20)
 (7499, 'ALLEN', 'SALESMAN', 7698, '20-FEB-81', 1600.,  300, 30)
 (7521, 'WARD', 'SALESMAN', 7698, '22-FEB-81', 1250.,  500, 30)
 (7566, 'JONES', 'MANAGER', 7839, '02-APR-81', 2975.,   -1, 20)
 (7654, 'MARTIN', 'SALESMAN', 7698, '28-SEP-81', 1250., 1400, 30)
 (7698, 'BLAKE', 'MANAGER', 7839, '01-MAY-81', 2850.,   -1, 30)
 (7782, 'CLARK', 'MANAGER', 7839, '09-JUN-81', 2450.,   -1, 10)
 (7788, 'SCOTT', 'ANALYST', 7566, '19-APR-87', 3000.,   -1, 20)
 (7839, 'KING', 'PRESIDENT', 7844, '17-NOV-81', 5000.,   -1, 10)
 (7844, 'TURNER', 'SALESMAN', 7698, '08-SEP-81', 1500.,   -1, 30)
 (7876, 'ADAMS', 'CLERK', 7788, '23-MAY-87', 1100.,   -1, 20)
 (7900, 'JAMES', 'CLERK', 7698, '03-DEC-81',  950.,   -1, 30)
 (7902, 'FORD', 'ANALYST', 7566, '03-DEC-81', 3000.,   -1, 20)
 (7934, 'MILLER', 'CLERK', 7782, '23-JAN-82', 1300.,   -1, 10)]


In [68]:
emp_data=np.genfromtxt(file_name, dtype=data_type, comments='\\', names=True, missing_values={'COMM':'N/A'}, filling_values={'COMM':0});
print(emp_data)

[(7369, 'SMITH', 'CLERK', 7902, '17-DEC-80',  800.,    0, 20)
 (7499, 'ALLEN', 'SALESMAN', 7698, '20-FEB-81', 1600.,  300, 30)
 (7521, 'WARD', 'SALESMAN', 7698, '22-FEB-81', 1250.,  500, 30)
 (7566, 'JONES', 'MANAGER', 7839, '02-APR-81', 2975.,    0, 20)
 (7654, 'MARTIN', 'SALESMAN', 7698, '28-SEP-81', 1250., 1400, 30)
 (7698, 'BLAKE', 'MANAGER', 7839, '01-MAY-81', 2850.,    0, 30)
 (7782, 'CLARK', 'MANAGER', 7839, '09-JUN-81', 2450.,    0, 10)
 (7788, 'SCOTT', 'ANALYST', 7566, '19-APR-87', 3000.,    0, 20)
 (7839, 'KING', 'PRESIDENT', 7844, '17-NOV-81', 5000.,    0, 10)
 (7844, 'TURNER', 'SALESMAN', 7698, '08-SEP-81', 1500.,    0, 30)
 (7876, 'ADAMS', 'CLERK', 7788, '23-MAY-87', 1100.,    0, 20)
 (7900, 'JAMES', 'CLERK', 7698, '03-DEC-81',  950.,    0, 30)
 (7902, 'FORD', 'ANALYST', 7566, '03-DEC-81', 3000.,    0, 20)
 (7934, 'MILLER', 'CLERK', 7782, '23-JAN-82', 1300.,    0, 10)]


In [69]:
# the converters argument

In [92]:
from datetime import datetime;
data_type=(int,'|U8','|U10',int,'datetime64[D]',float,int,int)
date_fmt="%d-%m-%Y";
convert=lambda x:  datetime.strptime(str(x),date_fmt).date();
emp_data=np.genfromtxt(file_name, dtype=data_type, comments='\\', names=True, converters={'HIREDATE': convert});
print(emp_data)

[(7369, 'SMITH', 'CLERK', 7902, 'NaT',  800.,   -1, 20)
 (7499, 'ALLEN', 'SALESMAN', 7698, 'NaT', 1600.,  300, 30)
 (7521, 'WARD', 'SALESMAN', 7698, 'NaT', 1250.,  500, 30)
 (7566, 'JONES', 'MANAGER', 7839, 'NaT', 2975.,   -1, 20)
 (7654, 'MARTIN', 'SALESMAN', 7698, 'NaT', 1250., 1400, 30)
 (7698, 'BLAKE', 'MANAGER', 7839, 'NaT', 2850.,   -1, 30)
 (7782, 'CLARK', 'MANAGER', 7839, 'NaT', 2450.,   -1, 10)
 (7788, 'SCOTT', 'ANALYST', 7566, 'NaT', 3000.,   -1, 20)
 (7839, 'KING', 'PRESIDENT', 7844, 'NaT', 5000.,   -1, 10)
 (7844, 'TURNER', 'SALESMAN', 7698, 'NaT', 1500.,   -1, 30)
 (7876, 'ADAMS', 'CLERK', 7788, 'NaT', 1100.,   -1, 20)
 (7900, 'JAMES', 'CLERK', 7698, 'NaT',  950.,   -1, 30)
 (7902, 'FORD', 'ANALYST', 7566, 'NaT', 3000.,   -1, 20)
 (7934, 'MILLER', 'CLERK', 7782, 'NaT', 1300.,   -1, 10)]


In [79]:
from datetime import datetime;
date_format="%d-%m-%Y";
date="23-04-2019";
date_obj=datetime.strptime(date,date_format).date();
date_obj

datetime.date(2019, 4, 23)