### Properties and Attributes of Numpy Array

#### shape

In [2]:
import numpy as np;

In [3]:
arr1=np.array([[[3,4],[8,6],[7,1]]]);

In [5]:
arr1

array([[[3, 4],
        [8, 6],
        [7, 1]]])

In [4]:
arr1.shape

(1, 3, 2)

In [7]:
arr1=np.array([[[3,5],[6,2]],[[5,2],[7,4]]]);

In [8]:
arr1

array([[[3, 5],
        [6, 2]],

       [[5, 2],
        [7, 4]]])

In [9]:
arr1.shape

(2, 2, 2)

In [10]:
arr1.ndim

3

In [12]:
arr1=np.array([[[3,5]],[[6,2]],[[9,3]]]);

In [13]:
arr1.shape

(3, 1, 2)

In [15]:
arr1=np.array([[[45],[65]],[[87],[26]]]);

In [16]:
arr1

array([[[45],
        [65]],

       [[87],
        [26]]])

#### ndim

In [17]:
arr1.ndim

3

#### size

In [18]:
arr1.size

4

In [19]:
arr2=np.zeros((3,3));

In [20]:
arr2.size

9

#### itemsize

In [21]:
arr1.itemsize

4

In [22]:
arr2.itemsize

8

#### dtype

In [23]:
arr1.dtype

dtype('int32')

In [24]:
arr2.dtype

dtype('float64')

#### astype('')

In [25]:
arr1.dtype

dtype('int32')

In [26]:
arr1.astype('float')

array([[[45.],
        [65.]],

       [[87.],
        [26.]]])

In [28]:
arr3=arr1.astype('float');

In [29]:
arr3

array([[[45.],
        [65.]],

       [[87.],
        [26.]]])

In [31]:
arr3.dtype

dtype('float64')