### Reshaping

In [2]:
import numpy as np;

#### ravel()

In [3]:
arr1=np.identity(3);

In [4]:
arr1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
arr1.shape

(3, 3)

In [6]:
arr1.ravel()

array([1., 0., 0., 0., 1., 0., 0., 0., 1.])

In [11]:
arr1.ravel().shape

(9,)

#### reshape()

In [13]:
arr2=np.linspace(21,44,24);

In [14]:
arr2

array([21., 22., 23., 24., 25., 26., 27., 28., 29., 30., 31., 32., 33.,
       34., 35., 36., 37., 38., 39., 40., 41., 42., 43., 44.])

In [16]:
arr2.reshape(4,6)

array([[21., 22., 23., 24., 25., 26.],
       [27., 28., 29., 30., 31., 32.],
       [33., 34., 35., 36., 37., 38.],
       [39., 40., 41., 42., 43., 44.]])

In [18]:
arr2.reshape(6,4)

array([[21., 22., 23., 24.],
       [25., 26., 27., 28.],
       [29., 30., 31., 32.],
       [33., 34., 35., 36.],
       [37., 38., 39., 40.],
       [41., 42., 43., 44.]])

#### transpose()

In [19]:
arr1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
arr2

array([21., 22., 23., 24., 25., 26., 27., 28., 29., 30., 31., 32., 33.,
       34., 35., 36., 37., 38., 39., 40., 41., 42., 43., 44.])

In [21]:
arr1.transpose()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
arr3=np.array([[4,2,6,1],[6,1,5,3]]);

In [23]:
arr3.transpose()

array([[4, 6],
       [2, 1],
       [6, 5],
       [1, 3]])

#### staking

In [32]:
arr4=np.ones((2,4));

In [33]:
arr3

array([[4, 2, 6, 1],
       [6, 1, 5, 3]])

In [34]:
arr4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
arr3.dtype

dtype('int32')

In [36]:
arr4.dtype

dtype('float64')

In [38]:
np.hstack((arr3,arr4))

array([[4., 2., 6., 1., 1., 1., 1., 1.],
       [6., 1., 5., 3., 1., 1., 1., 1.]])

In [39]:
np.vstack((arr3,arr4))

array([[4., 2., 6., 1.],
       [6., 1., 5., 3.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [42]:
type(np.vstack((arr3,arr4)).dtype)

numpy.dtype[float64]

#### splitting

In [43]:
arr3

array([[4, 2, 6, 1],
       [6, 1, 5, 3]])

In [46]:
np.hsplit(arr3,4)

[array([[4],
        [6]]),
 array([[2],
        [1]]),
 array([[6],
        [5]]),
 array([[1],
        [3]])]

In [47]:
np.vsplit(arr3,2)

[array([[4, 2, 6, 1]]), array([[6, 1, 5, 3]])]

In [49]:
np.hsplit(arr3,2)

[array([[4, 2],
        [6, 1]]),
 array([[6, 1],
        [5, 3]])]