### Structure Array

- Structured arrays are ndarrays whose datatype is a composition of simpler datatypes organized as a sequence of named fields.

In [2]:
import numpy as np;

In [4]:
arr1=np.array([('kamran',4.5,50),('usman',5,60),('wahid',5.4,61)], dtype=[('name','|U10'),('hight','f8'),('wight','i4')]);

In [5]:
arr1

array([('kamran', 4.5, 50), ('usman', 5. , 60), ('wahid', 5.4, 61)],
      dtype=[('name', '<U10'), ('hight', '<f8'), ('wight', '<i4')])

In [6]:
arr1[0]

('kamran', 4.5, 50)

In [9]:
arr1[0].dtype

dtype([('name', '<U10'), ('hight', '<f8'), ('wight', '<i4')])

In [10]:
arr1['name']

array(['kamran', 'usman', 'wahid'], dtype='<U10')

In [11]:
arr1.size

3

In [12]:
arr1[0].size

1

In [21]:
arr1=np.array([('kamran',4.5,50),('usman',5,60),('wahid',5.4,61)], dtype="U10,float,int");

In [22]:
arr1

array([('kamran', 4.5, 50), ('usman', 5. , 60), ('wahid', 5.4, 61)],
      dtype=[('f0', '<U10'), ('f1', '<f8'), ('f2', '<i4')])

In [23]:
print(arr1)

[('kamran', 4.5, 50) ('usman', 5. , 60) ('wahid', 5.4, 61)]


In [24]:
for i in arr1:
    print(i)

('kamran', 4.5, 50)
('usman', 5., 60)
('wahid', 5.4, 61)


In [25]:
arr1['f0']

array(['kamran', 'usman', 'wahid'], dtype='<U10')

In [26]:
arr1['f1']

array([4.5, 5. , 5.4])

In [27]:
arr1['f2']

array([50, 60, 61])

In [28]:
arr1[0][1]                 # we can accress a specific element as will

4.5

In [34]:
arr1=np.array([('kamran',4.5,50),('usman',5,60),('wahid',5.4,61)], dtype="U10,f8,i4");

In [35]:
arr1

array([('kamran', 4.5, 50), ('usman', 5. , 60), ('wahid', 5.4, 61)],
      dtype=[('f0', '<U10'), ('f1', '<f8'), ('f2', '<i4')])

In [36]:
print(arr1)

[('kamran', 4.5, 50) ('usman', 5. , 60) ('wahid', 5.4, 61)]


In [41]:
arr1=np.array([('kamran',4.5,50),('usman',5,60),('wahid',5.4,61)], dtype=[('name','|U10'),('hight','f8'),('wight','i4')]);

In [69]:
avg_wight=sum(arr1['wight'])/len(arr1['wight']);
print("the average wight is : ",avg_wight);

the average wight is :  57.0


In [64]:
list(map((lambda x: x if len(x)==5 else None), arr1['name']))

[None, 'usman', 'wahid']

In [68]:
list(filter(None,list(map((lambda x: x if len(x)==5 else None), arr1['name']))))

['usman', 'wahid']

### Structure Datatype Creation

- 1. A list of tuples, one type per field

In [75]:
arr1=np.array([('kamran',30000,10),('wahid',3000,20)], dtype=[('name','U10'),('sal',np.int32),('dept',np.int8)])

In [76]:
arr1

array([('kamran', 30000, 10), ('wahid',  3000, 20)],
      dtype=[('name', '<U10'), ('sal', '<i4'), ('dept', 'i1')])

In [91]:
data_type=[('prdct_name','U20'),('price',np.int32),('RAM',np.int8),('storage',np.int16)];
arr2=np.array([('laptop',32000,4,500),('mobile',50000,4,128),('tablet',20000,4,128)], dtype=data_type);

In [92]:
arr2

array([('laptop', 32000, 4, 500), ('mobile', 50000, 4, 128),
       ('tablet', 20000, 4, 128)],
      dtype=[('prdct_name', '<U20'), ('price', '<i4'), ('RAM', 'i1'), ('storage', '<i2')])

In [93]:
arr2['prdct_name']

array(['laptop', 'mobile', 'tablet'], dtype='<U20')

In [94]:
arr2['price']

array([32000, 50000, 20000])

In [95]:
arr2['storage']

array([500, 128, 128], dtype=int16)

- 2. A String of comma separated dtype specifications

- 3. Adictionary of field parameter arrays

- 4. A dictionary of field names