## The absolute basics for beginners

### Array

- An array is usually a fixed-size container of items of the same type and size.
- The NumPy array is a data structure consisting of two parts: the contiguous data buffer with the actual data elements and the metadata that contains information about the data buffer. The metadata includes data type, strides, and other important information that helps manipulate the ndarray easily.

In [6]:
import  numpy as np;

In [7]:
arr=np.arange(5);

In [8]:
arr

array([0, 1, 2, 3, 4])

In [9]:
arr.shape

(5,)

In [12]:
type(arr.shape)

tuple

In [13]:
arr.dtype

dtype('int32')

In [15]:
arr.ndim

1

In [16]:
# Tensor: term used for 3D or higher dimensional arrays

### How to create a basic array

#### np.array()

In [18]:
arr=np.array([[23,434,53,45],[455,734,34,634]]);

In [19]:
arr

array([[ 23, 434,  53,  45],
       [455, 734,  34, 634]])

In [20]:
arr.dtype

dtype('int32')

In [31]:
# creating array from list

In [21]:
L=[[[94,57,39,63],[94,36,35,73]],[[44,63,63,23],[45,74,34,53]]];

In [22]:
arr1=np.array(L)

In [23]:
arr1

array([[[94, 57, 39, 63],
        [94, 36, 35, 73]],

       [[44, 63, 63, 23],
        [45, 74, 34, 53]]])

In [24]:
arr1.shape

(2, 2, 4)

In [25]:
arr1.ndim

3

In [30]:
# creating from tupel

In [26]:
T=((34,53,34,64),(34,63,23,63));

In [27]:
arr2=np.array(T);

In [29]:
arr2

array([[34, 53, 34, 64],
       [34, 63, 23, 63]])

In [32]:
# specifying data type

In [33]:
arr3=np.array([[23,53,64,26],[95,35,83,25]], np.float32);

In [34]:
arr3

array([[23., 53., 64., 26.],
       [95., 35., 83., 25.]], dtype=float32)

In [35]:
arr3.dtype

dtype('float32')

In [36]:
arr3.ndim

2

#### np.ones();

In [37]:
arr1=np.ones(3)

In [38]:
arr1

array([1., 1., 1.])

In [58]:
arr2=np.ones((3,3), dtype=np.int32)

In [59]:
arr2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [60]:
arr2.dtype

dtype('int32')

In [61]:
arr2=np.ones((3,4),np.float32)

In [62]:
arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [63]:
arr2.shape

(3, 4)

In [64]:
arr2.ndim

2

In [65]:
arr2.dtype

dtype('float32')

In [66]:
arr2.size

12

In [67]:
# creating arrays with same elements

In [69]:
arr3=np.ones((3,3,3,3))*4

In [70]:
arr3

array([[[[4., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]],

        [[4., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]],

        [[4., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]]],


       [[[4., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]],

        [[4., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]],

        [[4., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]]],


       [[[4., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]],

        [[4., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]],

        [[4., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]]]])

In [71]:
arr3.ndim

4

In [72]:
arr3.size

81

In [73]:
arr3.shape

(3, 3, 3, 3)

In [74]:
arr3.dtype

dtype('float64')

In [81]:
arr3[np.zeros(3).astype(int),  np.zeros(3).astype(int),  np.zeros(3).astype(int)]

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [82]:
arr3[np.ones(3).astype(int),  np.ones(3).astype(int),  np.zeros(3).astype(int)]=0

In [80]:
arr3

array([[[[4., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]],

        [[4., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]],

        [[4., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]]],


       [[[4., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]],

        [[0., 0., 0.],
         [4., 4., 4.],
         [4., 4., 4.]],

        [[4., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]]],


       [[[4., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]],

        [[4., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]],

        [[4., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]]]])

In [83]:
rand=np.random.randint(low=0, high=100, size=(3,3,3,3))

In [84]:
rand

array([[[[40, 64, 12],
         [ 0, 19, 65],
         [80, 70, 76]],

        [[34, 57, 35],
         [ 6, 88, 73],
         [95, 23, 98]],

        [[82, 91, 12],
         [95, 93, 10],
         [85, 79, 43]]],


       [[[36, 36, 42],
         [62, 93, 75],
         [60, 25, 36]],

        [[68, 46, 68],
         [73, 66, 87],
         [90, 54, 45]],

        [[31,  8,  4],
         [36, 47, 10],
         [77,  5, 55]]],


       [[[34, 74, 93],
         [50,  3,  9],
         [ 9, 11, 12]],

        [[61, 68, 83],
         [60, 61, 46],
         [46, 16, 16]],

        [[46, 80, 73],
         [27, 31, 79],
         [43, 88, 35]]]])

In [87]:
rand[np.ones(3).astype(int),  np.ones(3).astype(int),  np.zeros(3).astype(int)]

array([[68, 46, 68],
       [68, 46, 68],
       [68, 46, 68]])

#### np.zeros()

In [88]:
arr1=np.zeros(6);

In [89]:
arr1

array([0., 0., 0., 0., 0., 0.])

In [90]:
arr1.dtype

dtype('float64')

In [94]:
arr2=np.zeros((4,5,3),float);     # the second argument is for data type.  you must incluse shape in a tuple

In [95]:
arr2

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [96]:
arr2.dtype

dtype('float64')

In [97]:
arr3=np.zeros((3,3))+5;

In [98]:
arr3

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [100]:
arr3[slice(1,4)]

array([[5., 5., 5.],
       [5., 5., 5.]])

In [101]:
arr3[slice(1,4)]=0

In [102]:
arr3

array([[5., 5., 5.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [103]:
arr3[slice(1,2),slice(1,2)]

array([[0.]])

In [104]:
arr3[slice(1,2),slice(1,2)]=5

In [105]:
arr3

array([[5., 5., 5.],
       [0., 5., 0.],
       [0., 0., 0.]])

In [106]:
arr3[slice(None,None,1),np.arange(3)]

array([[5., 5., 5.],
       [0., 5., 0.],
       [0., 0., 0.]])

In [108]:
arr3[np.arange(3),np.arange(3)]

array([5., 5., 0.])

#### np.arange();

In [109]:
arr1=np.arange(5);

In [110]:
arr1

array([0, 1, 2, 3, 4])

In [111]:
arr1.dtype

dtype('int32')

In [114]:
arr2=np.arange(5,20,2)

In [115]:
arr2

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [116]:
arr2.size

8

In [118]:
arr2.reshape(2,2,2)

array([[[ 5,  7],
        [ 9, 11]],

       [[13, 15],
        [17, 19]]])

In [119]:
reverse_arr=np.arange(20,10,-1)

In [120]:
reverse_arr

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

In [121]:
multiple_5=np.arange(0,51,5)

In [122]:
multiple_5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [123]:
multiple_5=np.arange(1,11,1)*5

In [124]:
multiple_5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [125]:
float_arr=np.arange(2.1,3.1,0.1);

In [126]:
float_arr

array([2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. ])

In [127]:
float_arr.dtype

dtype('float64')

In [128]:
arr4D=np.arange(1001,1081,2).reshape(2,1,5,4);

In [129]:
arr4D

array([[[[1001, 1003, 1005, 1007],
         [1009, 1011, 1013, 1015],
         [1017, 1019, 1021, 1023],
         [1025, 1027, 1029, 1031],
         [1033, 1035, 1037, 1039]]],


       [[[1041, 1043, 1045, 1047],
         [1049, 1051, 1053, 1055],
         [1057, 1059, 1061, 1063],
         [1065, 1067, 1069, 1071],
         [1073, 1075, 1077, 1079]]]])

In [130]:
arr4D.size

40

In [132]:
arr4D[arr4D%2==0]

array([], dtype=int32)

In [134]:
arr4D[True]

array([[[[[1001, 1003, 1005, 1007],
          [1009, 1011, 1013, 1015],
          [1017, 1019, 1021, 1023],
          [1025, 1027, 1029, 1031],
          [1033, 1035, 1037, 1039]]],


        [[[1041, 1043, 1045, 1047],
          [1049, 1051, 1053, 1055],
          [1057, 1059, 1061, 1063],
          [1065, 1067, 1069, 1071],
          [1073, 1075, 1077, 1079]]]]])

In [135]:
arr4D[arr4D<1040]

array([1001, 1003, 1005, 1007, 1009, 1011, 1013, 1015, 1017, 1019, 1021,
       1023, 1025, 1027, 1029, 1031, 1033, 1035, 1037, 1039])

In [136]:
cond=arr4D<1040;

In [137]:
cond

array([[[[ True,  True,  True,  True],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]],


       [[[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]]])

#### np.linspace() function

In [138]:
arr1=np.linspace(0,10,20);

In [139]:
arr1

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [140]:
arr1.size

20

In [144]:
arr1[1]-arr1[0]

0.5263157894736842

In [154]:
for i in range(arr1.size):
    if not i:
        continue;
    print(arr1[i]-arr1[i-1]);

0.5263157894736842
0.5263157894736842
0.5263157894736843
0.5263157894736841
0.5263157894736841
0.5263157894736845
0.5263157894736841
0.5263157894736841
0.5263157894736841
0.5263157894736841
0.5263157894736841
0.526315789473685
0.5263157894736841
0.5263157894736841
0.5263157894736841
0.5263157894736841
0.526315789473685
0.5263157894736832
0.526315789473685


In [155]:
arr2=np.linspace(0,100,20)

In [156]:
arr2

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

In [157]:
arr2.dtype

dtype('float64')

In [158]:
np.round(arr2)

array([  0.,   5.,  11.,  16.,  21.,  26.,  32.,  37.,  42.,  47.,  53.,
        58.,  63.,  68.,  74.,  79.,  84.,  89.,  95., 100.])

In [159]:
np.round(arr2,2)

array([  0.  ,   5.26,  10.53,  15.79,  21.05,  26.32,  31.58,  36.84,
        42.11,  47.37,  52.63,  57.89,  63.16,  68.42,  73.68,  78.95,
        84.21,  89.47,  94.74, 100.  ])

In [160]:
np.round(arr2,decimals=3)

array([  0.   ,   5.263,  10.526,  15.789,  21.053,  26.316,  31.579,
        36.842,  42.105,  47.368,  52.632,  57.895,  63.158,  68.421,
        73.684,  78.947,  84.211,  89.474,  94.737, 100.   ])

In [163]:
np.round(arr2,decimals=-2)

array([  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100.])

In [164]:
np.round(np.round(arr2,decimals=-1),4)

array([  0.,  10.,  10.,  20.,  20.,  30.,  30.,  40.,  40.,  50.,  50.,
        60.,  60.,  70.,  70.,  80.,  80.,  90.,  90., 100.])

### np.sort()

In [223]:
arr1=np.arange(11,1,-1)

In [224]:
arr1

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2])

In [225]:
np.sort(arr1)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [226]:
np.sort(arr1)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [227]:
arr1=np.sort(arr1)[::-1]          ## descending order

In [228]:
arr1

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2])

In [229]:
arr2=np.random.randint(low=0,high=100,size=(5,3,4));

In [230]:
arr2

array([[[41, 72, 42, 70],
        [21, 87,  0, 58],
        [49, 81, 94, 54]],

       [[20, 46, 52, 91],
        [14, 94, 72, 26],
        [80, 72, 40, 68]],

       [[46, 51, 94, 76],
        [59, 87,  8,  3],
        [49, 62, 63, 30]],

       [[29, 81, 68, 18],
        [51, 10, 43, 59],
        [94,  0, 85, 63]],

       [[67, 41, 42, 70],
        [86, 17, 55, 27],
        [22, 36, 32,  0]]])

In [231]:
print(arr2);
print(20*"*")
print(np.sort(arr2,axis=0))

[[[41 72 42 70]
  [21 87  0 58]
  [49 81 94 54]]

 [[20 46 52 91]
  [14 94 72 26]
  [80 72 40 68]]

 [[46 51 94 76]
  [59 87  8  3]
  [49 62 63 30]]

 [[29 81 68 18]
  [51 10 43 59]
  [94  0 85 63]]

 [[67 41 42 70]
  [86 17 55 27]
  [22 36 32  0]]]
********************
[[[20 41 42 18]
  [14 10  0  3]
  [22  0 32  0]]

 [[29 46 42 70]
  [21 17  8 26]
  [49 36 40 30]]

 [[41 51 52 70]
  [51 87 43 27]
  [49 62 63 54]]

 [[46 72 68 76]
  [59 87 55 58]
  [80 72 85 63]]

 [[67 81 94 91]
  [86 94 72 59]
  [94 81 94 68]]]


In [232]:
print(arr2);
print(20*"*")
print(np.sort(arr2,axis=1));

[[[41 72 42 70]
  [21 87  0 58]
  [49 81 94 54]]

 [[20 46 52 91]
  [14 94 72 26]
  [80 72 40 68]]

 [[46 51 94 76]
  [59 87  8  3]
  [49 62 63 30]]

 [[29 81 68 18]
  [51 10 43 59]
  [94  0 85 63]]

 [[67 41 42 70]
  [86 17 55 27]
  [22 36 32  0]]]
********************
[[[21 72  0 54]
  [41 81 42 58]
  [49 87 94 70]]

 [[14 46 40 26]
  [20 72 52 68]
  [80 94 72 91]]

 [[46 51  8  3]
  [49 62 63 30]
  [59 87 94 76]]

 [[29  0 43 18]
  [51 10 68 59]
  [94 81 85 63]]

 [[22 17 32  0]
  [67 36 42 27]
  [86 41 55 70]]]


In [233]:
print(arr2);
print(20*"*")
print(np.sort(arr2,axis=2))

[[[41 72 42 70]
  [21 87  0 58]
  [49 81 94 54]]

 [[20 46 52 91]
  [14 94 72 26]
  [80 72 40 68]]

 [[46 51 94 76]
  [59 87  8  3]
  [49 62 63 30]]

 [[29 81 68 18]
  [51 10 43 59]
  [94  0 85 63]]

 [[67 41 42 70]
  [86 17 55 27]
  [22 36 32  0]]]
********************
[[[41 42 70 72]
  [ 0 21 58 87]
  [49 54 81 94]]

 [[20 46 52 91]
  [14 26 72 94]
  [40 68 72 80]]

 [[46 51 76 94]
  [ 3  8 59 87]
  [30 49 62 63]]

 [[18 29 68 81]
  [10 43 51 59]
  [ 0 63 85 94]]

 [[41 42 67 70]
  [17 27 55 86]
  [ 0 22 32 36]]]


In [234]:
arr2

array([[[41, 72, 42, 70],
        [21, 87,  0, 58],
        [49, 81, 94, 54]],

       [[20, 46, 52, 91],
        [14, 94, 72, 26],
        [80, 72, 40, 68]],

       [[46, 51, 94, 76],
        [59, 87,  8,  3],
        [49, 62, 63, 30]],

       [[29, 81, 68, 18],
        [51, 10, 43, 59],
        [94,  0, 85, 63]],

       [[67, 41, 42, 70],
        [86, 17, 55, 27],
        [22, 36, 32,  0]]])

In [235]:
arr1.size

10

In [236]:
arr2.size

60

In [237]:
arr2.shape

(5, 3, 4)

In [238]:
arr2.ndim

3

In [239]:
arr2.size

60

In [241]:
arr2.reshape(2,5,6)

array([[[41, 72, 42, 70, 21, 87],
        [ 0, 58, 49, 81, 94, 54],
        [20, 46, 52, 91, 14, 94],
        [72, 26, 80, 72, 40, 68],
        [46, 51, 94, 76, 59, 87]],

       [[ 8,  3, 49, 62, 63, 30],
        [29, 81, 68, 18, 51, 10],
        [43, 59, 94,  0, 85, 63],
        [67, 41, 42, 70, 86, 17],
        [55, 27, 22, 36, 32,  0]]])

### np.expand_dims

In [242]:
arr2

array([[[41, 72, 42, 70],
        [21, 87,  0, 58],
        [49, 81, 94, 54]],

       [[20, 46, 52, 91],
        [14, 94, 72, 26],
        [80, 72, 40, 68]],

       [[46, 51, 94, 76],
        [59, 87,  8,  3],
        [49, 62, 63, 30]],

       [[29, 81, 68, 18],
        [51, 10, 43, 59],
        [94,  0, 85, 63]],

       [[67, 41, 42, 70],
        [86, 17, 55, 27],
        [22, 36, 32,  0]]])

In [244]:
np.expand_dims(arr2,axis=0)

array([[[[41, 72, 42, 70],
         [21, 87,  0, 58],
         [49, 81, 94, 54]],

        [[20, 46, 52, 91],
         [14, 94, 72, 26],
         [80, 72, 40, 68]],

        [[46, 51, 94, 76],
         [59, 87,  8,  3],
         [49, 62, 63, 30]],

        [[29, 81, 68, 18],
         [51, 10, 43, 59],
         [94,  0, 85, 63]],

        [[67, 41, 42, 70],
         [86, 17, 55, 27],
         [22, 36, 32,  0]]]])

In [246]:
np.expand_dims(arr2,axis=0).shape

(1, 5, 3, 4)

In [247]:
np.expand_dims(arr2,axis=1)

array([[[[41, 72, 42, 70],
         [21, 87,  0, 58],
         [49, 81, 94, 54]]],


       [[[20, 46, 52, 91],
         [14, 94, 72, 26],
         [80, 72, 40, 68]]],


       [[[46, 51, 94, 76],
         [59, 87,  8,  3],
         [49, 62, 63, 30]]],


       [[[29, 81, 68, 18],
         [51, 10, 43, 59],
         [94,  0, 85, 63]]],


       [[[67, 41, 42, 70],
         [86, 17, 55, 27],
         [22, 36, 32,  0]]]])

In [248]:
np.expand_dims(arr2,axis=1).shape

(5, 1, 3, 4)

In [249]:
np.expand_dims(arr2, axis=2)

array([[[[41, 72, 42, 70]],

        [[21, 87,  0, 58]],

        [[49, 81, 94, 54]]],


       [[[20, 46, 52, 91]],

        [[14, 94, 72, 26]],

        [[80, 72, 40, 68]]],


       [[[46, 51, 94, 76]],

        [[59, 87,  8,  3]],

        [[49, 62, 63, 30]]],


       [[[29, 81, 68, 18]],

        [[51, 10, 43, 59]],

        [[94,  0, 85, 63]]],


       [[[67, 41, 42, 70]],

        [[86, 17, 55, 27]],

        [[22, 36, 32,  0]]]])

In [251]:
np.expand_dims(arr2, axis=2).shape

(5, 3, 1, 4)

### np.newaxis

In [252]:
arr1

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2])

In [253]:
arr1[np.newaxis,:]

array([[11, 10,  9,  8,  7,  6,  5,  4,  3,  2]])

In [254]:
arr1[:,np.newaxis]

array([[11],
       [10],
       [ 9],
       [ 8],
       [ 7],
       [ 6],
       [ 5],
       [ 4],
       [ 3],
       [ 2]])

### np.concatenate()

In [218]:
arr1=np.arange(5);
arr2=np.arange(5);
np.concatenate((arr1,arr2))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [219]:
arr1=np.array([4,3,5,2]);
arr2=np.array([5,2,6,2]);
np.concatenate((arr1,arr2))

array([4, 3, 5, 2, 5, 2, 6, 2])

In [220]:
arr1.size

4

In [221]:
arr1.ndim

1

In [222]:
arr1.shape

(4,)